### PR TITLE
Fixes `bool` and `Literal[True, False]` subtyping, refs #11701

### LINKED ISSUE #11701: Literal[True, False] false positives within tuples
This code generates unexpected errors:

```py
from typing import NamedTuple, Literal, List, Tuple

C = NamedTuple("C", [("x", Literal[True, False])])

T = Tuple[Literal[True, False]]

# Incompatible types in assignment (expression has type "List[C]", variable has type "List[C]")
x: List[C] = [C(True)]

t: T

# Incompatible types in assignment (expression has type "List[Tuple[bool]]", 
# variable has type "List[Tuple[Union[Literal[True], Literal[False]]]]")
y: List[T] = [t]
```

The issue was introduced in #10389.

Marking as high priority since this is a regression.

cc @ethan-leba

### PR DESCRIPTION
**Pull request by sobolevn**
In some places in our code `bool` was compared with `Union[Literal[True], Literal[False]]`.
It was later compared with each union item. And `bool` is not subtype of `Literal[True]` and `Literal[False]`

Closes #11701
Refs #11705

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Awesome, thanks for this. #10389 was super useful, so glad we're fixing regressions.

Seems like this logic is coupled to `try_expanding_sum_type_to_union`, we should probably put a comment in both places

**Comment by ethan-leba** [comment]
thanks for fixing this!

**Review by JukkaL — APPROVED** [review]
Thanks!
