### PR TITLE
Narrow Any in and_conditional_map

### LINKED ISSUE #16462: Possible regression when narrowing using isinstance
**Bug Report**

Type narrowing using `isinstance` with 1.7 behaves differently from 1.6 for seemingly valid code.

**To Reproduce**

```python
import typing

class A:
    def write(self) -> str:
        return "A"

    # succeeds
    def eq1(self, other: typing.Any) -> bool:
        if other:
            if isinstance(other, self.__class__):
                return self.write() == other.write()
        return False

    # fails
    def eq2(self, other: typing.Any) -> bool:
        if other and isinstance(other, self.__class__):
            return self.write() == other.write()
        return False
```

**Expected Behavior**

The `eq1` and `eq2` should both be valid code. `eq2` fails under 1.7 but succeeded under 1.6.

**Actual Behavior**

```
file.py:15: error: Returning Any from function declared to return "bool"  [no-any-return]
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.7.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):

```
# Global options:

[mypy]
ignore_missing_imports = True
follow_imports = silent
strict = True
```

- Python version used:

Python 3.12 macos-arm64

### LINKED ISSUE #17100: Combining two type checks with `and` deduces `Any` if the first is `Any`
Combining two `isinstance` checks with `and` where the first one deduces the type to `Any` ignores the second one.

**To Reproduce**

```python
from typing import Any, reveal_type

class A: pass
class B(A): pass  
value: Any

if isinstance(value, A) and not isinstance(value, B):
    reveal_type(value)
if not isinstance(value, B) and isinstance(value, A):
    reveal_type(value)
```

https://mypy-play.net/?mypy=latest&python=3.12&gist=643066dcf62c1c2b88bb4714032fa8b5

**Expected Behavior**

Mypy should deduce the type as `A` in both cases:

```
main.py:8: note: Revealed type is "__main__.A"
main.py:10: note: Revealed type is "__main__.A"
```

**Actual Behavior**

```
main.py:8: note: Revealed type is "__main__.A"
main.py:10: note: Revealed type is "Any"
```

**Background**

This worked before mypy 1.7 and is a regression caused by #16237. The direct reason is that `Any` is now preferred in some circumstances in `and_conditional_maps()` (the `isinstance` in the `if`):

https://github.com/python/mypy/blob/80190101f68b52e960c22572ed6cc814de078b9c/mypy/checker.py#L7609-L7618

I'm not sure why this is the case or why it is needed to prefer `Any` here. Intuitively, it should be the other way around. The additional `Any` doesn't add any new information but it shouldn't destroy the information already known from other sources.

When I remove the `or isinstance(get_proper_type(m1[n1]), AnyType)` in the above code, only one testcase fails (in `testNarrowingWithAnyOps`) because it explicitly tests for this `Any` result, like this:

```
class C: ...
class D(C): ...
tp: Any
...

c1: C
if isinstance(c1, tp) and isinstance(c1, D):
    reveal_type(c1)  # N: Revealed type is "Any"
```

With the changed code this deduces the type as `D` instead.

### LINKED ISSUE #20363: type narrowing with `isinstance` does not work in combination with `and` and `or`
**Bug Report**

Type narrowing with `isinstance` doesn't happen if it's used in a conditional statement with `and` or `or`

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.13&flags=strict&gist=fb4efdf001e261dd16d2605c7488537e

```python
from typing import Any


def foo() -> str:
    a: dict[str, Any] = {"foo": "bar"}
    foo = a.get("foo")
    if foo and isinstance(foo, str):
        return foo

    return ""
```

it works if we remove the `and`:

```python
from typing import Any


def foo() -> str:
    a: dict[str, Any] = {"foo": "bar"}
    foo = a.get("foo")
    if isinstance(foo, str):
        return foo

    return ""
```

**Expected Behavior**

`isinstance` should narrow the type regardless of whether it's used in a conjunction or not

**Your Environment**

- Mypy version used: 1.18.2
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.13.9

### PR DESCRIPTION
**Pull request by hauntsaninja**
Prior to this, mypy's behaviour is inconsistent depending on the order of the condition or the presence of terms in the condition other than `isinstance`

Fixes #17100 , fixes #20363 , fixes #16462

### CODE REVIEW

**Comment by hauntsaninja** [comment]
tanjun is good, first homeassistant is good, second homeassistant is meh, ddtrace is good
