### ISSUE TITLE
[mypyc] Pickle test failure with Python 3.14.0a1

### ISSUE THREAD

**Issue by cdce8p** [python/mypy#17973]
_After being a bit late with Python 3.13, I figured to start testing 3.14 early this time._

With Python `3.14.0a1` the following fails:
```py
# native.py
from typing import Any

def dec(x: Any) -> Any:
    return x

@dec
class D:
    x: int

class E(D):
    y: int
```
```py
# driver.py
from native import D, E

import pickle

assert not hasattr(D, '__mypyc_attrs__')
assert E.__mypyc_attrs__ == ('y', '__dict__')

e = E()
e.x = 10
e.y = 20

assert e.__getstate__() == {'y': 20, '__dict__': {'x': 10}}
e2 = pickle.loads(pickle.dumps(e))
assert e is not e2 and e.x == e2.x and e.y == e2.y
```
```
rm -rf build
rm *.so
python3.14 -m mypyc native.py
python3.14 -c 'import driver.py'
```

**The error message**
```py
$ python -c "import driver.py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import driver.py
  File ".../driver.py", line 14, in <module>
    assert e is not e2 and e.x == e2.x and e.y == e2.y
                                  ^^^^
AttributeError: 'E' object has no attribute 'x'
```

I bisected this to https://github.com/python/cpython/pull/123192 upstream.

--
This is also part of the mypyc test suite
```
pytest -n0 mypyc/test/test_run.py::TestRun::run-classes.test::testPickling
```

**Comment by hauntsaninja** [comment]
With a debug Python build you also get:
```
Assertion failed: (0), function _PyObject_InlineValuesConsistencyCheck, file dictobject.c, line 7470.
zsh: abort      python driver.py
```

**Comment by cdce8p** [comment]
Still an issue with `3.14.0a2`

**Comment by cdce8p** [comment]
Still an issue with `3.14.0a3` as well.

**Comment by cdce8p** [comment]
A possible workaround could be to disable the `Py_TPFLAGS_INLINE_VALUES` here:

https://github.com/python/mypy/blob/f44a60dd9d02ce496561c08ded134d5e2e3bc8ca/mypyc/lib-rt/misc_ops.c#L299-L304

```diff
 #if PY_MINOR_VERSION == 11
     // This is a hack. Python 3.11 doesn't include good public APIs to work with managed
     // dicts, which are the default for heap types. So we try to opt-out until Python 3.12.
     t->ht_type.tp_flags &= ~Py_TPFLAGS_MANAGED_DICT;
+#elif PY_MINOR_VERSION == 14
+    t->ht_type.tp_flags &= ~Py_TPFLAGS_INLINE_VALUES;
```

With that the test case passes again (and no other test is failing because of it). However, I'm unsure that's the correct solution. With https://github.com/python/cpython/pull/123192 `Py_TPFLAGS_INLINE_VALUES` is automatically set for `type->tp_itemsize == 0` which is the case here.

**Comment by cdce8p** [comment]
From what I can tell the `testPickling` case also had issues when adding support for 3.12.
- https://github.com/python/mypy/pull/15471
- https://github.com/python/mypy/pull/15574

/CC @JukkaL

**Comment by cdce8p** [comment]
This was fixed in https://github.com/python/cpython/pull/134859 which will be included in Python 3.14.0b3.
