### ISSUE TITLE
Frozen dataclass with function fields incorrectly thinks first argument is self

### ISSUE THREAD

**Issue by wrobell** [python/mypy#10711]
Example from #5485 works with mypy 0.902

```
from dataclasses import dataclass
from typing import Callable

@dataclass
class Repro:
    fn: Callable[[int], str]

r = Repro(fn=repr)
assert "1" == r.fn(1)
```

but let's change the dataclass to a frozen one

```
from dataclasses import dataclass
from typing import Callable

@dataclass(frozen=True)
class Repro:
    fn: Callable[[int], str]

r = Repro(fn=repr)
assert "1" == r.fn(1)
```

then

```
$ mypy t.py
t.py:9: error: Invalid self argument "Repro" to attribute function "fn" with type "Callable[[int], str]"
t.py:9: error: "str" not callable
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment]
Can you repro against master? I don't think https://github.com/python/mypy/pull/10548 made it into any of the recent releases

**Comment by wrobell** [comment]
Works with mypy from master. Thanks.

**Comment by dimaqq** [comment]
Ah, would be nice to have this released! 🙏🏿

**Comment by gwerbin** [comment]
Does #10548 also fix #9489 and #10353? They both look like dupes of #5485 but I'm not totally sure if they're all subtly different in some way.

**Comment by hauntsaninja** [comment]
Yup, those should be fixed

**Comment by wrobell** [comment]
@hauntsaninja I am reopening this issue as it seems the fix fell through the crack. I checked all 0.9xx versions and the fix never went to any of the releases, it seems

https://mypy-play.net/?mypy=0.942&python=3.10&gist=ce6181fa059e3ea269f3356fd7af65be

**Comment by hauntsaninja** [comment]
Unfortunately, https://github.com/python/mypy/pull/10548 was reverted in https://github.com/python/mypy/pull/11571

**Comment by erictraut** [comment]
It looks like this fix eventually made it in. I'm not able to repro the problem with mypy 1.5, so I think this is safe to close.

**Comment by hauntsaninja** [comment]
Fixed in https://github.com/python/mypy/pull/13400
