### PR TITLE
Fix crash in match statement when subject expression have unpacked tuple

### LINKED ISSUE #21468: Crash in match-statement's subject expression with an unpacked tuple
**Crash Report**

mypy crashes when it attempts to parse a match-statement with a subject expression that consists of a tuple with an unpacked secondary tuple inside.

See the mypy playground link:
https://mypy-play.net/?mypy=latest&python=3.14&flags=show-traceback&gist=e9fee1e1ecabfc2fc0aa5fc7a326f24c

```py
foo = 0
bar = (1, 2)
match foo, *bar:
    case _:
        pass
```

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mypy/checker.py", line 765, in accept
  File "mypy/nodes.py", line 2209, in accept
  File "mypy/checker.py", line 5968, in visit_match_stmt
  File "mypy/checker.py", line 6036, in _get_recursive_sub_patterns_map
AssertionError

main.py:3: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 2.0.0
main.py:3: note: use --pdb to drop into pdb
```

**Your Environment**

- Mypy versions used: 1.20.2, 2.0.0, 2.1.0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.14.4
- Operating system and version: Arch Linux

### PR DESCRIPTION
**Pull request by EmmanuelNiyonshuti**
Fixes https://github.com/python/mypy/issues/21468

Match subject expressions containing an unpacked tuple crash mypy. This looks like a regression introduced by https://github.com/python/mypy/pull/16905, which asserts that the subject expression's items line up one-to-one with its inferred type's items. well, because starred subject expression is flattened out, the type ends up with more items than the expression.
```python
foo: int
bar: tuple[int, int]

match foo, *bar: # this `*bar` gets flattened, foo -> int, bar -> int, int. 
                 # [int, int, int] But, the expression only has two items (foo and *bar), hence we crash.
       case _: pass
```

This PR is trivial because it returns early instead of asserting, to prevent the crash. Unfortunately, this doesn't preserve narrowing for unpacked tuples in the way #16905 seems to have been heading toward. I've kept this PR scoped to just preventing this crash; narrowing can (probably will, I don't think I have the bandwidth for it right now :sweat_smile: ) be handled in a separate PR.

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks!
