### ISSUE TITLE
[1.19 regression] copy.replace doesn't work with NamedTuple anymore

### ISSUE THREAD

**Issue by loic-simon** [python/mypy#21528]
**Bug Report**

Using [`copy.replace`](https://docs.python.org/3/library/copy.html#copy.replace) on a [`NamedTuple`](https://docs.python.org/3/library/typing.html#typing.NamedTuple) produces an object that is not considered assignable to the NamedTuple type by mypy 1.19.0 and newer.

**To Reproduce**

```python
from copy import replace
from typing import NamedTuple

class NT(NamedTuple):
    foo: int

def mre(nt: NT) -> NT:
    return replace(nt, foo=3)
```

**Expected Behavior**

* 1.18.2 ([playground](https://mypy-play.net/?mypy=1.18.2&python=3.14&gist=6a2a0703452aab7090f4954a661fcf70)) : success

**Actual Behavior**

* 1.19.0 ([playground](https://mypy-play.net/?mypy=1.19.0&python=3.14&gist=6a2a0703452aab7090f4954a661fcf70)) : `main.py:10: error: Incompatible return value type (got "NT", expected "NT")  [return-value]`

Some `reveal_type`s ([playground](https://mypy-play.net/?mypy=1.19.0&python=3.14&gist=10f10a3a149b773ca5716d3fcb7e957e)):
```python
def mre(nt: NT) -> NT:
    reveal_type(nt)
    replaced = replace(nt, foo=3)
    reveal_type(replaced)
    return replaced
```
give
```
main.py:10: note: Revealed type is "tuple[builtins.int, fallback=__main__.NT]"
main.py:12: note: Revealed type is "__main__.NT"
main.py:13: error: Incompatible return value type (got "NT", expected "NT")  [return-value]
```

**Your Environment**

- Reproduced from 1.19.0 to master. I'll try to bisect it to the exact commit.
- Python version used: 3.14

**Comment by loic-simon** [comment]
Bisected to [`Sync typeshed`](https://github.com/python/mypy/commit/4936099b126f4c982c68b25208c434959d1602da)

So it looks like a typeshed problem, upsteam commit: [`Refine the copy._SupportsReplace.__replace__ signature`](https://github.com/python/typeshed/commit/91055c730ffcda6311654cf32d663858ece69bad)

**Comment by ilevkivskyi** [comment]
A self-contained test to reproduce this
```
[case testTupleTypeSelfTypeProto]
from typing import Protocol, TypeVar

R = TypeVar("R", covariant=True)

class P(Protocol[R]):
    def rep(self) -> R: ...

T = TypeVar("T")
def rep(x: P[T]) -> T: ...

class C(tuple[int, str]):
    def rep(self: T) -> T: ...

t: C
reveal_type(t)  # N: Revealed type is "tuple[builtins.int, builtins.str, fallback=__main__.C]"
reveal_type(rep(t))  # N: Revealed type is "tuple[builtins.int, builtins.str, fallback=__main__.C]"
[builtins fixtures/tuple.pyi]
```
(second reveal fails)
