### ISSUE TITLE
"yield from f()" infers wrong type for type variable

### ISSUE THREAD

**Issue by lincolnq** [python/mypy#3808]
I have the following test case on mypy 0.521: 

```py
from typing import Generator, TypeVar
T = TypeVar('T')
def f(v: T) -> Generator[None, None, T]:
    yield
    return v

def g() -> Generator[None, None, None]:
    # This works:
    gen = f(1)
    result_int = yield from gen

    # This breaks:
    result_int_2 = yield from f(1)
    # I get
    #  mypy_bug.py:13: error: Function does not return a value
    #  mypy_bug.py:13: error: Argument 1 to "f" has incompatible type "int"; expected None
```

I expected this to type-check, but instead it complains on the last line. (I'm using strict-optional, although I don't think that is essential to this example)

**Comment by gvanrossum** [comment]
Definitely a bug. I'll look into it.

**Comment by gvanrossum** [comment]
Remarkably, the bug seems to have been introduced with 074dadac7ee7c32243e414391f33208e3932d6de. (This is so old I can't even find the corresponding PR.)
