### ISSUE TITLE
Small code snippet - "possible cyclic definition"

### ISSUE THREAD

**Issue by simon-datakod** [python/mypy#15676]
**Crash Report**

Ran into what seems to be mypy gettting stuck in a cycle and then crashing. It's easy to reproduce with a small snippet of code.

**Traceback**

```
$ mypy --show-traceback test.py
Deferral trace:
    test:3
    test:3
    test:-1
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
    test:3
    test:3
    test:6
    test:6
    test:-1
test.py: error: INTERNAL ERROR: maximum semantic analysis iteration count reached
test.py:9: error: Cannot resolve name "Foo.Bar" (possible cyclic definition)  [misc]
Found 2 errors in 1 file (errors prevented further checking)
```

**To Reproduce**
```
from typing import Callable, NamedTuple

Handler = Callable[["Foo.Bar"], None]

class Foo:
    class Bar(NamedTuple):
        cmd: List[str]  # NOTE: 'List' missing from import

    def do_stuff(self, handler: Callable[["Foo.Bar"], None]) -> None:
        pass
```

**Your Environment**

- Mypy version used: mypy 0.991 (compiled: yes)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): No special config
- Python version used: Python 3.8.10
- Operating system and version: Ubuntu 20.04.6 LTS

**Comment by hauntsaninja** [comment]
This works on master, mypy 0.991 is several releases old
