### ISSUE TITLE
add test case: regression w/ mypy mis-interpreting generator comprehension

### ISSUE THREAD

**Issue by zzzeek** [python/mypy#12610]
this seems to be a regression which I am getting with mypy master @ 0df8cf532918f888610a5afd7bb88192, havent bisected to find the exact commit:

```py
from typing import Dict
from typing import Generic
from typing import List
from typing import Tuple
from typing import TypeVar
from typing import Union


class Thing:
    pass


_THING = TypeVar("_THING", bound="Thing")


class ThingCollection(Generic[_THING]):
    _collection: List[Tuple[str, _THING]]

    _index: Dict[Union[None, str, int], _THING]

    def __init__(self, t: _THING):
        self._collection = [("x", t)]
        self._index = {}

    def do_thing(self) -> None:
        self._index.update(
            (idx, c) for idx, (k, c) in enumerate(self._collection)
        )

    def do_thing_workaround(self) -> None:
        self._index.update(
            (idx, c) for idx, c in enumerate(c for (k, c) in self._collection)
        )
```

output:

```
$ mypy test3.py 
test3.py:27: error: Generator has incompatible item type "Tuple[int, Tuple[str, _THING]]"; expected "Tuple[Union[None, str, int], _THING]"  [misc]
Found 1 error in 1 file (checked 1 source file)
```

mypy seems to be mis-interpreting the first generator.   works in mypy 0.942 and pyright

**Comment by hauntsaninja** [comment]
Thanks! This bisects to the recent typeshed sync: https://github.com/python/mypy/pull/12321

Ran `mypy_primer -p test.py --bisect --new origin/master --old v0.942 --debug`

**Comment by hauntsaninja** [comment]
Looks like the following diff "fixes" it:
```
diff --git a/mypy/typeshed/stdlib/builtins.pyi b/mypy/typeshed/stdlib/builtins.pyi
index 9c5dfcfef..870ed693d 100644
--- a/mypy/typeshed/stdlib/builtins.pyi
+++ b/mypy/typeshed/stdlib/builtins.pyi
@@ -995,7 +995,7 @@ class frozenset(AbstractSet[_T_co], Generic[_T_co]):
 
 class enumerate(Iterator[tuple[int, _T]], Generic[_T]):
     def __init__(self, iterable: Iterable[_T], start: int = ...) -> None: ...
-    def __iter__(self: Self) -> Self: ...
+    def __iter__(self) -> Iterator[tuple[int, _T]]: ...
     def __next__(self) -> tuple[int, _T]: ...
     if sys.version_info >= (3, 9):
         def __class_getitem__(cls, __item: Any) -> GenericAlias: ...
```

**Comment by hauntsaninja** [comment]
Looks like I'm treading ground already covered in https://github.com/python/mypy/issues/12588

**Comment by AlexWaygood** [comment]
This was fixed by #12590, so I'm closing this (cc. @JukkaL)

**Comment by JelleZijlstra** [comment]
Could we add a test case specifically for @zzzeek's example? #12590 is pretty remote from its effect, and it would be good to get new regression tests for each bug we find.
