### ISSUE TITLE
collections.abc.Sequence considered typing.Sequence

### ISSUE THREAD

**Issue by astronouth7303** [python/mypy#6036]
```python
from collections.abc import Sequence

class Spam: pass

Sequence.register(Spam)
```

Produces this error when run through mypy:

```
test.py:5: error: "Type[Sequence[Any]]" has no attribute "register"
```

This is a regression in v0.650. This error was not produced in v0.641.

**Comment by gvanrossum** [comment]
I wonder if this is due to a change in typeshed -- I get the same error with mypy at v0.641 but typeshed at the current rev, and I don't get the error with mypy at v0.650 but typeshed at the rev it was at in the mypy 0.641 release. (I hope you follow what I'm saying here.)

If you want to help fix this, it should be easy enough to track down the precise typeshed change using `git bisect`.

**Comment by ilevkivskyi** [comment]
This is caused by PR https://github.com/python/typeshed/pull/2658, for some reasons `Sized` was the only base that has `metaclass=ABCMeta`, and now it's gone. A quick solution is to put the metaclass back where it belongs.

However, I think a better solution is automatically infer `ABCMeta` as a metaclass for protocols if no explicit metaclass is given in a class or its bases. The reason is that `Protocol` is an instance of `ABCMeta` at runtime, plus logically protocols are just fancier ABCs that type-checkers understand statically.

**Comment by ilevkivskyi** [comment]
(set priority high, since this is a regression)
