### ISSUE TITLE
mypy always fails with Python 3.10 match statement

### ISSUE THREAD

**Issue by wrobell** [python/mypy#11829]
Please consider:
```
a = 1
match a:  # type: ignore
    case 0:
        print('is zero')
    case 1:
        print('is one')
```
then
```
$ mypy t5.py
t5.py:2: error: Match statement is not supported
Found 1 error in 1 file (errors prevented further checking)
```
I would expect Mypy to ignore the whole match block.

Or is there an option I am missing, which I can pass to Mypy?

Mypy 0.930, Python 3.10.1.

**Comment by srittau** [comment]
The match statement is not yet supported in mypy. See #10191.

**Comment by wrobell** [comment]
@srittau That's OK. I am just asking Mypy to ignore match block, but it still raises the error.

It seems it could be trivial to make it to respect "type: ignore"? https://github.com/python/mypy/blob/9e34f6ac4327cc929ab6f4c4153c130242a0a149/mypy/fastparse.py#L1289-L1293

**Comment by srittau** [comment]
That indeed seems like a regression. At least in mypy 0.910, the match statement could be ignored.

**Comment by jarek-webellian** [comment]
@srittau downgraded to mypy 0.910, the error is still the same
```
$ mypy -V && mypy t5.py
mypy 0.910
t5.py:2: error: Match statement is not supported  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**Comment by MPalarya** [comment]
@srittau is there a way to properly ignore the `match` section as a temporary solution?
OP's attempt does not seem to work on either 0.910 and 0.931 versions

**Comment by srittau** [comment]
I'm not sure. I thought it had worked for me with 0.910, but when I downgraded, it failed too.

**Comment by intgr** [comment]
Looks like proper `match` support is pretty close to merging (#10191), so I guess it makes sense to just wait it out?

**Comment by JelleZijlstra** [comment]
It has been merged

**Comment by lenoqt** [comment]
When this is going to be available on pypi? I am still having issues with my build using the latest version.

**Comment by JelleZijlstra** [comment]
There are no concrete plans for the next release yet.

**Comment by JukkaL** [comment]
I'm hoping that we will have a feature release sometime in February.

**Comment by JukkaL** [comment]
This issue can be used to track progress on the next feature release which will support the match statement:
* #12021

**Comment by schlopp96** [comment]
> When this is going to be available on pypi? I am still having issues with my build using the latest version.

As have I unfortunately...

I've tried adding `# type: ignore` to various parts of code blocks just in case perhaps there was some sort of bug causing said phrase to function incorrectly or in different positions, but no dice.

**Comment by lenoqt** [comment]
> > When this is going to be available on pypi? I am still having issues with my build using the latest version.
> 
> As have I unfortunately...
> 
> I've tried adding `# type: ignore` to various parts of code blocks just in case perhaps there was some sort of bug causing said phrase to function incorrectly or in different positions, but no dice.
> 
> Are there _any_ sort of temporary fixes in the meantime, or do I just need to ignore the red squiggles in my IDE for now, lol?

I had to disable mypy until this gets released.

**Comment by gdalmau** [comment]
> As have I unfortunately...
> 
> I've tried adding `# type: ignore` to various parts of code blocks just in case perhaps there was some sort of bug causing said phrase to function incorrectly or in different positions, but no dice.
> 
> Are there _any_ sort of temporary fixes in the meantime, or do I just need to ignore the red squiggles in my IDE for now, lol?

While there is no release you can install mypy on the commit that includes this initial support for match statements:

```
pip install git+git://github.com/python/mypy.git@9b3147701f054bf8ef42bd96e33153b05976a5e1
```

The commit above is the first commit after 9b63751819d040fd78b8f37fac14e2fff6b927bc where the CI succeeds.

**Comment by jeremytwfortune** [comment]
I can absolutely appreciate that mypy needs time to support newer features. I'm confused on the choice here, though, to return an error. What is the reasoning behind classifying the result this way?

**Comment by jeremytwfortune** [comment]
Certainly agree with the warning. It would be awkward to just have mypy be silent when it can't process some syntax at all. If the fact that it raises an error was in error, that's certainly my misunderstanding of the issue here. Thanks! 👍

**Comment by SerGeRybakov** [comment]
> > As have I unfortunately...
> > I've tried adding `# type: ignore` to various parts of code blocks just in case perhaps there was some sort of bug causing said phrase to function incorrectly or in different positions, but no dice.
> > Are there _any_ sort of temporary fixes in the meantime, or do I just need to ignore the red squiggles in my IDE for now, lol?
> 
> While there is no release you can install mypy on the commit that includes this initial support for match statements:
> 
> ```
> pip install git+git://github.com/python/mypy.git@9b3147701f054bf8ef42bd96e33153b05976a5e1
> ```
> 
> The commit above is the first commit after [9b63751](https://github.com/python/mypy/commit/9b63751819d040fd78b8f37fac14e2fff6b927bc) where the CI succeeds.

It's good to have an option to install from git branch to local. But it doesn't solve pre-commit hooks problems.
Waiting for a soonest release!

**Comment by kernowalmayden** [comment]
Any updates on this? I'm using mypy 1.3.0 and this is still throwing the error
`error: Pattern matching is only supported in Python 3.10 and greater  [syntax]`

**Comment by larroy** [comment]
I still have this in mypy 1.6.1 for mac.
```error: Pattern matching is only supported in Python 3.10 and greater```

Python 3.10.13
mypy                                     1.6.1
