### ISSUE TITLE
`array` generic changes type in isinstance check

### ISSUE THREAD

**Issue by InvincibleRMC** [python/mypy#19421]
**Bug Report**

The isinstance check narrows incorrectly to `array[int]` rather than `array[float]`

**To Reproduce**

```python
from typing import Iterable, Sequence
import array

class A:
    
    @property
    def a(self) -> array.array[float]:
        return self._a
    
    @a.setter
    def a(self, input: Sequence[float]) -> None:
        if isinstance(input, array.array):
            reveal_type(input)
            self._a = input
            return

        self._a = array.array('d', input)
```

https://mypy-play.net/?mypy=latest&python=3.12&gist=369504fe046c9e0ede6abd99266d12e6

**Expected Behavior**

The isinstance should narrow correctly to `array[float]`

**Actual Behavior**

The isinstance narrows to `array[int]` which gives assignment errors.

**Your Environment**
Python 3.12
Mypy 1.16.1

**Comment by brianschubert** [comment]
Reproducer without typeshed dependency ([playground]( https://mypy-play.net/?mypy=latest&python=3.12&gist=28c7921636db3508a825e727d95a9f64&flags=warn-unreachable)):
```python
from typing import overload

class A[T]: ...

class B[T: (int, float)](A[T]):
    @overload
    def __new__(cls: type[B[int]]) -> B[int]: ...
    @overload
    def __new__(cls: type[B[float]]) -> B[float]: ...
    def __new__(cls): raise NotImplementedError
    
def foo(x: A[float]) -> None:
    if isinstance(x, B):
        reveal_type(x)  # main.py:14: note: Revealed type is "__main__.B[builtins.int]"
```
And without what looks like an int-float promotion wrinkle ([playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=76c74789a9fac261d57829492fd4b360&flags=warn-unreachable)):
```python
from typing import overload

class A[T]: ...

class B[T: (int, str)](A[T]):
    @overload
    def __new__(cls: type[B[int]]) -> B[int]: ...
    @overload
    def __new__(cls: type[B[str]]) -> B[str]: ...
    def __new__(cls): raise NotImplementedError
    
def foo(x: A[str]) -> None:
    if isinstance(x, B):  # main.py:13: error: Subclass of "A[str]" and "B[int]" cannot exist: would have inconsistent method resolution order  [unreachable]
        reveal_type(x)    # main.py:14: error: Statement is unreachable  [unreachable]
```

**Comment by sterliakov** [comment]
Furthermore, this is not the result of our typevar values "hack" either, nor a `__new__` quirk:

```python
from typing import overload

class A[T]: ...

class B[T: int | str](A[T]):
    @overload
    def __init__(self: B[int]) -> None: ...
    @overload
    def __init__(self: B[str]) -> None: ...
    def __init__(self): raise NotImplementedError
    
def foo(x: A[str]) -> None:
    if isinstance(x, B):  # E: Subclass of "A[str]" and "B[int]" cannot exist: would have inconsistent method resolution order  [unreachable]
        reveal_type(x)  # E: Statement is unreachable  [unreachable]
```

**Comment by sterliakov** [comment]
Ough, sorry, all examples are passing on master (in playground too) and work as intended. I just bisected it to my own PR #19223 and can confirm that it was supposed to fix this one... Definitely need more coffee. 

Note that we reveal `array[Any]` in the OP example, and that's by design and aligns with other cases of `isinstance` narrowing to generics.

**Comment by InvincibleRMC** [comment]
Good to see that this seems fixed on master already!
