### ISSUE TITLE
mypy got a regression while determining mixin class members

### ISSUE THREAD

**Issue by mykola-mokhnach** [python/mypy#11935]
**Bug Report**

mypy unexpectedly complains about protocol members existence in mixin classes. See the example below for more details.
I did not observe this error earlier while linting the same code.

**To Reproduce**

has_logger.py

```python
from typing import Protocol
import logging

class HasLogger(Protocol):
    @property
    def log(self) -> logging.Logger:
        ...
```

has_presets_persistence_client.py

```python
from typing import Protocol

from src.persistence.presets_client import PresetsPersistenceClient


class HasPresetsPersistenceClient(Protocol):
    @property
    def presets_persistence_client(self) -> PresetsPersistenceClient:
        ...
```

health.py

```python
import asyncio
from typing import Union, TypeVar, Dict, Coroutine, List

from aiohttp import web

from src.protocols.has_presets_persistence_client import HasPresetsPersistenceClient
from src.protocols.has_logger import HasLogger

T = TypeVar('T', bound=Union['HealthHandlerMixin', HasLogger, HasPresetsPersistenceClient])


class HealthHandlerMixin:
    async def handle_health(self: T, request: web.Request) -> web.Response:
        self.log.info('Something')
```

**Expected Behavior**

No errors from mypy linting

**Actual Behavior**

Bunch of errors similar to `health.py:163: error: Item "HealthHandlerMixin" of the upper bound "Union[HealthHandlerMixin, HasLogger, HasPresetsPersistenceClient]" of type variable "T" has no attribute "log"`

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):

```
[mypy]
python_version = 3.9
```

- Python version used: 3.9.2
- Operating system and version: macOS 12.0.1

**Comment by sobolevn** [comment]
Hi! Thanks for the report! 

It does not seem like a bug to me 🤔 
Let me explain:

```python
T = TypeVar('T', bound=Union['HealthHandlerMixin', HasLogger, HasPresetsPersistenceClient])
```

Here `T` is bound to *either* `HealthHandlerMixin`, or `HasLogger`, or `HasPresetsPersistenceClient`. But two of the classes above do not have `.log` attribute.

Do you agree?

**Comment by mykola-mokhnach** [comment]
This makes sense, but I don't see any other way to properly explain to mypy that a class (in my case `HealthHandlerMixin`) implements multiple protocols? 
I did follow https://stackoverflow.com/questions/51930339/how-do-i-correctly-add-type-hints-to-mixin-classes, although the accepted solution there proposes to enumerate missing properties explicitly under the mixin class, which defeats the purpose of multiple protocols inheritance and creates unnecessary code duplication. And the above solution with `Union` was working in mypy v 0.790, but stopped working after I bumped it to v 0.930

**Comment by sobolevn** [comment]
> but I don't see any other way to properly explain to mypy that a class (in my case HealthHandlerMixin) implements multiple protocols?

You an try creating an intermediate protocol:

```python
class HasMany(HasLogger, HasPresetsPersistenceClient): ...
```

This should do what you want 🙂

**Comment by mykola-mokhnach** [comment]
Thanks @sobolevn 

This is what I got so far:

```python
class IsMixedIntoServer(HasPresetsPersistenceClient, HasLogger):
    pass


class HealthHandlerMixin(IsMixedIntoServer):
    def _run_some_helper(self) -> None:
       pass
    
    async def handle_health(self, request: web.Request) -> web.Response:
        self.log.info('Something')
        self._run_some_helper()
```

and it looks like both mypy and the built-in PyCharm linter are happy with that solution. Thanks again for your hint.
