### ISSUE TITLE
Mypy v1.10.0 errors out when functools wraps a method

### ISSUE THREAD

**Issue by davidbrochart** [python/mypy#17166]
**Bug Report**

`mypy` v1.10.0 gives the following error, while it was working with v1.9.0:
```
test.py:13: error: Missing positional argument "self" in call to "__call__" of "_Wrapped"  [call-arg]
```

**To Reproduce**

```python
# test.py

from functools import wraps

class Foo:
    def f(self):
        pass

class Bar:
    @wraps(Foo.f)
    def f(self):
        pass

bar = Bar()
bar.f()
```
```bash
mypy test.py
```

**Expected Behavior**

There should be no error.

**Comment by AlexWaygood** [comment]
almost certainly due to https://github.com/python/mypy/pull/16942

**Comment by Hnasar** [comment]
I also hit this in a few places. Here's the relevant upstream bug https://github.com/python/typeshed/issues/10653

Workaround I used:

```python
from typing import TYPE_CHECKING

class Bar:
    def f(self):
        pass

    if not TYPE_CHECKING:
        f = wraps(Foo.f)(f)
```

**Comment by troiganto** [comment]
I've also run into this. My workaround was to use `update_wrapper()` (for which `wraps()` is a convenience wrapper) instead. This is, understandably, completely invisible to Mypy.

```py

from functools import update_wrapper

class Foo:
    def f(self):
        pass

class Bar:
    def f(self):
        pass
    update_wrapper(f, Foo.f)

bar = Bar()
bar.f()
```

**Comment by pp-mo** [comment]
We hit this too.
See: https://github.com/SciTools/iris/pull/6033

I guess this is the same problem, but it's not our _only_ usage of "wraps", so I'm not really clear why other uses seem to be OK.

**Comment by davidbrochart** [comment]
This doesn't seem to be an issue anymore.
