### PR TITLE
Fix isinstance with type aliases to PEP 604 unions

### LINKED ISSUE #11673: `isinstance` doesn't work on type aliases that use a union
```py
Foo = int | str

foo: object

isinstance(foo, Foo) # error
isinstance(foo, int | str) # no error
```
https://mypy-play.net/?mypy=master&python=3.10&gist=da37bef9ace54d59c18631a0a9f5bef2

### LINKED ISSUE #12155: Unexpected error behaviour: Parameterized generics cannot be used with class or instance checks
`mypy` reports success for
```python 
import numpy as np
x = "a"
assert isinstance(x, np.float64)
```
but fails for
```python
from numpy import float64
x = "a"
assert isinstance(x, float64)

```
with the error `fails.py:3: error: Parameterized generics cannot be used with class or instance checks`

I'm using `mypy` (0.931) and `numpy` (1.22.2).

Why do I get different results?

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #12155, fixes #11673, seems pretty commonly reported issue

### CODE REVIEW

**Review by JukkaL — COMMENTED** [review]
What about old-style unions? They work at runtime:
```
>>> from typing import Union
>>> isinstance(1, Union[int, str])
True
```
It's also okay to only support PEP 604 unions for now.

**Comment by JelleZijlstra** [comment]
Note those only work with `isinstance()` in 3.10+.

**Comment by hauntsaninja** [comment]
I'll take a look at supporting old-style unions, but in another PR. It doesn't seem to be nearly as popular a feature request and it would require monkeypatching typeshed: https://github.com/python/typeshed/issues/12137

**Comment by hauntsaninja** [comment]
This also fixes https://github.com/python/mypy/issues/13810

**Comment by ngnpope** [comment]
@hauntsaninja Unfortunately it seems this fix doesn't extend to the case where the type alias is defined in another module:

Given `a.py`:
```python
from typing import TypeAlias

IntOrStr: TypeAlias = int | str

assert isinstance(1, int | str)
assert isinstance(1, IntOrStr)
```

And `b.py`:
```python
from a import IntOrStr

assert isinstance(1, int | str)
assert isinstance(1, IntOrStr)
```

I get the following output:
```console
$ mypy --version
mypy 1.11.0 (compiled: yes)
$ mypy --strict a.py
Success: no issues found in 1 source file
$ mypy --strict b.py
b.py:4: error: Parameterized generics cannot be used with class or instance checks  [misc]
b.py:4: error: Argument 2 to "isinstance" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```
