### PR TITLE
Avoid false `unreachable`, `redundant-expr`, and `redundant-casts` warnings in loops more robustly and efficiently, and avoid multiple `revealed type` notes for the same line.

### LINKED ISSUE #18511: mypy duplicates `reveal_type` notes with partial types
**Bug Report**

There's two notes from a single `reveal_type` with a partial type in a loop.

**To Reproduce**

```python
def main() -> None:
    x = None
    while True:
        reveal_type(x)
        x = ""
```

(the outer function is only necessary to make sure a transition to `--local-partial-types` doesn't render this test case useless)

**Expected Behavior**

```
main.py:4: note: Revealed type is "Union[builtins.str, None]"
Success: no issues found in 1 source file
```

**Actual Behavior**

```
main.py:4: note: Revealed type is "None"
main.py:4: note: Revealed type is "Union[builtins.str, None]"
Success: no issues found in 1 source file
```

**Your Environment**

I assume this was caused by https://github.com/python/mypy/pull/18180. Checked on mypy playground.

- Mypy version used: master
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.12

### LINKED ISSUE #18606: [1.15 regression] (Temporary) false positive for reachability with unannotated partial type
Sort of a weird / minor case, but with mypy 1.15
```
λ cat e.py
def merge_debugs(debugs: list[int | None]) -> None:
    metadata = None
    for debug in debugs:
        if debug is not None:
            if metadata is None:
                metadata = {}

λ mypy  e.py --warn-unreachable
e.py:6: error: Need type annotation for "metadata" (hint: "metadata: dict[<type>, <type>] = ...")  [var-annotated]
e.py:6: error: Statement is unreachable  [unreachable]
Found 2 errors in 1 file (checked 1 source file)
```
If you add an annotation to `metadata` (standalone or with the assignment) the unreachable warning goes away

### LINKED ISSUE #19170: [1.16 regression] a cast is both needed and redundant at the same time
**Bug Report**

Since 1.16, [_structlog_](https://github.com/hynek/structlog#)'s package type check fails with:

```
src/structlog/stdlib.py:1160: error: Redundant cast to "MutableMapping[str, Any]"  [redundant-cast]
                ed = p(logger, meth_name, cast(EventDict, ed))
                                          ^
Found 1 error in 1 file (checked 1 source file)
```

If I remove the cast, I get:

```
src/structlog/stdlib.py:1160: error: Argument 3 has incompatible type "Mapping[str, Any] | str | bytes | bytearray | tuple[Any, ...]"; expected
"MutableMapping[str, Any]"  [arg-type]
                ed = p(logger, meth_name, ed)
                                          ^~
Found 1 error in 1 file (checked 1 source file)
```

If I add a reveal_type, I get on both 1.15 & 1.16:

```
src/structlog/stdlib.py:1160: note: Revealed type is "typing.MutableMapping[builtins.str, Any]"
src/structlog/stdlib.py:1160: note: Revealed type is "Union[typing.Mapping[builtins.str, Any], builtins.str, builtins.bytes, builtins.bytearray, builtins.tuple[Any, ...]]"
```

So I guess Mypy got somehow smarter/confused about that?

**To Reproduce**

- `git clone git@github.com:hynek/structlog.git`
- remove the `deps = mypy<1.16` line in `tox.ini`
- run `tox -e mypy-pkg`

I really tried to create a minimal reproducer, but given that I don't quite understand what's going on, I've failed.

The relevant code is here: https://github.com/hynek/structlog/blob/e941e337d312eaf256595d9d09da4542c5e94d0b/src/structlog/stdlib.py#L1160

The types are defined here: https://github.com/hynek/structlog/blob/e941e337d312eaf256595d9d09da4542c5e94d0b/src/structlog/typing.py#L61-L76

**Expected Behavior**

I would expect it to keep working, or at least decide whether or not I need the cast. 🤓

**Actual Behavior**

I don't seem to find a way to make the code pass except using Any all over the place I guess.

**Your Environment**

- Mypy version used: 1.16
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): https://github.com/hynek/structlog/blob/e941e337d312eaf256595d9d09da4542c5e94d0b/pyproject.toml#L175-L191
- Python version used: 3.13

### PR DESCRIPTION
**Pull request by tyralla**
Fixes #18606 
Closes #18511
Improves #18991
Fixes #19170

This change is an improvement over 9685171.  Besides fixing the regressions reported in #18606 and #19170 and removing the duplicates reported in #18511, it should significantly reduce the performance regression reported in #18991.  At least running `Measure-command {python runtests.py self}` on my computer (with removed cache) is 10 % faster.

### CODE REVIEW

**Comment by tyralla** [comment]
@JukkaL: I thought that later responses to `reveal_type` are always better than earlier ones.  However, this is not the case for `testNewRedefineTryStatement` test case.  Maybe the most general approach would be to collect all the union items of the individual responses and to combine them in the final note.  I could try this, if you think it's a good way to go.

Alternatively, I could just remove the `reveal_type` part of this pull request, as it seems less important than the other two addressed issues.

**Comment by tyralla** [comment]
I implemented a collection mechanism for the types revealed in different iteration steps.  In the case of unions, the items are sorted alphabetically without differentiating upper and lower case letters.

At first glance, the reason for the Mypy primer diff (https://github.com/pydata/xarray) is not clear to me.

I asked for a review of those who opened the mentioned issues.  Thanks in advance!

**Comment by tyralla** [comment]
@sterliakov: Thanks, good to know.   (Anybody already working on it?)

File: mypy/checker.py [hunk 1]
```diff
@@ -600,19 +600,23 @@ def accept_loop(
...
             while True:
                 with self.binder.frame_context(can_skip=True, break_frame=2, continue_frame=1):
                     if on_enter_body is not None:
                         on_enter_body()
 
-                    self.accept(body)
+                    # We collect errors that indicate unreachability or redundant expressions
+                    # in the first iteration and remove them in subsequent iterations if the
+                    # related statement becomes reachable or non-redundant due to changes in
+                    # partial types:
```
Comment (A5rocks) [inline mypy/checker.py:612]: What if an unreachable statement is within another unreachable statement?

**Review by A5rocks — COMMENTED** [review]
I'm not immediately convinced this is robust!

File: mypy/checker.py (hunk 1 above)
Comment (tyralla) [reply mypy/checker.py:612]: I am not exactly sure what you are asking for. 

Is this an example that fits your question?

```python
[case testAvoidUnreachableCodeInUnreachableCodeWithPartialType]
# flags: --warn-unreachable --python-version 3.11

x = None
y = None
while x is None and y is None:
    reveal_type(x)  # N: Revealed type is "None"
    reveal_type(y)  # N: Revealed type is "None"
    if x is None and y is not None:
        x = 1  # E: Statement is unreachable
        if y is None:
            y = 1

[builtins fixtures/bool.pyi]
```

In this case, the results are the same for 1.15 and the current state of this PR.

**Comment by A5rocks** [comment]
Also BTW I notice your "restart CI" commit -- you could use `git commit --allow-empty` to avoid having to push a dummy change + a revert. (just a recommendation in case you didn't know)

File: mypy/checker.py (hunk 1 above)
Comment (tyralla) [reply mypy/checker.py:612]: This example should print `b`.  Is there a typo?

Comment (tyralla) [reply mypy/checker.py]: Yes, you were totally right.  The large temporarily unreachable code section shadowed the persistent unreachable code section.  I added your test case and extended the current logic a bit.  It's late now, so I'll postpone double-checking until tomorrow. 

Can you see any more potential pitfalls?

Comment (tyralla) [reply mypy/checker.py]: I again looked at it.  To me, the logic appears a little special, but clear and straightforward.  Of course, I cannot exclude that there are more special cases my solution does not cover.  So I wait for the next review.

File: mypy/checker.py [hunk 2]
```diff
@@ -633,16 +640,29 @@ def accept_loop(
...
-                        on_enter_body()
-
-                    self.accept(body)
+            # Report only those `unreachable` and `redundant-expr` errors that could not
+            # be ruled out in any iteration step:
+            persistent_uselessness_errors = set()
+            for candidate in set(itertools.chain(*uselessness_errors)):
+                if all(
+                    (candidate in errors) or (candidate[2] in lines)
+                    for errors, lines in zip(uselessness_errors, unreachable_lines)
```
Comment (A5rocks) [inline mypy/checker.py:649]: I didn't really get this until I looked at the bug report this fixes and now I really don't get this! Why is `metadata` ever turned into a dictionary, rather than being a `None | dict[..., ...]`?

**Review by A5rocks — COMMENTED** [review]
I think the implementation makes sense, I'm just not sure what this is implementing towards is right. https://github.com/python/mypy/issues/18606 doesn't quite make sense to me; shouldn't mypy be setting `metadata` to `None | dict[..., ...]`? How could mypy think the branch is unreachable! Is mypy also not erroring if we do something that `None` doesn't support?

File: mypy/checker.py (hunk 2 above)
Comment (A5rocks) [inline mypy/checker.py:649]: Why can't this just use the last round of unreachability warnings?

Comment (A5rocks) [reply mypy/checker.py:649]: Wouldn't that case also allow something not allowed for `str`? Eg does that error for:
```py
if x is not None:
  print(x + 5)
```

Above the `reveal_type`

Comment (tyralla) [reply mypy/checker.py:649]: Oh, after re-reading, it seems that I have not hit the point of your question.   Another try: There might be some scope for optimisations.  However, I am unsure what can possibly happen when running Mypy with different configurations (like in the `f4` example discussed above), so I preferred to implement this part of the approach as robustly as possible.

Comment (A5rocks) [reply mypy/checker.py:649]: well there seems to be a bug in your logic anyways (I can't see where, it looks right to me):
```py
def f4() -> None:
    while int():
        try:
            x = 1
            if int():
                x = ""
                break
            if int():
                while int():
                    if int():
                        x = None
                        break
        finally:
            if isinstance(x, str):
                print("hello :)")  # E: Statement is unreachable
            reveal_type(x) # N: Revealed type is "Union[builtins.int, builtins.str, None]"
```

Anyways, turns out I was wrong about mypy only erroring in the final cycle. But the above bug should be enough for now and IMO a type becoming a subtype at the same place in the code seems like a bug.

@JukkaL since maybe some of my other assumptions are wrong. Do you think that looping over code multiple times but with subtypes should be considered a bug?

Comment (tyralla) [reply mypy/checker.py:649]: Are you certain? This is what I get: 

```python
# flags: --allow-redefinition-new --local-partial-types

def f4() -> None:
    while int():
        try:
            x = 1
            if int():
                x = ""
                break
            if int():
                while int():
                    if int():
                        x = None
                        break
        finally:
            if isinstance(x, str):
                reveal_type(x)  # N: Revealed type is "builtins.str"
            reveal_type(x)  # N: Revealed type is "Union[builtins.int, builtins.str, None]"
```

(I had to add `isinstance` to `exception.pyi` to get this running.)

Comment (tyralla) [reply mypy/checker.py:649]: ...I had no time for a detailed investigation yet, but I tend to think the problem with the currently discussed test case has nothing to do with this PR, because the response to `reveal_type` and the `unreachable` error for the same line happen at the same iteration step.

Maybe the first hint on the cause for this discrepancy: `expr.node.type = Union[builtins.int, builtins.str, None]` but `TypeChecker.lookup_type(expr) = Union[builtins.int, None]`.

**Comment by JukkaL** [comment]
Thanks for working on the performance regression! It would be great to measure the impact using the `misc/perf_compare.py` script. I can do this but possibly not until next week.

**Comment by tyralla** [comment]
I did not work with `misc/perf_compare.py` so far, but using it does not seem very complicated. I will try it later.

**Comment by tyralla** [comment]
@JukkaL 

I just executed `python .\misc\perf_compare.py master fix/reachability_regression`.

The results:

```
master                    10.851s (0.0%) | stdev 0.373s
fix/reachability_regression 10.044s (-7.4%) | stdev 0.423s
Total time taken by the whole benchmarking program (including any setup): 11 minutes, 32 seconds
```

So, according to this measurement, this PR achieves a speed increase of 7.4 %, while #18433 resulted in a slowdown of 8.7 %.  I am not familiar with the involved tools, but this intuitively makes sense to me and aligns roughly with my initial estimate using `Measure-command {python runtests.py self}` (which is already somewhat outdated because some details of the implementation changed).

File: mypy/checker.py (hunk 2 above)
Comment (A5rocks) [reply mypy/checker.py:650]: @JukkaL do you think types getting narrower between runs (see previous comments) should be allowed?

If not, then could this PR simply suppress *all* output and only print out the last iteration?

Comment (tyralla) [reply mypy/checker.py:650]: Maybe I misunderstand, but that sounds like reverting the "fix part" of this PR.

This is the current behaviour with the proposed changes to Mypy:

```python
y = None
while y is None:
    reveal_type(y)  # None
    if y is None:
        y = []
    y.append(1)
    reveal_type(y)  # list[int]
```

The responses to `reveal_type` are the result of the first iteration step.  In the second iteration step, the whole loop's body is unreachable.

Comment (JukkaL) [reply mypy/checker.py:650]: I think @tyralla is right, and just printing out the last iteration is not the right thing to do. I'll still need to experiment with this however.

**Comment by JukkaL** [comment]
> So, according to this measurement, this PR achieves a speed increase of 7.4 %, while https://github.com/python/mypy/pull/18433 resulted in a slowdown of 8.7 %

This looks good. The exact numbers depend on the specifics of hardware, Python version, C compiler, etc.

**Review by JukkaL — APPROVED** [review]
The seems good to me, and at least a significant improvement over the old behavior (plus it's faster!). 

@A5rocks Do you still have further concerns?

**Comment by A5rocks** [comment]
I still think this is a bug: https://github.com/python/mypy/pull/19118#discussion_r2106280582

But it's probably a bug with some other things rather than specifically the logic in this PR (mainly because the logic looks right to me). (though, what's the point of more robust logic if it cannot prevent that)

**Comment by tyralla** [comment]
@A5rocks

I appreciate your carefulness.  Still, I rethought the problem and am now very sure it is beyond the scope of this PR.   This PR only tries to correctly aggregate information that Mypy collects stepwise when analysing loops.   The bug you discovered, however, can be triggered without loops:

```python
# Mypy 1.16.0
# --allow-redefinition-new --local-partial-types --warn-unreachable
def f() -> None:
    try:
        x = 1
        if int():
            x = ""
            return
        if int():
            x = None
            return
    finally:
        reveal_type(x)  # N: Revealed type is "Union[builtins.int, builtins.str, None]" \
                        # N: Revealed type is "builtins.int"
        if isinstance(x, str):  # E: Subclass of "int" and "str" cannot exist: would have incompatible method signatures
            reveal_type(x)  # E: Statement is unreachable \
                            # E: Revealed type is "builtins.str"
        reveal_type(x) # N: Revealed type is "Union[builtins.int, builtins.str, None]" \
                       # N: Revealed type is "builtins.int"
```

This suggests that `try-finally` statements are also handled iteratively and may require similar treatment to the one we are discussing for loops in this PR.  The corresponding code  and code comments suggest the same:

https://github.com/python/mypy/blob/b025bda885027aa12965135e376a060d7582df06/mypy/checker.py#L4954-L4985

Would you like to open a separate issue?  I think I could work on it next week.
