### PR TITLE
Fix types of inherited attributes in generic dataclasses

### LINKED ISSUE #12633: Regression with generic type var inheritance
**Bug Report**
Regression added with #12590. Currently also part of the v0.950 release branch.
/CC: @JukkaL

**To Reproduce**

```py
from dataclasses import dataclass
from typing import Any, Callable, Generic, TypeVar


T = TypeVar("T")

@dataclass
class Parent(Generic[T]):
    f: Callable[[T], Any]

@dataclass
class Child(Parent[T]): ...


class A: ...
def func(obj: A) -> bool: ...

reveal_type(Child[A](func).f)
```

**Expected Behavior**

```
test.py:18: note: Revealed type is "def (mypy_tests.staging3.A) -> Any"
```

**Actual Behavior**

```
test.py:18: note: Revealed type is "def (T`1) -> Any"
test.py:18: error: Argument 1 to "Child" has incompatible type "Callable[[A], bool]"; expected "Callable[[T], Any]"
```

**Your Environment**

- Mypy version used: mypy 0.960+dev.50213b520b131fc1dd037dfcc1938beba1f4e177

### PR DESCRIPTION
**Pull request by JukkaL**
Fixes #12633.

### CODE REVIEW

**Comment by JukkaL** [comment]
mypy_primer found some regressions.

**Comment by JukkaL** [comment]
The issue is that we are performing type operations during semantic analysis, when not everything may be correctly set up. We'll need to move any type operations to a later phase. We should probably have an assertion that gets triggered if trying to perform type operations when it's not okay to do so. This would save a lot of debugging.

**Comment by cdce8p** [comment]
> mypy_primer found some regressions.

Isolated the regression with Home Assistant. Hope that helps.
```py
from __future__ import annotations
from dataclasses import dataclass
from typing import Generic, TypeVar

T = TypeVar("T")

@dataclass
class Parent2(Generic[T]):
    key: str | None = None

@dataclass
class Child2(Parent2[T]): ...


Child2(key=None)  # <-- error
```
```
error: Argument "key" to "Child2" has incompatible type "None"; expected "str"
```

**Comment by cdce8p** [comment]
The last change does resolve all dataclass regressions I saw with Home Assistant.

A bit unfortunate that `mypy_primer` didn't found them earlier but I think it might be because it doesn't install project dependencies.

**Review by jhance — APPROVED** [review]
