### ISSUE TITLE
Type narrowing broken with dict items

### ISSUE THREAD

**Issue by esceral** [python/mypy#18440]
**Bug Report**

When using a dict item, the type does not get narrowed.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.12&gist=77cccd913f6c38a3536c4306c1439cf3

**Expected Behavior**

Both functions should typecheck.

**Actual Behavior**

```
main.py:6: error: Item "int" of "int | str" has no attribute "upper"  [union-attr]
main.py:16: error: Argument 1 to "assert_never" has incompatible type "int | str"; expected "Never"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

[A workaround with an intermediate variable](https://mypy-play.net/?python=3.12&gist=306dc3cb1f4187857e26400be0884944) typechecks without issues.

**Your Environment**

- Mypy version used: 1.13.0 (initially; also tested with master, 1.14.1, 1.12.0, 1.0.0)
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.12

**Comment by tyralla** [comment]
Thanks for the report!

The first example is not a bug.  Consider this example:

```python
def a(k: str, d: dict[str, int | str]):
    if isinstance(d[k], str):
        d[k] = 1
        d[k].upper()  # clearly a crash
```

However, the second example is in fact a limitation:

```python
def b(k: str, d: dict[str, int|str]):
    match d[k]:
        case str(s):
            print(s.upper())
        case int(x):
            print(x)
        case unreachable:
            assert_never(unreachable)  # really not reachable
```

**Comment by sterliakov** [comment]
And the second part happens because only calls are currently considered "special enough", and an IndexExpr is not a CallExpr:

https://github.com/python/mypy/blob/106f714ad5967b82dcacd965c46fe6bbff38c05d/mypy/checker.py#L5272-L5284

That was introduced in #16503. I guess it should be possible to rewrite that name generation logic to make it work with any expression, not only a simple call.

**Comment by tyralla** [comment]
@sterliakov: Cool, do you plan to extend "this hack"?  I was starting to do it, but only have the test case so far:

```python
# flags: --warn-unreachable

from typing import Dict, Union

m: Dict[str, Union[int, str]]
k: str

match m[k]:
    case str(s):
        reveal_type(s)  # N: Revealed type is "builtins.str"
    case int(i):
        reveal_type(i)  # N: Revealed type is "builtins.int"
    case u:
        u

[builtins fixtures/dict.pyi]
```

Feel free to take it, if this small snippet seems useful.

**Comment by sterliakov** [comment]
@tyralla yep, I'll try to get this done soon. I think I can (at a reasonably low cost of just keeping a last_used_id per `TypeChecker`) handle that for arbitrary expressions in `match` without trying to specialize for any specific one. That would also allow narrowing of immediately-constructed tuples/lists/dicts/sets (with tuple being probably the most popular pattern), and maybe some other expressions I didn't think of yet.

We can also try to extend this spaghetti one-by-one for call, index, tuple, list, ... expressions, but I don't think it's the most ergonomic solution. This id shouldn't ever leak to error messages, so IMO just `f"dummy-match-{self.last_used_id}"` is a perfect candidate.

**Comment by injust** [comment]
Here's another test case, which doesn't use `dict`:

```python
from enum import Enum, auto


class Thing(Enum):
    ONE = auto()
    TWO = auto()


def test(name: str) -> None:
    match Thing[name]:
        case Thing.ONE:
            pass
        case Thing.TWO:
            pass
```

It's a simplified version of what I reported in https://github.com/python/mypy/issues/18875.
