### ISSUE TITLE
`mypyc` crash: `AttributeError: 'ASTConverter' object has no attribute 'visit_Match'`

### ISSUE THREAD

**Issue by goodboy** [python/mypy#13650]
```python
(xonsh310)  >>> mypyc piker/clearing/_paper_engine.py
/home/goodboy/repos/piker/build/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
piker/clearing/_paper_engine.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "/home/goodboy/repos/piker/build/setup.py", line 5, in <module>
    ext_modules=mypycify(['piker/clearing/_paper_engine.py'], opt_level="3"),
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypyc/build.py", line 487, in mypycify
    groups, group_cfilenames = mypyc_build(
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypyc/build.py", line 400, in mypyc_build
    group_cfiles, ops_text = generate_c(all_sources, options, groups, fscache,
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypyc/build.py", line 186, in generate_c
    result = emitmodule.parse_and_typecheck(
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypyc/codegen/emitmodule.py", line 173, in parse_and_typecheck
    result = build(sources=sources,
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 2644, in dispatch
    graph = load_graph(sources, manager)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 2802, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager,
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 1888, in __init__
    self.parse_file()
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 2016, in parse_file
    with self.wrap_context():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 1955, in wrap_context
    yield
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 2046, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source,
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/build.py", line 788, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/parse.py", line 25, in parse
    return mypy.fastparse.parse(source,
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 168, in parse
    ).visit(ast)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 496, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 514, in visit_AsyncFunctionDef
    return self.do_func_def(n, is_coroutine=True)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 607, in do_func_def
    self.as_required_block(n.body, lineno),
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 807, in visit_AsyncFor
    self.as_required_block(n.body, n.lineno),
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 797, in visit_For
    self.as_required_block(n.body, n.lineno),
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 797, in visit_For
    self.as_required_block(n.body, n.lineno),
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/goodboy/.virtualenvs/xonsh310/lib/python3.10/site-packages/mypy/fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'
piker/clearing/_paper_engine.py: : note: use --pdb to drop into pdb
```
Pretty sure this is some kinda pure internal error?

**To Reproduce**

ran `mypyc` on a module with async code?

**Your Environment**

- Mypy version used: see above tb
- Mypy command-line flags: see above tb
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.7
- Operating system and version: 5.19.7-arch1-1

**Comment by AlexWaygood** [comment]
Mypy 0.910 is quite old. Many bugfixes have been merged since that release. Does this crash reproduce on mypy 0.971?

**Comment by goodboy** [comment]
Seems to be a release bug since [current code has this method?](https://github.com/python/mypy/blob/130e1a4e6fc5b14fda625495e25abd177af61bbb/mypy/fastparse.py#L1649)

**Comment by goodboy** [comment]
@AlexWaygood will check now 👍🏼

**Comment by goodboy** [comment]
heyyoo, yup seems to have worked on `0.971`..

Sorry for the noise!
