### PR TITLE
[mypyc] Improve support for compiling singledispatch

### PR DESCRIPTION
**Pull request by pranavrajpal**
This makes several improvements to the support for compiling singledispatch that was introduced in #10753 by:
- Making sure registered implementations defined later in a file take precedence when multiple overlap (33798df28aaac5f3a925c3476abde15e11eb02c7)
- Using non-native calls to registered implementations to allow for adding other decorators to registered functions (099b047ea074a1ddeea434d55f4e30e9ca6384d1)
- Creating a separate function that dispatches to the correct implementation instead of adding code to dispatch to one of the registered implementations directly into the main singledispatch function, allowing the main singledispatch function to be a generator (59555e4b83de93f189c86c3198ea531c9def9ad5)
- Avoiding a compilation error when trying to dispatch on an ABC (2d404216ea2cabfc28238546652ad6fd76f6631b)

## Test Plan

I extended the `testErrorOutput` test in commandline.test, added a few tests to run-singledispatch.test, and changed some of the existing tests in run-singledispatch.test from xfails to regular tests.

### CODE REVIEW

File: mypyc/irbuild/function.py [hunk 1]
```diff
@@ -313,6 +315,20 @@ def c() -> None:
...
+        # create a dispatch function (a function that checks the first argument type and dispatches
+        # to the correct implementation)
+        builder.enter()
+        assert isinstance(fitem, FuncDef)
+        generate_singledispatch_dispatch_function(builder, fn_info.name, fitem)
+        args, _, blocks, _, fn_info = builder.leave()
+        dispatch_name = decorator_helper_name(name) if is_decorated else name
+        func_decl = FuncDecl(dispatch_name, None, builder.module_name, sig)
+        dispatch_func_ir = FuncIR(func_decl, args, blocks)
+        return dispatch_func_ir, None
```
Comment (msullivan) [inline mypyc/irbuild/function.py:330]: Do you think this would be cleaner if we pulled it out into another function? (The answer could be no)

**Review by msullivan — APPROVED** [review]
Looks good. Look into my one question and we can merge

File: mypyc/irbuild/function.py (hunk 1 above)
Comment (pranavrajpal) [reply mypyc/irbuild/function.py:330]: It probably would be cleaner. I'll move it into another function.
