### PR TITLE
Ignore promotions when simplifying unions

### LINKED ISSUE #6060: mypy fails to narrow Union[float,int] to float after isinstance(x, float)
Mypy fails to typecheck the following valid code:

```python
from typing import Union
def maybe_convert_to_int(x: Union[float,int]) -> Union[float,int]:
    '''Convert x from float to int if it can be done losslessly.'''
    if isinstance(x, float):
        # x must be a float here, so this is a legal operation, but
        # mypy still thinks its type is Union[float,int]
        assert isinstance(x, float)
        if x.is_integer():
            x = int(x)
    return x
```

When I run mypy on it, I get:

```
$ mypy ~/temp/test_mypy.py
temp/test_mypy.py:8: error: Item "int" of "Union[float, int]" has no attribute "is_integer"
$ python --version
Python 3.7.1
$ mypy --version
mypy 0.650
```

I would expect this program to pass the type checker, since I am using `isinstance` to narrow the type to float before performing the float-specific operation `float.is_integer`. If I replace the assertion with `x = float(x)`, that satisfies the type checker.

### LINKED ISSUE #12824: Invalid handling type narrowing with inf/float due to duck typing
**Bug Report**

Due to [duck typing](https://mypy.readthedocs.io/en/stable/duck_type_compatibility.html#duck-type-compatibility) handling type narrowing within a function accepting both int and float (even explicitly) doesn't work correctly.

**To Reproduce**
Consider this code, that actually leads to a type error

```python
from typing import NewType

Euro = NewType("Euro", float)

def to_eur(user_in: int | float | str) -> Euro:
    reveal_type(user_in) # int | float | str as expected
    if isinstance(user_in, float):
        reveal_type(user_in) # float
        return Euro(user_in)
    reveal_type(user_in) # str, but expected str | int
    converted = float(user_in.rstrip("€"))
    return Euro(converted)
    

print(to_eur(10))  # Raises type error as int has no method rstrip
```

**Expected Behavior**
I would expect that MyPy would warn me and that the expected reveal_type after the the isinstance call is `int | float`
This should be even the case, if `int` is not explicitly given.

Consider the modification of above:

```python
from typing import NewType

Euro = NewType("Euro", float)

def to_eur(user_in: float | str) -> Euro:
    reveal_type(user_in) # float | str as expected
    if isinstance(user_in, float):
        reveal_type(user_in) # float
        return Euro(user_in)
    reveal_type(user_in) # str
    converted = float(user_in.rstrip("€"))
    return Euro(converted)
    

print(to_eur(10))   # Raises type error as int has no method rstrip
```
would still raise a runtime type error and no typing error at all.

Also handling all duck types explicitly as unions when type narrowing would probably handle the non reachable bugs described in
#12643.
This is also suggested in #11516

**Actual Behavior**
No error / warning raised by MyPy

**Your Environment**

See [MyPy Playground](https://mypy-play.net/?mypy=latest&python=3.10&flags=strict%2Cstrict-equality%2Cwarn-incomplete-stub%2Cwarn-redundant-casts%2Cwarn-return-any%2Cwarn-unreachable%2Cwarn-unused-configs%2Cwarn-unused-ignores&gist=d92c6b0d410e37de179fb11d1a342337)

- Mypy version used: 0.950
- Mypy command-line flags: no
- Python version used: 3.10
- Operating system and version: Fedora/Online

Maybe related issues:
https://github.com/python/mypy/issues/11511

### LINKED ISSUE #13760: mypy 0.981 does not simplify unions for assert_type
**Bug Report**

Code below works fine with 0.971, but fails with 0.981.  It seems that 0.971 did type narrowing on contents of a `Union`, but 0.981 doesn't do it consistently.

**To Reproduce**

```python
from typing import Union
from typing_extensions import reveal_type, assert_type

from datetime import date, datetime, timedelta

Scalar = Union[str, bytes, date, datetime, timedelta, bool, complex]


def reduce_it(s: Scalar) -> Scalar:
    return s


reveal_type(reduce_it(20))
reveal_type(reduce_it(True))

assert_type(reduce_it(True), Scalar)

```

**Expected Behavior**

Version 0.971 output:
```text
mypysubclass.py:13: note: Revealed type is "Union[builtins.str, builtins.bytes, datetime.date, datetime.timedelta, builtins.complex]"
mypysubclass.py:14: note: Revealed type is "Union[builtins.str, builtins.bytes, datetime.date, datetime.timedelta, builtins.complex]"
```

**Actual Behavior**

Version 0.981 output:
```text
mypysubclass.py:13: note: Revealed type is "Union[builtins.str, builtins.bytes, datetime.date, datetime.timedelta, builtins.complex]"
mypysubclass.py:14: note: Revealed type is "Union[builtins.str, builtins.bytes, datetime.date, datetime.timedelta, builtins.complex]"
mypysubclass.py:16: error: Expression is of type "Union[str, bytes, date, timedelta, complex]", not "Union[str, bytes, date, datetime, timedelta, bool, complex]"
```

**Your Environment**

- Mypy version used:  0.981
- Mypy command-line flags:   None
- Mypy configuration options from `mypy.ini` (and other config files):   None
- Python version used:   3.10.4

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes #13760 
Fixes #6060
Fixes #12824

This is a right thing to do, but let's what `mypy_primer` will be. This also required re-applying #6181 (which is also a right thing to do) otherwise some tests fail.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
Few new errors are actually valid (and maybe actually catching actual bugs), except the one in `streamlit`. I will check if this is something new, or it was exposed by this PR.

**Comment by ilevkivskyi** [comment]
Yes, it looks like it is caused by this PR, a simple repro:
```python
x: float
if isinstance(x, int) or isinstance(x, float):
    pass
```
it worked before, but fails with this PR.

**Comment by ilevkivskyi** [comment]
Oh wait, it only happens with a `--warn-unreachable` flag. So it is in some sense correct, it warns that the first `isinstance()` will be always false.

**Comment by ilevkivskyi** [comment]
This is ready for review then.

**Review by hauntsaninja — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
@JukkaL if you have no objections, I will merge this latter today.

**Comment by Dr-Irv** [comment]
@ilevkivskyi Any sense as to when this fix will be released?

**Comment by hauntsaninja** [comment]
As part of 0.990, probably in a month or so
