### ISSUE TITLE
tuple excepts fail when one of the classes has type `Any`

### ISSUE THREAD

**Issue by ddfisher** [python/mypy#1635]
```python
from typing import Any

C = None   # type: Any
try:
    pass
except (C, Exception):
    pass
```
results in
```test.py:6: error: Exception type must be derived from BaseException```

**Comment by ddfisher** [comment]
@pdmccormick

**Comment by gvanrossum** [comment]
What's the purpose of C in the repro?

--Guido (mobile)

**Comment by ddfisher** [comment]
I made a slight editing error as I was cleaning the example up.  Fixed.

**Comment by ddfisher** [comment]
This was broken in #1610.
