### ISSUE TITLE
Regression with generic type var inheritance

### ISSUE THREAD

**Issue by cdce8p** [python/mypy#12633]
**Bug Report**
Regression added with #12590. Currently also part of the v0.950 release branch.
/CC: @JukkaL

**To Reproduce**

```py
from dataclasses import dataclass
from typing import Any, Callable, Generic, TypeVar


T = TypeVar("T")

@dataclass
class Parent(Generic[T]):
    f: Callable[[T], Any]

@dataclass
class Child(Parent[T]): ...


class A: ...
def func(obj: A) -> bool: ...

reveal_type(Child[A](func).f)
```

**Expected Behavior**

```
test.py:18: note: Revealed type is "def (mypy_tests.staging3.A) -> Any"
```

**Actual Behavior**

```
test.py:18: note: Revealed type is "def (T`1) -> Any"
test.py:18: error: Argument 1 to "Child" has incompatible type "Callable[[A], bool]"; expected "Callable[[T], Any]"
```

**Your Environment**

- Mypy version used: mypy 0.960+dev.50213b520b131fc1dd037dfcc1938beba1f4e177

**Comment by hynek** [comment]
It looks like this regression also [affects the attrs plugin](https://github.com/python-attrs/attrs/issues/960). Would it be possible to fix it for it too, please?

**Comment by JukkaL** [comment]
@hynek I'm working on it and should have a PR up soon.

**Comment by hynek** [comment]
Wonderful, thank you Jukka!

**Comment by Tinche** [comment]
@JukkaL My hero ❤️ (no sarcasm)
