### ISSUE TITLE
TypeGuard does not narrow when assignment expression

### ISSUE THREAD

**Issue by roganov** [python/mypy#17088]
**Bug Report**

In the example below, `is_str` is a type guard, but when used mypy fails to narrow the type. I'm pretty sure this happens because of the assignment expression.

**To Reproduce**
https://mypy-play.net/?mypy=latest&python=3.12&gist=42da00a72ace0a51a5d2335721877591
```python
import typing

s: str | int


def is_str(x: str | int) -> typing.TypeGuard[str]:
    return bool(
        isinstance(x, str)
        and (y if len(y := '123'.split('/')) > 1 else '')
    )


if is_str(s):
    s + ''

```

**Expected Behavior**
No mypy errors.

**Actual Behavior**

main.py:14: error: Unsupported operand types for + ("int" and "str")  [operator]
main.py:14: note: Left operand is of type "str | int"
Found 1 error in 1 file (checked 1 source file)

**Your Environment**

- Mypy version used: 1.19
- Mypy command-line flags: non
- Mypy configuration options from `mypy.ini` (and other config files): non
- Python version used: 3.12

**Comment by JelleZijlstra** [comment]
This also reproduces it:

```
import typing

s: str | int


def is_str(x: str | int) -> typing.TypeGuard[str]:
    return y


if is_str(s):
    s + ''
```

Or
```
def is_str(x: str | int) -> typing.TypeGuard[str]:
    return True + "x"
```

It (correctly) emits an error inside the TypeGuard, but then also disables the TypeGuard.

**Comment by AlexWaygood** [comment]
So there's two bugs here:
1. Mypy gets confused about a typeguard function that returns a boolean conditions if the boolean condition involves a walrus expression. It thinks that it's an invalid typeguard function when it should see it as valid.
2. If mypy sees something it deems to be an invalid typeguard function, the error "leaks" out to places where the typeguard function is called, when mypy _should_ just emit an error at the location where the typeguard function is originally defined.

**Comment by jaycle** [comment]
I just opened https://github.com/python/mypy/issues/17104, but looking at comments, they may be related.

**Comment by grayjk** [comment]
@roganov It looks like your original test case now works in 1.18.1 and 1.18.2. Can you confirm?
