### PR TITLE
Fix regression when a contextmanager yields a generic

### LINKED ISSUE #11852: mypy 0.930: regression: no longer keeping contextmanager generic return value
**Bug Report**

I bisected this, the regression was introduced in https://github.com/python/mypy/pull/11352 CC @BarnabyShearer @sobolevn 

here's a minimal case split out from `pre-commit`:

```python
import concurrent.futures
import contextlib
from typing import Callable
from typing import Generator
from typing import Iterable
from typing import TypeVar

TArg = TypeVar('TArg')
TRet = TypeVar('TRet')

@contextlib.contextmanager
def _thread_mapper(maxsize: int) -> Generator[
    Callable[[Callable[[TArg], TRet], Iterable[TArg]], Iterable[TRet]],
    None, None,
]:
    if maxsize == 1:
        yield map
    else:
        with concurrent.futures.ThreadPoolExecutor(maxsize) as ex:
            yield ex.map


def double(x: int) -> int: return x * 2

with _thread_mapper(1) as m:
    print(list(m(double, [2, 3])))
```

**To Reproduce**

1. `mypy t.py`

**Expected Behavior**

I expect it to pass (as it did with 0.920)

**Actual Behavior**

```console
$ mypy ../t.py
../t.py:25: error: Need type annotation for "m"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.930 (regression from 0.920)
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.8.10
- Operating system and version: ubuntu 20.04

### PR DESCRIPTION
**Pull request by asottile**
### Description

resolves #11852

I had to back out some of the tests added in the patch which regressed this behaviour -- once I had "fixed" them they were identical to existing tests

I added a new test to cover the behaviour that had regressed.  I had to simplify it a bit from the one in the issue due to missing fixtures

## Test Plan

automated tests in the patch itself -- the added test fails on master:

```
___________________ testContextManagerReturnsGenericFunction ___________________
[gw2] linux -- Python 3.7.12 /tmp/mypy/.tox/py37/bin/python
data: /tmp/mypy/test-data/unit/check-default-plugin.test:45:
../mypy/mypy/test/testcheck.py:140: in run_case
    self.run_case_once(testcase)
../mypy/mypy/test/testcheck.py:227: in run_case_once
    assert_string_arrays_equal(output, a, msg.format(testcase.file, testcase.line))
E   AssertionError: Unexpected type checker output (/tmp/mypy/test-data/unit/check-default-plugin.test, line 45)
----------------------------- Captured stderr call -----------------------------
Expected:
  main:26: note: Revealed type is "builtins.list[builtins.int*]" (diff)
Actual:
  main:24: error: Need type annotation for "m"  (diff)
  main:26: note: Revealed type is "builtins.list[Any]" (diff)

Alignment of first line difference:
  E: main:26: note: Revealed type is "builtins.list[builtins.int*]"
  A: main:24: error: Need type annotation for "m"
           ^
```

### CODE REVIEW

**Review by JukkaL — APPROVED** [review]
Thanks for the fix! Looks good.
