### PR TITLE
Clarify --warn-unreachable behavior for pass statements

### LINKED ISSUE #20462: Documentation: --warn-unreachable should clarify special handling of pass statements
**Documentation**
The documentation for the --warn-unreachable flag currently does not mention that unreachable blocks containing only a pass statement are silently ignored and do not trigger a warning. This creates confusion.

The current documentation lists two specific cases where unreachable statements are silenced:
- When the statement raises an error or terminates the program.
- When the statement is intentionally marked with platform/version checks.
The behavior for pass is a third, distinct case that is not documented.

Link: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable

### PR DESCRIPTION
**Pull request by brovoski69**
This PR clarifies the documentation for the `--warn-unreachable` option by explaining that unreachable `pass` statements are intentionally not reported, and adds a small example for clarity.

Fixes #20462

### CODE REVIEW

**Comment by wyattscarpenter** [comment]
This is untrue now because of https://github.com/python/mypy/pull/20488.

The test testPassAndEllipsisUnreachable is basically your example code, but the opposite behavior. That test passes, while your example code is unfortunately not automatically typechecked so nothing complains that its expectation is wrong.

For some reason, I can't replicate this on mypy-play.net to link you to some proof, even using its "master branch" setting (probably it's just not quite up-to-date). But, I pasted your example code into a local file and ran `mypy tmp.py --warn-unreachable` on it and I can confirm that on master one gets a `tmp.py:4: error: Statement is unreachable  [unreachable]`.

So, thanks for the effort, but we already obsoleted this! 😄

**Comment by buildwithsoumya** [comment]
Thanks for the detailed explanation and for checking locally, which makes sense now. I wasn’t aware of the change introduced by #20488. Agreed that this documentation update is now obsolete. Thanks for the clarification, and I appreciate the review!
