### PR TITLE
Sync typeshed

### PR DESCRIPTION
**Pull request by JukkaL**
Source commit:
https://github.com/python/typeshed/commit/4e87b9058f0908fa895076c0d9643e18be785be6

### CODE REVIEW

**Comment by JukkaL** [comment]
There's quite a lot of fallout. I will investigate the (possible) regressions and test failures later.

**Comment by AlexWaygood** [comment]
To save you some time on a few of these:

- The new `ChainMap` errors in `pydantic` and `pandera` are unfortunate. The immediate cause is the recent change to `type.__dict__` in https://github.com/python/typeshed/pull/7423. However, arguably the "true" cause  was the changes implemented further back in https://github.com/python/typeshed/issues/6042 and https://github.com/python/typeshed/pull/6044.
- The `edgedb` errors are due to https://github.com/python/typeshed/pull/7153. They were warned about them in the PR, and said they were okay with them.
- `homeassistant/util/async_.py:158: error: Item "None" of "Optional[str]" has no attribute "strip"  [union-attr]`. This is due to https://github.com/python/typeshed/pull/7210. I argued in the PR that they seem like true positives to me. The same argument applies for the `pyp` hit and the first `werkzeug` hit.
- `homeassistant/components/statistics/sensor.py:646: error: Argument "method" to "quantiles" has incompatible type "str"; expected "Literal['inclusive', 'exclusive']"  [arg-type]`. This is due to https://github.com/python/typeshed/pull/7463, and is very easily fixed by homeassistant.
- The first two `unused type: ignore` hits in `chess` are due to missing types being added to typeshed (https://github.com/python/typeshed/pull/7412, https://github.com/python/typeshed/pull/7397)
- The `sphinx/locale/__init__.py` errors are all caused by https://github.com/python/typeshed/pull/7207

**Comment by hauntsaninja** [comment]
Here's a PR that will fix several of the broken tests here: https://github.com/python/mypy/pull/12323

**Comment by graingert** [comment]
This doesn't seem right, `__anext__` Can return any Awaitable object
```
 tornado/gen.py:429: note:     Expected:
+ tornado/gen.py:429: note:         def __anext__(self) -> Coroutine[Any, Any, Any]
+ tornado/gen.py:429: note:     Got:
+ tornado/gen.py:429: note:         def __anext__(self) -> Future[Any]
+
```

**Comment by graingert** [comment]
> This doesn't seem right, `__anext__` Can return any Awaitable object
> 
> ```
>  tornado/gen.py:429: note:     Expected:
> + tornado/gen.py:429: note:         def __anext__(self) -> Coroutine[Any, Any, Any]
> + tornado/gen.py:429: note:     Got:
> + tornado/gen.py:429: note:         def __anext__(self) -> Future[Any]
> +
> ```

Being fixed here https://github.com/python/typeshed/pull/7491

**Comment by AlexWaygood** [comment]
> This doesn't seem right, `__anext__` Can return any Awaitable object
> 
> ```
>  tornado/gen.py:429: note:     Expected:
> + tornado/gen.py:429: note:         def __anext__(self) -> Coroutine[Any, Any, Any]
> + tornado/gen.py:429: note:     Got:
> + tornado/gen.py:429: note:         def __anext__(self) -> Future[Any]
> +
> ```

https://github.com/python/typeshed/pull/7491 has now been merged, so I think this particular regression has now been fixed on typeshed's master branch (thanks again for your help reviewing @graingert).

**Comment by JukkaL** [comment]
I investigated most of the remaining errors. A few things look like real regressions, but since they don't seem to cause a lot of trouble, I'm going to merge this now and file issues (or create PRs) about them afterwards (next week).
