### ISSUE TITLE
Prime number sieve with generators example doesn't work with Python 3

### ISSUE THREAD

**Issue by MattDMo** [python/mypy#1227]
On the [examples page](http://www.mypy-lang.org/examples.html), the very last example is a prime number sieve. Unfortunately, the code does not work with Python 3 (I tested it with 3.5.1 on Linux):
```
$ python3 mypy_static_typing.py 
Traceback (most recent call last):
  File "mypy_static_typing.py", line 12, in <module>
    for p in iter_primes():
  File "mypy_static_typing.py", line 7, in iter_primes
    prime = numbers.next()
AttributeError: 'itertools.count' object has no attribute 'next'
```
whereas it works fine with 2.7.11 (I commented out the `typing` import and usage). If the offending code is replaced with `next(numbers)` (or `numbers.__next__()` if you wish), there's another error:
```
AttributeError: module 'itertools' has no attribute 'ifilter'
```
In Python 3, `itertools.ifilter()` became the built-in function `filter()`. So, the code should be as follows:
```python
import itertools
from typing import Iterator

def iter_primes() -> Iterator[int]:
    numbers = itertools.count(2)
    while True:
        prime = next(numbers)
        yield prime

        numbers = filter(prime.__rmod__, numbers)

for p in iter_primes():
    if p > 1000:
        break
    print(p)
```

**Comment by ddfisher** [comment]
Good catch!  @JukkaL, is there any way for me to update the website?

@MattDMo: FYI, if you remove the usage of `typing.Iterator`, then the function signature becomes `def iter_primes():` which has no type annotations, so mypy will *not* type check the function.  (Your conclusion was right, though -- mypy type checks the program without errors in `--py2` mode if you `pip install typing`.)

**Comment by ddfisher** [comment]
Fixed (though the live site has not yet been updated) in https://github.com/JukkaL/mypy-website/commit/a79f70dccb4de51806c85dc48ecb214cf18437f0.

**Comment by ddfisher** [comment]
Thanks again for reporting this!
