### ISSUE TITLE
Foo and Union[Foo, bool] fail to unify, when working with NamedTuple and recursively typed values

### ISSUE THREAD

**Issue by mikeyhew** [python/mypy#3069]
Obviously, this example is infinitely recursive. The original code that produced the error was more complicated so I distilled it down to the simplest example that still triggers the error.

```python
from typing import Union, NamedTuple

class Foo(NamedTuple):
    bar: Union[Foo, bool]

def make_foo() -> Union[Foo, bool]:
    return Foo(make_foo())

# foo.py:7: error: Incompatible return value type (got "Foo", expected "Union[Foo, bool]")
```

Replacing the body of `make_foo` with the following does not get rid of the error, but produces an extra error which may or may not be unrelated.

```python
bar: Union[Foo, bool] = make_foo()
return Foo(bar)

# foo.py:7: error: Incompatible types in assignment (expression has type "Union[Foo, bool]", variable has type "Union[Foo, bool]")
# foo.py:8: error: Incompatible return value type (got "Foo", expected "Union[Foo, bool]")````

**Comment by gvanrossum** [comment]
Maybe it thinks that there are two different types named `Foo`?

You can debug this more by putting calls to `reveal_type()` in various places (search the mypy docs for how).

**Comment by pkch** [comment]
The changes required to fix this will likely conflict with #3025; so it's probably better to fix it either after that PR is merged in, or inside it.

**Comment by mikeyhew** [comment]
Using `reveal_type`, the types still look like they should be compatible.

```
reveal_type(make_foo)
# Revealed type is 'def () -> Union[Tuple[Union[foo.Foo, builtins.bool], fallback=foo.Foo], builtins.bool]'

reveal_type(Foo(True))
# Revealed type is 'Tuple[Union[foo.Foo, builtins.bool], fallback=foo.Foo]'
```

**Comment by ilevkivskyi** [comment]
This is also fixed by #3952 both examples now work as expected, however a warning about forward references not fully supported is (expectedly) emitted.
