### PR TITLE
'await' in non-async function is a blocking error, fixes #15339

### LINKED ISSUE #15339: 'await' in non-async function is a blocking error
await in a function (not a  async def) causes an error "errors prevented further checking".  I think the expected behavior here is to assign an error code in this case rather than to halt. 

### To Reproduce
Run the following file with "mypy example.py":

```
def bar():
    return await (coro())
```

### Expected Behavior:
MyPy does not halt checking, and it uses an error-code for "await" outside function.  

###  Actual Behavior
```
Desktop/example.py:2: error: "await" outside coroutine ("async def")
Found 1 error in 1 file (errors prevented further checking)
```

### Environment
Mypy version: 1.3.0
Python version: 3.11.3
Operating System: Ubuntu 18.04
How to install MyPy: "python3.11 -m pip install mypy"

### PR DESCRIPTION
**Pull request by gregorysantosa**
Fixes, https://github.com/python/mypy/issues/15339

Added a new error code AWAIT_NOT_ASYNC to address awaits in non-async functions as a blocking error. Then I assigned the error code to an error print in visit_await_expr and removed the blocker flag.

I modified the testInvalidComprehensionNoCrash test case within the check-async-await.test file to reflect the updated error message for await statements not located within async functions.

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Thanks for fixing this!

**Comment by AlexWaygood** [comment]
Looks like the docs build is failing on `master` as a result of this change: https://github.com/python/mypy/actions/runs/5840508131/job/15839825549

**Comment by ilevkivskyi** [comment]
I am curious why the build didn't fail on the PR, and failed only after merge on master.

**Comment by AlexWaygood** [comment]
> I am curious why the build didn't fail on the PR, and failed only after merge on master.

Because it was a very old PR, that predated the new docs check, and `master` had not been merged into the PR branch since the new docs check had been introduced

**Comment by ilevkivskyi** [comment]
OK, I see. @hauntsaninja @gregorysantosa Could you please add the docs for the new error code to unbreak master?

**Comment by hauntsaninja** [comment]
Fixed in https://github.com/python/mypy/pull/15858

**Comment by gregorysantosa** [comment]
Sorry for not replying to this, I took a break from the internet for a while. I will be more active in thsi community from here on out! Thank you.
