### PR TITLE
Fix broken refactor of awaitable generator patching

### LINKED ISSUE #21426: [2.0 regression] INTERNAL ERROR: AssertionError in visit_decorator_inner on `@types.coroutine` generator function
**Bug Report**

mypy 2.0.0 crashes with an `AssertionError` (`assert isinstance(defn.type, CallableType)`) when checking a generator function decorated with `@types.coroutine`. This is a regression: mypy 1.20.2 accepts the same code without issue. The bug also reproduces on master as of commit 11f945b504631705696901a786ef24978f58b3f7.

Originally encountered while running `mypy --ignore-missing-imports supervisor` on the [Home Assistant Supervisor](https://github.com/home-assistant/supervisor) project; the crash occurs inside the `aiodocker` dependency at [`aiodocker/jsonstream.py:21`](https://github.com/aio-libs/aiodocker/blob/main/aiodocker/jsonstream.py#L21-L32).

**To Reproduce**

```python
import types

@types.coroutine
def f():
    yield
    return 1
```

Run: `mypy tiny.py`

**Expected Behavior**

No errors. `@types.coroutine` is a stdlib decorator that turns a generator function into a coroutine; the same file checks cleanly with mypy 1.x.

**Actual Behavior**

```
tiny.py:3: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 2.0.0
tiny.py:3: note: use --pdb to drop into pdb
Traceback (most recent call last):
  File "mypy/checker.py", line 765, in accept
  File "mypy/nodes.py", line 1352, in accept
  File "mypy/checker.py", line 5716, in visit_decorator
    self.visit_decorator_inner(e)
  File "mypy/checker.py", line 5724, in visit_decorator_inner
    assert isinstance(defn.type, CallableType)
AssertionError
```

**Your Environment**

- Mypy version used: 2.0.0 (compiled: yes); confirmed working on 1.20.2
- Mypy command-line flags: none (also reproduces with `--ignore-missing-imports` and `--show-traceback`)
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.14.4

### PR DESCRIPTION
**Pull request by ilevkivskyi**
Fixes https://github.com/python/mypy/issues/21426

Fix is straightforward: make the new logic more 1:1 with the old one (which was not the case for untyped functions).

### CODE REVIEW

**Review by JukkaL — COMMENTED** [review]
It seems to regress unannotated functions -- their bodies may now be checked (but this wasn't the case in 1.20):
```
import types

@types.coroutine
def f(x):
    1 + "x"  # Error (but shouldn't be, since no annotation)
    yield
```
If I omit `@types.coroutine`, there is no error reported.

**Comment by ilevkivskyi** [comment]
Hm, this is kind of a pre-existing problem, I can reproduce this on older versions with e.g. a deferral (or otherwise force re-visiting the function). But now the issue is more prominent, because with two-phase checking every function is in some sense deferred.

Patching the `defn.type` in-place is a sketchy thing (and also all the code around awaitable generators is sketchy, but I knew about this when I started the whole two-phase checking thing).

After some thinking, we probably shouldn't do the wrapping at all for dynamic functions for consistency with regular `async def`:
```python
async def f(): ...
reveal_type(f)  # "def () -> Any", not "def () -> Coroutine[Any, Any, Any]"
```

Or vice-versa, we should wrap _both_. So what would it be? @JukkaL 

(to be clear both ways have relatively simple fixes)

**Comment by hauntsaninja** [comment]
Let's try wrapping both!

**Comment by ilevkivskyi** [comment]
> Let's try wrapping both!

OK, let's see how it works. Btw there is another quirk that needed fixing, the
```
Use "-> None" if function does not return a value
```
note is added based on some random heuristics. I made some changes to preserve the current behavior (just to minimize number of ~unrelated changes in this PR)

**Comment by ilevkivskyi** [comment]
> > Let's try wrapping both!
>
> OK, let's see how it works

It didn't really work, whatever direction I go, a whole can of worms opens. So let's just fix the regression. The PR as it is now should be strictly better than both 2.0 (no crash) and 1.20 (dynamic functions don't stop being such when deferred).

**Review by JukkaL — APPROVED** [review]

**Comment by agners** [comment]
I can confirm this fixes the issue in our code base. Thanks for picking this up!

**Review by agners — APPROVED** [review]
