### ISSUE TITLE
super().__init_subclass__() fails

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#7352]
```
$ mypy bin/insubcl.py 
bin/insubcl.py:3: error: Too few arguments for "__init_subclass__" of "object"
$ cat bin/insubcl.py 
class X:
    def __init_subclass__(cls) -> None:
        super().__init_subclass__()
$ mypy --version
mypy 0.730+dev.36fcf1d5aa0f5656ac367bc66aba6e390f82ea9a.dirty
```

This code works correctly at runtime and the latest release accepts it.

**Comment by ilevkivskyi** [comment]
I didn't check, but it is likely a regression caused by https://github.com/python/mypy/pull/7232

cc @tavianator
