### ISSUE TITLE
"error: only instance methods can be decorated with @property" is incorrect for Python 3.9 and later

### ISSUE THREAD

**Issue by zackw** [python/mypy#20067]
**Bug Report**

The code shown in the "to reproduce" section works correctly in Python 3.10 and later (and _would_ work correctly in 3.9 and later if it didn't use `inspect.get_annotations`), but triggers an unconditional error message from mypy: "Only instance methods can be decorated with `@property`".

As far as I can tell, that _was_ true in 3.8 and earlier, but that restriction was relaxed as a new feature of 3.9.  See the "Changed in 3.9" note at the end of <https://docs.python.org/3.9/library/functions.html#classmethod>, which specifically calls out `@property` as something that can now be wrapped in `@classmethod`.

This is closely related to, but not quite the same as, #2563.

**To Reproduce**

```python
from inspect import get_annotations

class BugDemo:
    @classmethod
    @property
    def permitted_keys(cls) -> frozenset[str]:
        return frozenset(get_annotations(cls).keys())

    a: str
    b: int

if __name__ == "__main__":
    print(repr(BugDemo.permitted_keys))
```

playground: https://mypy-play.net/?mypy=latest&python=3.10&gist=91eef6c76933a64774b3ac310976da27

**Expected Behavior**

This program should be considered type-correct.

**Actual Behavior**

```
$ python3.10 bug.py
frozenset({'b', 'a'})

$ mypy bug.py
bug.py:4: error: Only instance methods can be decorated with @property  [misc]

$ mypy --python-version=3.10 bug.py
bug.py:4: error: Only instance methods can be decorated with @property  [misc]
```

**Your Environment**

- Mypy version used: 1.18.2 (compiled: yes)
- Mypy command-line flags: see "actual behavior" section
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10

**Comment by sterliakov** [comment]
Allowing `@classmethod @property` was a huge mistake, only present in 3.10 (3.9 is already EOL) - this stacking was deprecated in 3.11 and removed in 3.13. [deprecation docs](https://docs.python.org/3/whatsnew/3.11.html#language-builtins) (first bullet), [removal docs](https://docs.python.org/3/whatsnew/3.13.html#builtins).

I think it's OK for mypy to unconditionally reject code that is only supported on 3.10, especially given that this behavior was considered so problematic that it was worth an immediate revert in the next major release.

**Comment by zackw** [comment]
Ugh.  I was looking at the documentation for 3.11 only (my lowest actual supported Python version is 3.11); the fact that this feature was backed out was not nearly as obvious as it should have been in the 3.11 docs (it is clear from the 3.13 documentation).

I'd suggest that the mypy error message should be revised to read "`Chaining @classmethod with @property was deprecated in 3.11 and removed in 3.13, see <https://github.com/python/cpython/issues/89519>.`"  This would make it clearer that it isn't a case of mypy being out of step with cpython.
