### ISSUE TITLE
dmypy broken after "python setup.py install"

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6028]
Running dmypy on the command line no longer works after `python setup.py install` (in a virtualenv):

```
$ dmypy
Traceback (most recent call last):
  File "/Users/jukka/venv/test2/bin/dmypy", line 11, in <module>
    load_entry_point('mypy==0.650+dev.534e549c9d1e8780ca96fb0f170977cc427e85c1', 'console_scripts', 'dmypy')()
TypeError: main() missing 1 required positional argument: 'argv'
```

This used to work in 0.640 and was broken by abd319ab80d476f14e96918d5615fa0ac5b41d75.

cc @msullivan
