### ISSUE TITLE
Incompatible import of "Literal" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")

### ISSUE THREAD

**Issue by hackaugusto** [python/mypy#8520]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
from typing import Literal
from typing_extensions import Literal
```

* What is the actual behavior/output?

No conflicts among the types

* What is the behavior/output you expect?

```
t.py:3: error: Incompatible import of "Literal" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
Found 1 error in 1 file (checked 1 source file)
```

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?

Python 3.8.1
mypy 0.761
mypy 0.770+dev.a0c5dfc88fa8780db8a3cf7b76c32e4257f218e2
mypy-extensions==0.4.3
typing-extensions==3.7.4.1

* What are the mypy flags you are using? (For example --strict-optional)

None

* If mypy crashed with a traceback, please paste
  the full traceback below.

None

**Comment by JelleZijlstra** [comment]
That error seems OK to me (it's a bit unfortunate that the `_SpecialForm` name leaks to a user-visible error message).

Why do you want this code to work? Importing the same name from two different packages outside a conditional or try-except doesn't seem useful.

**Comment by hackaugusto** [comment]
> Why do you want this code to work? Importing the same name from two different packages outside a conditional or try-except doesn't seem useful.

It happened by accident. The project has its own typing module with reexports all symbols from `typing` with a [`from typing import *`](https://github.com/raiden-network/raiden/blob/e6e17beb3245ac4792a1bf03d2933311713149a2/raiden/utils/typing.py#L2-L6).

I opened the issues mostly because this does work with py3.7 and the error surprised me when I created a new fresh venv.

**Comment by plannigan** [comment]
For anyone trying to write code using `Literal` has to older versions python, while not requiring `typing-extensions` be installed for 3.8: mypy v0.782 raised this same error when using the following pattern. However, that is no longer the case in mypy v0.790.
```
try:
    from typing import Literal
except ImportError:                                                                            
        from typing_extensions import Literal
```

Looking at the blog post for v0.790, I was not able to find anything that explicitly pointed out this change/fix.

**Comment by wbolster** [comment]
@plannigan did you manage to get it to work?

i'm also trying to use `typing.Literal`, with an *optional* fall-back to `typing_extensions.Literal`, in a code base supporting py3.6+. if possible i would like to avoid depending on `typing_extensions`.

apart from the error about `_SpecialForm`, which i also see, how would one _conditionally_ use that `Literal[...]` in annotations? as a string is the only option i guess?

(mypy 0.800)

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module

**Comment by wbolster** [comment]
yes, i'm aware of that, but as i wrote:

> if possible i would like to avoid depending on `typing_extensions`.

on second thought i cannot think of a good reason to avoid `typing_extensions`; adding such dependency won't hurt (and will likely be pulled in by other dependencies already anyway).

**Comment by plannigan** [comment]
I guess I was looking for an [ask for forgiveness](https://docs.python.org/3/glossary.html#term-eafp) instead of [look before you leap](https://docs.python.org/3/glossary.html#term-lbyl). But explicitly checking the python version will work.

**Comment by janosh** [comment]
For copy-paste convenience, @plannigan is referring to this:

```py
import sys

if sys.version_info < (3, 8):
    from typing import Literal
else:
    from typing_extensions import Literal
```

**Comment by hauntsaninja** [comment]
@janosh your conditions are the wrong way round. Consider copy-pasting from https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module

**Comment by janosh** [comment]
@hauntsaninja Oops, thanks for catching.
