### ISSUE TITLE
Mypy reports a function is "missing return statement" when unused imports are removed

### ISSUE THREAD

**Issue by eli-schwartz** [python/mypy#13667]
I know this sounds ridiculous, but I'm not sure how else to explain it. In the middle of a large refactor of code, which can be found here in its original, mypy-passing state:

https://github.com/mesonbuild/meson/blob/83d18d137dc50437a8263983e8883198c7bc41ed/mesonbuild/compilers/detect.py#L272-L352

I have a function which looks like this:

```
def _handle_exceptions(data: StuffICareAbout) -> typing.NoReturn:
    raise mesonlib.EnvironmentException(f'{data} happened and this is bad')

def detect_static_linker(env: 'Environment', compiler: Compiler) -> StaticLinker:
    data = do_stuff()
    if foo_condition:
        return StaticLinkerA()
    elif bar_condition:
        return StaticLinkerB()
    _handle_exceptions(data)
```
mypy says this is fine. `detect_static_linker()` doesn't always return, but if it doesn't return, it runs a function that is guaranteed to never return, always raise.

This somehow stops working during the course of this series of changes, which doesn't affect the high-level overview of that function: https://github.com/eli-schwartz/meson/compare/83d18d137dc50437a8263983e8883198c7bc41ed...681609624b687d660b234a9393d446a8f2f6663b

After way too much troubleshooting, and separating out parts of the commit to see what caused it, I produced the above series of commits, and...

... this commit is fingered by git bisect: https://github.com/eli-schwartz/meson/compare/fe42a1cadade94cb39e2761500a1f5849ad7d2e8...b1676e57f60c6a1fb7533096402ae5c8ff713a35

All it does is finally drop the unused imports rendered redundant by the previous commit. I don't understand how this could be possible.

Furthermore, if I run `mypy mesonbuild/compilers/detect.py`, mypy passes. If I run `./run_mypy.py`, a script that contains a list of files to check, and runs `mypy "list" "of" "files"`, it triggers the issue.

Discussion in the meson review can be seen here, in case that's interesting (two people failed to reproduce it locally at first): https://github.com/mesonbuild/meson/pull/10810#discussion_r970164045

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): https://github.com/mesonbuild/meson/blob/master/.mypy.ini
- Python version used: 3.10
- Operating system and version: Arch Linux

**Comment by hauntsaninja** [comment]
https://github.com/mesonbuild/meson/pull/10810#discussion_r970175460 sounds like there may be some mypy cache issue. This means your bisection results may be confounded. Perhaps try bisecting again with `--no-incremental` (disables cache)?

**Comment by eli-schwartz** [comment]
No luck. The command that run_mypy.py ultimately invokes, with --no-incremental stuck in there:

```
$ /usr/bin/python3 -m mypy --no-incremental mesonbuild/cmake mesonbuild/compilers mesonbuild/dependencies mesonbuild/interpreter/primitives mesonbuild/interpreterbase mesonbuild/linkers mesonbuild/scripts mesonbuild/wrap mesonbuild/arglist.py mesonbuild/backend/backends.py mesonbuild/depfile.py mesonbuild/envconfig.py mesonbuild/interpreter/compiler.py mesonbuild/interpreter/mesonmain.py mesonbuild/interpreter/interpreterobjects.py mesonbuild/interpreter/type_checking.py mesonbuild/mcompile.py mesonbuild/mdevenv.py mesonbuild/mesonlib/platform.py mesonbuild/mesonlib/universal.py mesonbuild/minit.py mesonbuild/minstall.py mesonbuild/mintro.py mesonbuild/mlog.py mesonbuild/msubprojects.py mesonbuild/modules/external_project.py mesonbuild/modules/fs.py mesonbuild/modules/gnome.py mesonbuild/modules/i18n.py mesonbuild/modules/icestorm.py mesonbuild/modules/java.py mesonbuild/modules/keyval.py mesonbuild/modules/modtest.py mesonbuild/modules/pkgconfig.py mesonbuild/modules/qt.py mesonbuild/modules/rust.py mesonbuild/modules/sourceset.py mesonbuild/modules/wayland.py mesonbuild/modules/windows.py mesonbuild/mparser.py mesonbuild/msetup.py mesonbuild/mtest.py mesonbuild/optinterpreter.py mesonbuild/programs.py run_mypy.py run_project_tests.py run_single_test.py tools docs/genrefman.py docs/refman mesonbuild/mesonlib/posix.py
mesonbuild/compilers/detect.py:160:1: error: Missing return statement
Found 1 error in 1 file (checked 173 source files)
```

The issue is still present.

Just running that single file, nothing is reported:
```
$ /usr/bin/python3 -m mypy --no-incremental mesonbuild/compilers/detect.py
Success: no issues found in 1 source file
```
Plugging this into git bisect:

```
$ git bisect start HEAD origin/master 
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[f537c308efce427ed863004331a4d67aa7db3c4b] compilers: remove dead code
$ git bisect run /usr/bin/python3 -m mypy --no-incremental mesonbuild/cmake mesonbuild/compilers mesonbuild/dependencies mesonbuild/interpreter/primitives mesonbuild/interpreterbase mesonbuild/linkers mesonbuild/scripts mesonbuild/wrap mesonbuild/arglist.py mesonbuild/backend/backends.py mesonbuild/depfile.py mesonbuild/envconfig.py mesonbuild/interpreter/compiler.py mesonbuild/interpreter/mesonmain.py mesonbuild/interpreter/interpreterobjects.py mesonbuild/interpreter/type_checking.py mesonbuild/mcompile.py mesonbuild/mdevenv.py mesonbuild/mesonlib/platform.py mesonbuild/mesonlib/universal.py mesonbuild/minit.py mesonbuild/minstall.py mesonbuild/mintro.py mesonbuild/mlog.py mesonbuild/msubprojects.py mesonbuild/modules/external_project.py mesonbuild/modules/fs.py mesonbuild/modules/gnome.py mesonbuild/modules/i18n.py mesonbuild/modules/icestorm.py mesonbuild/modules/java.py mesonbuild/modules/keyval.py mesonbuild/modules/modtest.py mesonbuild/modules/pkgconfig.py mesonbuild/modules/qt.py mesonbuild/modules/rust.py mesonbuild/modules/sourceset.py mesonbuild/modules/wayland.py mesonbuild/modules/windows.py mesonbuild/mparser.py mesonbuild/msetup.py mesonbuild/mtest.py mesonbuild/optinterpreter.py mesonbuild/programs.py run_mypy.py run_project_tests.py run_single_test.py tools docs/genrefman.py docs/refman mesonbuild/mesonlib/posix.py
[...]
b1676e57f60c6a1fb7533096402ae5c8ff713a35 is the first bad commit
```

Still says that it's all the fault of https://github.com/eli-schwartz/meson/commit/b1676e57f60c6a1fb7533096402ae5c8ff713a35
