### ISSUE TITLE
Mypy with pydantic

### ISSUE THREAD

**Issue by andree0** [python/mypy#15675]
**Crash Report**

Mypy 1.4.1 not working with pydantic plugin, but 1.3.0 version working.
------

/home/andrzej/.pyenv/versions/3.11.4/envs/KRZ-3/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.4.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6451, in accept
  File "mypy/nodes.py", line 1139, in accept
  File "mypy/semanal.py", line 1582, in visit_class_def
  File "mypy/semanal.py", line 1667, in analyze_class
  File "mypy/semanal.py", line 1694, in analyze_class_body_common
  File "mypy/semanal.py", line 1777, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 129, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 262, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 441, in pydantic.mypy.PydanticModelTransformer.add_construct_method
TypeError: __init__() missing required argument 'default' (pos 6)
/home/andrzej/.pyenv/versions/3.11.4/envs/KRZ-3/lib/python3.11/site-packages/pydantic/env_settings.py:22: : note: use --pdb to drop into pdb

**To Reproduce**
- Create environment with python 3.11.4. You can use pyenv https://github.com/pyenv/pyenv#automatic-installer
- Install pydantic and mypy `pip install pydantic mypy`
- Add `pyproject.toml` file with config for mypy.
- Run mypy `mypy .`

**Your Environment**

- Mypy version used: `1.4.1`
- Mypy command-line flags: `.` or `--install-types .`
- Mypy configuration options from `pyproject.toml`:
```
[tool.mypy]
    python_version = "3.11"
    ignore_missing_imports = true
    strict_optional = false
    show_traceback = true
    pretty = true
    plugins = [
        "pydantic.mypy",
    ]
    exclude = [
        "lib",
        "venv", # gitlab ci
        ".venv",
    ]
[tool.pydantic-mypy]
    init_forbid_extra = true
    init_typed = true
    warn_required_dynamic_aliases = true
```
- Python version used: `3.11.4`
- Operating system and version:
```
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Comment by JelleZijlstra** [comment]
This is a bug in the mypy plugin that pydantic ships. I believe it was already fixed; you need to upgrade pydantic.

**Comment by AlexWaygood** [comment]
(Duplicate of #15485, #15492 and #15573)

**Comment by andree0** [comment]
works with pydantic 1.10.11, I run with 1.10.1 before
