### ISSUE TITLE
Error checking SimpleXMLRPCServer.register_function arguments

### ISSUE THREAD

**Issue by dbertouille** [python/mypy#8937]
* Are you reporting a bug, or opening a feature request?
Bug Report

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from xmlrpc.server import SimpleXMLRPCRequestHandler, SimpleXMLRPCServer
  
def f():
        pass


server = SimpleXMLRPCServer(
        ('127.0.0.1', 5000),
        requestHandler=SimpleXMLRPCRequestHandler,
        allow_none=True,
)
server.register_function(function=f)
```
* What is the actual behavior/output?

test.py:12: error: Argument "function" to "register_function" of "SimpleXMLRPCDispatcher" has incompatible type "Callable[[], Any]"; expected "Optional[_DispatchProtocol]"

* What is the behavior/output you expect?

No errors.

* What are the versions of mypy and Python you are using?

I've tried with Python versiond 3.5.9 and 3.7.7.

This error only started to appear after upgrading mypy to 0.780. Reverting to mypy 0.770 resolved the issue. 

* What are the mypy flags you are using? (For example --strict-optional)

`--ignore-missing-imports`
