### PR TITLE
Filter overload items based on self type during type inference

### LINKED ISSUE #15031: shutil.copyfileobj stopped working in 1.2.0
**Bug Report**

MyPy 1.2.0 doesn't like `shutil.copyfileobj` anymore, with "can't infer type argument 1".

Hit in https://github.com/pypa/cibuildwheel/pull/1468.

**To Reproduce**

```python
import shutil
import typing

stdin = typing.cast(typing.IO[bytes], None)
with open("random_file.txt", "rb") as from_file:
    shutil.copyfileobj(from_file, stdin)
```

**Expected Behavior**

```console
$ pipx run mypy==1.1.1 --strict tmp.py
Success: no issues found in 1 source file
```

https://mypy-play.net/?mypy=1.1.1&python=3.11&gist=7f9fbe8e5df5f52e5c639e30671eb208

**Actual Behavior**

```console
$ pipx run mypy==1.2.0 --strict tmp.py
tmp.py:6: error: Cannot infer type argument 1 of "copyfileobj"  [misc]
Found 1 error in 1 file (checked 1 source file)
```

https://mypy-play.net/?mypy=latest&python=3.11&gist=dbc914004646a0c0ad90926c501d1daa

**Your Environment**

- Mypy version used: 1.1.1 & 1.2.0
- Mypy command-line flags: (Seen in playground with nothing)
- Mypy configuration options from `mypy.ini` (and other config files): (Seen in playground with nothing)
- Python version used: 3.11 and others.

### LINKED ISSUE #17863: Regression: IO[str] not compatible with SupportsWrite[AnyStr]
This code generates a false positive, but type checked cleanly on mypy 1.11:
```py
from typing import IO
from shutil import copyfileobj

f: IO[str]
copyfileobj(f, f)  # Cannot infer type argument 1 of "copyfileobj"
```
I believe the reason is that the definition of `IO.write` changed in typeshed, and this triggered a mypy bug. Here's how `IO.write` is currently defined:
```py
class IO(Iterator[AnyStr]):
    ...
    @abstractmethod
    @overload
    def write(self: IO[bytes], s: ReadableBuffer, /) -> int: ...
    @abstractmethod
    @overload
    def write(self, s: AnyStr, /) -> int: ...
```

### PR DESCRIPTION
**Pull request by JukkaL**
Fix type argument inference for overloaded functions with explicit self types. Filter out the overload items based on the declared and actual types of self. The implementation is best effort and does the filtering only in simple cases, to reduce the risk of regressions (primarily performance, but I worry also about infinite recursion). I added a fast path for the typical case, since without it the filtering was quite expensive.

Note that the overload item filtering already worked in many contexts. This only improves it in specific contexts -- at least when inferring generic protocol compatibility.

This is a more localized (and thus lower-risk) fix compared to #14975 (thanks @tyralla!). #14975 might still be a good idea, but I'm not comfortable merging it now, and I want a quick fix to unblock the mypy 1.12 release.

Fixes #15031. Fixes #17863.

Co-authored by @tyralla.

### CODE REVIEW

**Comment by JukkaL** [comment]
I added a test case from #14975 by @tyralla.

**Review by ilevkivskyi — APPROVED** [review]
Yeah, looks hacky, but OK as a quick fix.

**Comment by JukkaL** [comment]
The new error in `discord.py` seems correct. We are now filtering the overloads of `list.sort` as expected.
