### PR TITLE
incremental testsuite: don't write subsequent step files until they are needed

### PR DESCRIPTION
**Pull request by nipunn1313**
### Description

This matters with namespace packages enabled - since an (otherwise) empty folder with
some .2 files in it will be considered a namespace package. This is
truer - by only writing the files at the point of the step. This helps
unblock #9636

## Test Plan

I confirmed that this helps fix some of the failures in #9636. I confirmed all preexisting tests continue to work.

### CODE REVIEW

File: test-data/unit/fine-grained-follow-imports.test [hunk 1]
```diff
@@ -638,6 +638,7 @@ import p2.m2
 p1/m1.py:1: error: "int" not callable
 main.py:2: error: Cannot find implementation or library stub for module named "p2.m2"
 main.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
+main.py:2: error: Cannot find implementation or library stub for module named "p2"
```
Comment (nipunn1313) [inline test-data/unit/fine-grained-follow-imports.test:641]: This now happens because the flags have `--namespace-packages` for this test! Before, p2 was being found as a namespace package because it contained `p2/m2.py.2`. This sort of error is happening all over the place in #9636

File: mypy/test/data.py [hunk 2]
```diff
@@ -270,11 +270,35 @@ def setup(self) -> None:
...
+
+        # Precalculate steps for find_steps()
+        steps: Dict[int, List[FileOperation]] = {}
+
         for path, content in self.files:
-            dir = os.path.dirname(path)
-            os.makedirs(dir, exist_ok=True)
-            with open(path, 'w', encoding='utf8') as f:
-                f.write(content)
+            m = re.match(r'.*\.([0-9]+)$', path)
```
Comment (nipunn1313) [inline mypy/test/data.py:278]: I moved this stuff so I could combine the `re.match` logic.
I wonder if we can totally eliminate `find_steps` and just inject the steps as an arg to `suite.run_test()`

**Review by hauntsaninja — APPROVED** [review]
Excellent!
