### PR TITLE
[mypyc] Fix __dict__ in CPython 3.11

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Fixes https://github.com/mypyc/mypyc/issues/943.

Many thanks to @kumaraditya303 for pointing me in the right direction.

### CODE REVIEW

File: mypyc/codegen/emitclass.py [hunk 1]
```diff
@@ -18,6 +19,7 @@
 from mypyc.sametype import is_same_type
 from mypyc.namegen import NameGenerator
 
+PY_3_11 = sys.version_info >= (3, 11)
```
Comment (JelleZijlstra) [inline mypyc/codegen/emitclass.py:22]: I think this isn't right: the running version of Python doesn't necessarily equal the version used at runtime. Maybe we need to emit #ifdef'ed C code instead?

Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py:22]: Oh right. Yeah my bad.

Comment (ichard26) [reply mypyc/codegen/emitclass.py]: Currently mypyc does not support cross Python version building, but yes conditional C code is better since cross version building is a future goal. The Emitter class does have the `capi_version` attribute for future reference (it's currently always set to the running version of Python).

**Comment by Fidget-Spinner** [comment]
I have no clue how/why everything is now segfaulting.

**Comment by Fidget-Spinner** [comment]
A second pair of eyes on the C code would be much appreciated :).

File: mypyc/codegen/emitclass.py (hunk 1 above)
Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py]: For some reason the ``PY_VERSION_HEX`` checks are not working (I suspect the appropriate headers aren't being included properly). So for now I'm using `capi_version` and leaving `TODO`s to use `PY_VERSION_HEX` in the future.

**Comment by Fidget-Spinner** [comment]
🎉 All the tests are green. `testProtocol` is fixed in 3.11. Leaving only `testProperty` broken in 3.11.

File: mypyc/codegen/emitclass.py [hunk 2]
```diff
@@ -698,13 +720,22 @@ def generate_traverse_for_class(cl: ClassIR,
...
+            emitter.emit_gc_visit('*((PyObject **)((char *)self + sizeof({})))'.format(
+                struct_name), object_rprimitive)
+            emitter.emit_gc_visit(
+                '*((PyObject **)((char *)self + sizeof(PyObject *) + sizeof({})))'.format(
+                    struct_name),
+                object_rprimitive)
+        else:
+            # In >=3.11, __dict__ is managed by CPython and __weakref__ lives right after
+            # the struct
+            emitter.emit_gc_visit(
```
Comment (kumaraditya303) [inline mypyc/codegen/emitclass.py:735]: Will this traverse `__dict__`? CPython relies on `subtype_traverse` in `typeobject.c` to traverse the dict, not sure how mypyc creates heap types.

Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py:735]: Wait, does `subtype_traverse` not apply to this type?

Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py:735]: I just checked the flags:
```
flags = ['Py_TPFLAGS_DEFAULT', 'Py_TPFLAGS_HEAPTYPE', 'Py_TPFLAGS_BASETYPE']
(and `Py_TPFLAGS_MANAGED_DICT`)
```
So this means the traverse function will automatically detect the dict and visit it during GC right?

Comment (kumaraditya303) [reply mypyc/codegen/emitclass.py:735]: `subtype_traverse` is only added for classes which are created by `type.__call__` and the  type metaclass's `tp_new`  but mypyc does it's custom class creation thing and does not seem to call `type()` so I am not sure.

Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py:735]: Ohh thanks you're right. Hmm in that case it's probably not being GC-ed then.

Comment (Fidget-Spinner) [reply mypyc/codegen/emitclass.py:735]: After consulting Mark, it appears that 3rd party code setting `Py_TPFLAGS_MANAGED_DICT` doesn't really have a safe way to GC its own dict.

I can think of two possible solutions:
1. Use the private `_PyObject_VisitInstanceAttributes` by including `pycore_object.h`. OR
2. Manage the dict ourselves.

**Comment by Fidget-Spinner** [comment]
This fix will only work in 3.11b5 and above. It does not work for 3.11b4. So I'm waiting for GH actions/setup-python to update to 3.11b5.

**Comment by Fidget-Spinner** [comment]
How do I make the CI use 3.11b5? @JelleZijlstra or @ichard26 do you have any idea?

**Comment by hauntsaninja** [comment]
I think it requires https://github.com/actions/python-versions/pull/180/files to be merged

**Comment by Fidget-Spinner** [comment]
This should now be ready. Thanks to everyone involved!

File: mypyc/codegen/emitclass.py [hunk 3]
```diff
@@ -257,21 +257,40 @@ def emit_line() -> None:
...
+            )
+
+            fields["tp_members"] = members_name
+            fields["tp_basicsize"] = f"{base_size} + 2*sizeof(PyObject *)"
+            fields["tp_dictoffset"] = base_size
+            fields["tp_weaklistoffset"] = weak_offset
+
+            # In CPython >=3.11, __dict__ slot is automatically set before the type. So
+            # we need to let CPython manage it.
+        else:
```
Comment (kumaraditya303) [inline mypyc/codegen/emitclass.py:280]: Move else block above comment.

**Review by kumaraditya303 — APPROVED** [review]
Not a mypyc expert but C code LGTM. I left one nit for you to consider.

File: mypyc/codegen/emitclass.py [hunk 4]
```diff
@@ -257,21 +257,40 @@ def emit_line() -> None:
...
+            # __weakref__ lives right after the struct
+            # TODO: __weakref__ should get members in the struct instead of doing this nonsense.
```
Comment (Fidget-Spinner) [inline mypyc/codegen/emitclass.py:282]:
```suggestion
        else:
            # In CPython >=3.11, __dict__ slot is automatically set before the type. So
            # we need to let CPython manage it.
            # __weakref__ lives right after the struct
            # TODO: __weakref__ should get members in the struct instead of doing this nonsense.
```

**Review by hauntsaninja — COMMENTED** [review]
Thank you! Looks like the run against Python 3.11b5 happened and this has fixed `testProtocol` and `testPickling`

**Review by hauntsaninja — APPROVED** [review]
Thanks, after reading https://github.com/python/cpython/issues/92678 this makes sense to me. I'll leave open for a couple days in case anyone else more familiar with mypyc or CPython wants to chime in :-)

File: mypyc/codegen/emitclass.py [hunk 5]
```diff
@@ -707,14 +729,27 @@ def generate_traverse_for_class(cl: ClassIR, func_name: str, emitter: Emitter) -
...
+            emitter.emit_gc_visit(
+                "*((PyObject **)((char *)self + sizeof(PyObject *) + sizeof({})))".format(
+                    struct_name
+                ),
+                object_rprimitive,
+            )
+        else:
+            # In >=3.11, __dict__ is managed by CPython and __weakref__ lives right after
+            # the struct
+            emitter.emit_line("_PyObject_VisitManagedDict((PyObject *)self, visit, arg);")
```
Comment (Fidget-Spinner) [inline mypyc/codegen/emitclass.py:748]: Wait. I need to handle the error code returned by this!

**Comment by Fidget-Spinner** [comment]
We don't need this anymore. It was fixed upstream in CPython 3.11.

**Comment by ilevkivskyi** [comment]
Hm, @Fidget-Spinner I think we may still need this PR to fix `testPickling` (the last failing test after https://github.com/python/mypy/pull/13787), see https://github.com/python/mypy/actions/runs/3165194624/jobs/5154028986

The test fails because of `__dict__` handling (looks like wrong offset on Python 3.11). I started working on my own PR, but then remembered that we had this (more thorough) one. Would you like to adapt this PR to fix that last test case?

**Comment by Fidget-Spinner** [comment]
Sorry but I'll be busy the next week, so I don't think I can work on this anytime soon.

I give full consent to copy my code in this PR for use in your PR. Just attribute it with [Co-Authored-By](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) if you do use it please.

**Comment by ilevkivskyi** [comment]
@Fidget-Spinner I tried and it looks like this approach doesn't work. The problem is that `_PyObject_VisitManagedDict` and `_PyObject_ClearManagedDict` are not public in 3.11 (I am not sure what was the reason to revert the backport, is it possible to get the "better" backport from 3.12? cc @markshannon). And even if try to vendor them and include `pycore_object.h` (which is already sketchy), I still get errors (e.g. conflicting types for `_PyObject_LookupSpecial`).

Since this used to work until 3.10, it would be great if there was a reasonable way to support this in 3.11, does anyone have any ideas?

**Comment by ilevkivskyi** [comment]
Actually after looking a bit more at this, I don't think I understand what is going on here. A simple repro mypyc test case is
```
[case test311Repro]
from typing import Any

def dec(x: Any) -> Any:
    return x

@dec
class D: pass

class E(D):
    y: int

[file driver.py]
from native import E

e = E()
e.__dict__
```
This raises an `AttributeError` on Python 3.11, while it works on Python 3.10. What we do here is "compiled class that inherits from interpreted one". `D` is created by simply calling `type("D", ...)` while `E` is created using a static type that has a member descriptor `__dict__` pointing right after `E` objects struct end.

Note that assigning attributes on `e` still works, so it does have a dict somewhere. Maybe `D` gets this managed dict flag, and therefore the negative dict offset is somehow used when storing attributes on `e` (instead of the one right after the object)? Also it may be a bug in `CPyType_FromTemplate()`.

@msullivan Maybe you will have time to look at this to figure out what is going on here?

**Comment by ilevkivskyi** [comment]
OK, so my guess was right, since `E` subclasses an interpreted class, it gets the managed dict. So the test is fixed by simply setting `t->ht_type.tp_flags &= ~Py_TPFLAGS_MANAGED_DICT` after `E` is created. I am not sure how safe it is, it seems like at least some code assumes that heap type implies managed dict.

If this hack gets us through 3.11 this is fine probably, since 3.12 already includes goop public APIs to work with managed dicts.
