### ISSUE TITLE
INTERNAL_ERROR # ShopifyShopManager: Type[ShopifyShopManagerBase] = Manager.from_queryset

### ISSUE THREAD

**Issue by cschubiner** [python/mypy#16008]
**Crash Report**

this is the broken line:
ShopifyShopManager: Type[ShopifyShopManagerBase] = Manager.from_queryset(ShopifyShopQuerySet)

**Traceback**

```
/Users/canal/canal/apps/web/models.py:1115: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.5.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6475, in accept
  File "mypy/nodes.py", line 1309, in accept
  File "mypy/semanal.py", line 2863, in visit_assignment_stmt
  File "mypy/semanal.py", line 3208, in apply_dynamic_class_hook
  File "/Users/canal/canal/canal-venv/lib/python3.10/site-packages/mypy_django_plugin/transformers/managers.py", line 39, in create_new_manager_class_from_from_queryset_method
    sym = semanal_api.lookup_fully_qualified_or_none(derived_queryset_fullname)
  File "mypy/semanal.py", line 5803, in lookup_fully_qualified_or_none
AssertionError: 
/Users/canal/canal/apps/web/models.py:1115: : n```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

<!-- Include as many relevant details about the environment you experienced the bug in -->

- Mypy version used: tried 1.2, 1.3, 1.4, 1.5 -- always fails! it previously worked on like version 0.888
- Mypy command-line flags: mypy -p apps -p canal --show-traceback    
- Mypy configuration options from `mypy.ini` (and other config files):
- ```
- [mypy]
python_version = 3.10
ignore_errors = False
ignore_missing_imports = True
implicit_reexport = True
strict_equality = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = True
check_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
exclude = .*(migrations|management|tests)/$
cache_dir = /dev/null

plugins =
    mypy_drf_plugin.main,
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "canal.settings"

[mypy-drfdapc.test_permissions]
ignore_errors = True

[mypy-pegasus.*]
ignore_errors = True

```
- Python version used: 3.10
- Operating system and version: mac ventura

**Comment by hauntsaninja** [comment]
This looks like an issue with mypy_django_plugin, so should be reported over there
