### ISSUE TITLE
1.19 Release Planning

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#19964]
We always wanted to release more often. I would propose to already aim at 1.19 release mid or late October.

cc @JukkaL

**Comment by ilevkivskyi** [comment]
From my side I would propose to:
* Stop calling `--fixed-format-cache` experimental
* Expose it in `argparse` on interpreted mypy (since we can now)
* Announce that `--fixed-format-cache` will be default in 1.20

**Comment by wyattscarpenter** [comment]
If https://github.com/python/mypy/issues/19922 (keep more readthedocs versions around) has to be done prospectively, it would be nice to enable that setting(?) on readthedocs before the next release. If old versions can easily be made retroactivity, however, this doesn't matter.

**Comment by ilevkivskyi** [comment]
Btw it may be worth highlighting https://github.com/python/mypy/pull/19719 in the release blog post, it is a surprisingly popular request.

**Comment by sterliakov** [comment]
[x] (resolved) Upgrading 1.18.2 to 1.19.0 cannot be performed with `pip install -U`. Am I missing any workarounds? If not, #20006 should probably be ALL CAPS and **bold** in the release notes.

**Comment by JukkaL** [comment]
Mid to late October release sounds good. @p-sawicki is expected to be the release manager.

This release will also have `librt` as a new dependency. It would be good to test installation in different contexts before the release goes out.

This is a release blocker (I'm working on it but have been busy recently, so not much progress):
* mypyc/mypyc#1141

It would be nice to have free-threaded binary wheels for 3.14 (3.14t). Currently free-threaded builds use the interpreted version of mypy.

> Upgrading 1.18.2 to 1.19.0 cannot be performed with pip install -U. Am I missing any workarounds? 

We haven't released 1.19.0 yet. Not being able to install a release using `pip install -U` is a release blocker.

**Comment by sterliakov** [comment]
> We haven't released 1.19.0 yet

Yep, sorry, I was trying to say that if 1.19.0 were released from current master branch, `pip install -U` would silently produce a broken installation.

**Comment by BobTheBuidler** [comment]
I'm hoping to get some of these mypyc optimizations merged in. I know I've made quite a few PRs lately so this little blurb should help separate signal from noise and make the review process easier from your end.

I'd like to get #19982 merged in so I can rebase and get the tests working for #19984 . They're both pretty straightforward.

I'm hoping to get some or all of these length helpers merged in so I can rebase the others and put them all to bed, they're all related but I kept them separate to avoid cluttering up the diff. I know there will be minor conflicts for me to deal with:
- #19930 
- #19929 
- #19927

And these 4 standalone ones are all ready and should all be relatively straightforward to review
- #19883
- #19972 - 6 LOC
- #19673 - you looked at this one already and just wanted some benchmark data
- #19643 - you looked at this one before releasing 1.18, there's just one open question left to close it out

Mypyc is evolving at a nice pace, love to see it. It's pretty exciting to watch you guys cook on the librt stuff. I can't say I understand how it all fits together but I'm excited to see some live examples and start hacking!

**Comment by randolf-scholz** [comment]
Hey, I have a bunch of open pull requests, hope that maybe some of them can make it into the next release.

- #19449
- #19466
- #19471
- #19517
- #19897 

and there's also #19046, but I think @sterliakov wanted to see a few more tests in this one.

**Comment by Chainfire** [comment]
I am excited about a new update, it would be great to have an official release that actually builds and runs our code (as there has never been one). However, running our test suite against the latest commit in master, I'm seeing segmentation faults and type errors all over the place. I'll see if I can hunt them down (may well be user error, badly typed mocks, etc) I guess...

EDIT (3):
- Some segfaults have been cleared by consistently force removing the build directory and all .so files generated before rebuilding. While fair, this was not necessary on 1.17.0 for the same patterns. But have more segfaults not solved by this.
- TypeErrors now seem limited to traits with async methods.

The mentions listed below are what I have thus far against `mypy 1.19.0+dev.2c6c3959356674262d9b2c2dc43a33486e807a9`. I'm a little on the fence about thinking something is wrong with my installation, but I wouldn't know what. I've reset and resynced the entire repo, force reinstalled librt, installed locally, and `./runtests.py` to completion without any other errors.

**Comment by BobTheBuidler** [comment]
I have 2 more bug fixes ready for 1.19
- #20085
- #19957 - This one was working, I broke it, and now there's just one open question about how allow_interpreted_subclasses interacts with native_class and @final
I can finish it up for 1.19 with some small feedback

**Comment by ilevkivskyi** [comment]
I tried `MYPY_USE_MYPYC=1 pip install -U .` locally on current master, and after install I am getting:
```
Traceback (most recent call last):
  File "/home/ivan/venvs/mypy_dev_3_12/bin/mypy", line 5, in <module>
    from mypy.__main__ import console_entry
ImportError: /home/ivan/venvs/mypy_dev_3_12/lib/python3.12/site-packages/7ae574991b77ef47acad__mypyc.cpython-312-x86_64-linux-gnu.so: undefined symbol: CPyTagged_BitLength
```
cc @BobTheBuidler it looks like this may be caused by your recent PR. Are you able to build/install mypy locally? Fixing this is a release blocker.

**Comment by ilevkivskyi** [comment]
Hm, actually reverting that commit doesn't fix the problem for me, I get a different error
```
Traceback (most recent call last):
  File "/home/ivan/venvs/mypy_dev_3_12/bin/mypy", line 5, in <module>
    from mypy.__main__ import console_entry
ImportError: /home/ivan/venvs/mypy_dev_3_12/lib/python3.12/site-packages/7ae574991b77ef47acad__mypyc.cpython-312-x86_64-linux-gnu.so: undefined symbol: CPyStr_EqualLiteral
```
probably something else is broken.

**Comment by ilevkivskyi** [comment]
Actually nvm, `rm -rf build dist` fixed the problem. That said it looks like there is some kind of caching bug in `pip install`, bit probably not a big deal.

**Comment by BobTheBuidler** [comment]
<img width="221" height="219" alt="Image" src="https://github.com/user-attachments/assets/9c543b8c-d801-46a1-be7c-11798c2400dc" />

I hate to throw a bunch of stuff at you at once (hehehe just kidding...) but here's one more fix, this time for a condition that causes mypyc to crash
- #20098

#20098 is part of a larger #20100 , so I separated them out to give you the option of merging the fix before spending any time revieing the feature

**Comment by Chainfire** [comment]
Another (for us, showstopper) issue above. I have uncovered another serious leak that I so far haven't been able to isolate further than task.cancel() on a task that has an add_done_callback() registered, but these may be the same issue as the one above, ultimately.

**Comment by hauntsaninja** [comment]
https://github.com/mypyc/mypyc/issues/1154 could be good to fix

**Comment by emmatyping** [comment]
I would recommend we make this version the last to support 3.9 see https://github.com/python/mypy/issues/20154

**Comment by JukkaL** [comment]
Found a release-blocker when testing in an internal repository:
* #20174

**Comment by ilevkivskyi** [comment]
@JukkaL are there any other blockers for the release? I think we should try getting it out, as it is already late.

**Comment by JukkaL** [comment]
I think all the blockers have been resolved, now that `librt.internal` versioning works better (#20221 and #20225).

**Comment by mr-c** [comment]
> https://github.com/mypyc/mypyc/issues/1154 could be good to fix

I think this regression which makes `black` segfault is still very important

**Comment by JukkaL** [comment]
Ok, I'll look at https://github.com/mypyc/mypyc/issues/1154 soon.

**Comment by BobTheBuidler** [comment]
I can forget about some of the features for now if that's best for the maintainers but I'd definitely like to get both of these bug fixes into the 1.19 release. The first is already ready to roll, the 2nd has just one pending concern to resolve before its also merge-ready.

> I have 2 more bug fixes ready for 1.19
> 
> * [[mypyc] fix: UnboundLocalError incorrectly raised as AttributeError #20085](https://github.com/python/mypy/pull/20085)
> * [[mypyc] fix: isinstance_native fast path conflict w/ interp. subclasses [1/1] #19957](https://github.com/python/mypy/pull/19957) - This one was working, I broke it, and now there's just one open question about how allow_interpreted_subclasses interacts with native_class and [@Final](https://github.com/Final)
>   I can finish it up for 1.19 with some small feedback

**Comment by ilevkivskyi** [comment]
@BobTheBuidler I would focus only on critical fixes as we already behind schedule.

**Comment by JukkaL** [comment]
Yeah, we will likely have another release in December or January.

**Comment by BobTheBuidler** [comment]
to be clear, without #19957 merged mypyc currently produces incorrect results for isinstance in some cases which imo is a pretty significant bug. I have some libraries that support Python3.9 which are impacted by this bug, so if 1.19 is going to be the last version that supports 3.9 its really important for me.

#20085 is less critical but is still a fix for a current case where mypyc behavior violates python semantics. I was under the impression that we want to eliminate these cases ASAP but we can kick that can down the road if you prefer.

**Comment by JukkaL** [comment]
Since we are late in the release process, we generally focus on critical fixes related to new functionality, and fixes to regressions. Other fixes can be merged as well, but they are lower priority. Otherwise releases tend to drag on for too long. #19957 seems pretty important and relatively small so we can try to get it in if the PR will be in a mergeable state in the next several days.

**Comment by BobTheBuidler** [comment]
Sounds good, I just have one quick open question for a maintainer on #19957 and I can get it fixed up straight away

**Comment by Chainfire** [comment]
I understand the need to focus on regressions, but does https://github.com/mypyc/mypyc/issues/1141 not count for that? It still breaks and used to work.

**Comment by JukkaL** [comment]
@Chainfire Yeah, https://github.com/mypyc/mypyc/issues/1141 seems important to fix -- I lost track that some cases are still broken. Thanks for the reminder!

**Comment by ilevkivskyi** [comment]
@JukkaL @p-sawicki please let me know if I can help to speed-up the process.

**Comment by BobTheBuidler** [comment]
Tests are green again on #19957, it's now ready for review

**Comment by JukkaL** [comment]
@ilevkivskyi This is a new feature that would be nice to include (though not strictly a release blocker):
* #20245

Can you help with this (should be simple)?

**Comment by ilevkivskyi** [comment]
> Can you help with this (should be simple)?

I opened https://github.com/mypyc/librt/pull/14 for this.

**Comment by JukkaL** [comment]
The mypyc regressions https://github.com/mypyc/mypyc/issues/1141 and https://github.com/mypyc/mypyc/issues/1154 are now fixed on master.

**Comment by ilevkivskyi** [comment]
@JukkaL @p-sawicki https://github.com/mypyc/mypyc/issues/1165 may be a potential blocker.

**Comment by JukkaL** [comment]
This looks like a blocker -- some users appear to be encountering it at work:
* #20209

**Comment by BobTheBuidler** [comment]
I think I might be in over my head re: the requested modification of non-native class handling on #19957

What do you think about merging the valid bugfix for native classes (since it already worked and tests passed, and DOES still fix a valid bug) so I can continue to work on implementing the same for non-native classes without blocking the release? Alternatively, a second set of eyeballs might help to find whatever it is that I'm missing. I suspect its something relatively simple that I'm missing here, as it isn't a complex PR.

**Comment by p-sawicki** [comment]
I have created the release branch https://github.com/python/mypy/tree/release-1.19 that is cut off from master at https://github.com/python/mypy/commit/a087a5894935cfdbc2eba27a6d04ebca38fd6659.

I have cherry-picked https://github.com/python/mypy/commit/b05fd6314ee741dd906713550c722e61ac126fa6 as it fixes a regression introduced in 1.18.

Let me know if there are other commits to add.

**Comment by ilevkivskyi** [comment]
@p-sawicki One remaining blocker is `black` fails to compile with current master. After some investigation it looks like the real root cause is https://github.com/python/mypy/pull/19739 (cc @brianschubert @JukkaL). The simplest test case is:
```
[case testNewSubclass]
class Base:
    def __new__(cls):
        return object.__new__(cls)

    def method(self) -> int:
        raise NotImplementedError

class Sub(Base):
    def method(self) -> int:
        return 0

def test_sub_new() -> None:
    x: Base = Sub()
    assert x.method() == 0
```
This currently fails with `NotImplementedError`, but there are other similar scenarios that can lead to segfaults. I also confirmed that after commenting out `pytree.Base.__new__` (that does nothing but an assert), all black tests pass locally.

The issue with the PR is that it breaks the `setup` logic in presence of inheritance. For example in this case `Sub()` (i.e. `CPyDef_Sub()`) calls `Base.__new__()` (i.e. `CPyPy_Base_____new__`) which in turn calls `CPyDef___mypyc__Base_setup()`. This leads to `Sub` instance having a pointer to `Base` vtable. I can't find a simple fix for this, it looks like we will need to rethink the logic of where exactly setup methods should be called in presence of custom `__new__()`.

@brianschubert unless you have a clean simple fix, I would propose to revert this for now (as this is the last release blocker).

**Comment by mr-c** [comment]
Please consider https://github.com/python/mypy/pull/20253 which fixes a regression requiring SSE4.2 for X86-64 users. If not applied, then Debian will have to carry this patch

**Comment by p-sawicki** [comment]
@ilevkivskyi thanks for reproducing the issue. i have opened #20302 that should fix it. are there instructions anywhere on how to run the black tests locally with mypyc? i couldn't figure it out.

**Comment by ilevkivskyi** [comment]
@p-sawicki Oh it is tricky indeed. It would be easier if I simply try it myself now.

**Comment by ilevkivskyi** [comment]
@p-sawicki Nope, it still crashes. Btw I think you should be able to try it yourself with this (update the remote hash if you push more commits).
```diff
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -123,10 +123,10 @@ sources = ["src"]
 macos-max-compat = true
 
 [tool.hatch.build.targets.wheel.hooks.mypyc]
-enable-by-default = false
+enable-by-default = true
 dependencies = [
   "hatch-mypyc>=0.16.0",
-  "mypy==1.17.1",
+  "mypy @ git+https://github.com/p-sawicki/mypy@a0ae3328e28ac134a0d02f34c72b2980eeaded61",
   "click>=8.1.7",
 ]
 require-runtime-dependencies = true
```
And optionally
```diff
@@ -146,7 +146,7 @@ exclude = [
   "/src/black/__main__.py",
 ]
 mypy-args = ["--ignore-missing-imports"]
-options = { debug_level = "0" }
+options = { debug_level = "2", opt_level = "0" }
```
to simplify debugging. To preserve the C files during the hatch build, you can use
```
HATCH_MYPYC_BUILD_DIR=/home/some/existing/dir pip install -U .
```

**Comment by ilevkivskyi** [comment]
(and to test simply run `pytest -k "not incompatible_with_mypyc"`)

**Comment by ilevkivskyi** [comment]
Hm, this time it is quite different, crashes are much more "predictable", essentially they all boil down to
```
AttributeError: attribute '_prefix' of 'Leaf' undefined
```
Btw another (potentially unrelated) problem, is that sometimes our tracebacks have `lineno` set to `None`, which makes debugging trickier.

**Comment by p-sawicki** [comment]
yeah i've managed to run the tests as well. looks like the only problem left with my changes is that the attribute is not initialized correctly when it's initialized outside of `__init__`. if i add `self._prefix = ""` to `__init__` of `Leaf` then all tests pass. i'll try to fix this.

**Comment by ilevkivskyi** [comment]
@p-sawicki Oh, right, now your `allocate` functions suffer from the same issue: `Base_allocate` is called inside `Base.__new__()` for a `Leaf` instance.

**Comment by ilevkivskyi** [comment]
@p-sawicki Another test case for you, this should _not_ print `0`:
```
[case testNewSubclass2]
class Base:
    def __new__(cls, *args):
        return object.__new__(cls)

class Sub(Base):
    x: int

def test_sub_new() -> None:
    x = Sub()
    print(x.x)
```
Instead `x` should be set to `CPY_INT_TAG`, and result in an `AttributeError` (as it does if I comment out `__new__`)

**Comment by ilevkivskyi** [comment]
(to be clear the above test case should pass in addition to fixing the problem you found, when the class body has `_prefix = ""`, although root cause is the same, it means you can't move _only_ the defaults setup part)

**Comment by ilevkivskyi** [comment]
Yeah, this is really chicken and egg problem: potentially you will need to do some kind of a trick, like setting up a pointer to vtable on the _class object_ in module init, then do something like `obj->vtable = obj->type->vtable`. And when you have the vtable you can call the correct allocate function. Anyway, sorry for spamming here.

**Comment by p-sawicki** [comment]
yeah i think there's no way to avoid dynamic lookup of the setup function. i've changed the implementation to instead store the pointer to the setup function in each type object and with that black seems to work correctly. thanks for the suggestion.

**Comment by mr-c** [comment]
> Please consider [#20253](https://github.com/python/mypy/pull/20253) which fixes a regression requiring SSE4.2 for X86-64 users. If not applied, then Debian will have to carry this patch

This is ready for review, merging, and cherry-picking into the 1.19 release branch.

**Comment by JukkaL** [comment]
I just merged #20253. I believe all regressions have been fixed on master.

**Comment by p-sawicki** [comment]
ok nice. i have cherry-picked #20302 and #20253 onto the release branch.

**Comment by ilevkivskyi** [comment]
Two more crash fixes I think may be worth cherry-picking (optionally):
* https://github.com/python/mypy/pull/20139
* https://github.com/python/mypy/pull/20289

**Comment by ilevkivskyi** [comment]
@p-sawicki @JukkaL One more important thing: please don't forget to announce that 1.19 will be the last version to support Python 3.9

**Comment by p-sawicki** [comment]
wheels for 1.19.0 are now available: https://pypi.org/project/mypy/1.19.0/
and there's a blog post: https://mypy-lang.blogspot.com/2025/11/mypy-119-released.html

**Comment by link2xt** [comment]
Because of dependency on librt it now fails to build with PyPy 3.10:
<details>

```
      gcc -pthread -DNDEBUG -O2 -fPIC -I. -I/home/runner/work/core/core/python/.tox/mypy/include -I/opt/hostedtoolcache/PyPy/3.10.16/x64/include/pypy3.10 -c exc_ops.c -o build/temp.linux-x86_64-pypy310/exc_ops.o -O3
      In file included from CPy.h:12,
                       from exc_ops.c:8:
      pythonsupport.h:38:1: warning: data definition has no type or storage class
         38 | _Py_IDENTIFIER(__mro_entries__);
            | ^~~~~~~~~~~~~~
      pythonsupport.h:38:1: warning: type defaults to ‘int’ in declaration of ‘_Py_IDENTIFIER’ [-Wimplicit-int]
      pythonsupport.h:38:1: warning: parameter names (without types) in function declaration
      pythonsupport.h: In function ‘update_bases’:
      pythonsupport.h:60:50: error: ‘PyId___mro_entries__’ undeclared (first use in this function)
         60 |         if (PyObject_GetOptionalAttrString(base, PyId___mro_entries__.string, &meth) < 0) {
            |                                                  ^~~~~~~~~~~~~~~~~~~~
      pythonsupport.h:60:50: note: each undeclared identifier is reported only once for each function it appears in
      pythonsupport.h: At top level:
      pythonsupport.h:113:1: warning: data definition has no type or storage class
        113 | _Py_IDENTIFIER(__init_subclass__);
            | ^~~~~~~~~~~~~~
      pythonsupport.h:113:1: warning: type defaults to ‘int’ in declaration of ‘_Py_IDENTIFIER’ [-Wimplicit-int]
      pythonsupport.h:113:1: warning: parameter names (without types) in function declaration
      pythonsupport.h: In function ‘init_subclass’:
      pythonsupport.h:125:12: warning: implicit declaration of function ‘_PyObject_GetAttrId’; did you mean ‘PyObject_GetAttr’? [-Wimplicit-function-declaration]
        125 |     func = _PyObject_GetAttrId(super, &PyId___init_subclass__);
            |            ^~~~~~~~~~~~~~~~~~~
            |            PyObject_GetAttr
      pythonsupport.h:125:40: error: ‘PyId___init_subclass__’ undeclared (first use in this function)
        125 |     func = _PyObject_GetAttrId(super, &PyId___init_subclass__);
            |                                        ^~~~~~~~~~~~~~~~~~~~~~
      In file included from pythonsupport.h:14:
      pythonsupport.h: In function ‘CPyLong_AsSsize_tAndOverflow’:
      mypyc_util.h:169:34: error: ‘PyLongObject’ has no member named ‘ob_digit’
        169 | #define CPY_LONG_DIGIT(o, n) ((o)->ob_digit[n])
            |                                  ^~
      pythonsupport.h:203:15: note: in expansion of macro ‘CPY_LONG_DIGIT’
        203 |         res = CPY_LONG_DIGIT(v, 0);
            |               ^~~~~~~~~~~~~~
      pythonsupport.h:207:17: error: ‘sdigit’ undeclared (first use in this function); did you mean ‘isdigit’?
        207 |         res = -(sdigit)CPY_LONG_DIGIT(v, 0);
            |                 ^~~~~~
            |                 isdigit
      mypyc_util.h:169:34: error: ‘PyLongObject’ has no member named ‘ob_digit’
        169 | #define CPY_LONG_DIGIT(o, n) ((o)->ob_digit[n])
            |                                  ^~
      pythonsupport.h:207:24: note: in expansion of macro ‘CPY_LONG_DIGIT’
        207 |         res = -(sdigit)CPY_LONG_DIGIT(v, 0);
            |                        ^~~~~~~~~~~~~~
      pythonsupport.h: In function ‘list_resize’:
      pythonsupport.h:226:32: error: ‘PyListObject’ has no member named ‘allocated’
        226 |     Py_ssize_t allocated = self->allocated;
            |                                ^~
      pythonsupport.h:256:44: error: ‘PyListObject’ has no member named ‘ob_item’
        256 |     items = (PyObject **)PyMem_Realloc(self->ob_item, num_allocated_bytes);
            |                                            ^~
      pythonsupport.h:261:9: error: ‘PyListObject’ has no member named ‘ob_item’
        261 |     self->ob_item = items;
            |         ^~
      pythonsupport.h:263:9: error: ‘PyListObject’ has no member named ‘allocated’
        263 |     self->allocated = new_allocated;
            |         ^~
      pythonsupport.h: In function ‘list_pop_impl’:
      pythonsupport.h:285:13: error: ‘PyListObject’ has no member named ‘ob_item’
        285 |     v = self->ob_item[index];
            |             ^~
      pythonsupport.h: In function ‘list_count’:
      pythonsupport.h:310:48: error: ‘PyListObject’ has no member named ‘ob_item’
        310 |         int cmp = PyObject_RichCompareBool(self->ob_item[i], value, Py_EQ);
            |                                                ^~
      pythonsupport.h: At top level:
      pythonsupport.h:382:35: error: unknown type name ‘_Py_Identifier’
        382 | _CPyObject_HasAttrId(PyObject *v, _Py_Identifier *name) {
            |                                   ^~~~~~~~~~~~~~
      CPy.h: In function ‘CPyLong_AsInt64’:
      mypyc_util.h:169:34: error: ‘PyLongObject’ has no member named ‘ob_digit’
        169 | #define CPY_LONG_DIGIT(o, n) ((o)->ob_digit[n])
            |                                  ^~
      CPy.h:337:20: note: in expansion of macro ‘CPY_LONG_DIGIT’
        337 |             return CPY_LONG_DIGIT(lobj, 0);
            |                    ^~~~~~~~~~~~~~
      CPy.h: In function ‘CPyLong_AsInt32’:
      CPy.h:359:40: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
        359 |         Py_ssize_t size = lobj->ob_base.ob_size;
            |                                        ^
      mypyc_util.h:169:34: error: ‘PyLongObject’ has no member named ‘ob_digit’
        169 | #define CPY_LONG_DIGIT(o, n) ((o)->ob_digit[n])
            |                                  ^~
      CPy.h:362:20: note: in expansion of macro ‘CPY_LONG_DIGIT’
        362 |             return CPY_LONG_DIGIT(lobj, 0);
            |                    ^~~~~~~~~~~~~~
      CPy.h: In function ‘CPyLong_AsInt16’:
      CPy.h:387:40: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
        387 |         Py_ssize_t size = lobj->ob_base.ob_size;
            |                                        ^
      CPy.h:390:13: error: unknown type name ‘digit’
        390 |             digit x = lobj->ob_digit[0];
            |             ^~~~~
      CPy.h:390:27: error: ‘PyLongObject’ has no member named ‘ob_digit’
        390 |             digit x = lobj->ob_digit[0];
            |                           ^~
      CPy.h: In function ‘CPyLong_AsUInt8’:
      CPy.h:417:40: error: ‘PyObject’ {aka ‘struct _object’} has no member named ‘ob_size’
        417 |         Py_ssize_t size = lobj->ob_base.ob_size;
            |                                        ^
      CPy.h:420:13: error: unknown type name ‘digit’
        420 |             digit x = lobj->ob_digit[0];
            |             ^~~~~
      CPy.h:420:27: error: ‘PyLongObject’ has no member named ‘ob_digit’
        420 |             digit x = lobj->ob_digit[0];
            |                           ^~
      CPy.h: At top level:
      CPy.h:939:35: error: unknown type name ‘_Py_Identifier’
        939 |                                   _Py_Identifier *method);
            |                                   ^~~~~~~~~~~~~~
      CPy.h: In function ‘CPyObject_GenericGetAttr’:
      CPy.h:955:12: warning: implicit declaration of function ‘_PyObject_GenericGetAttrWithDict’; did you mean ‘CPyObject_GenericGetAttr’? [-Wimplicit-function-declaration]
        955 |     return _PyObject_GenericGetAttrWithDict(self, name, NULL, 1);
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |            CPyObject_GenericGetAttr
      CPy.h:955:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
        955 |     return _PyObject_GenericGetAttrWithDict(self, name, NULL, 1);
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CPy.h: In function ‘CPyObject_GenericSetAttr’:
      CPy.h:958:12: warning: implicit declaration of function ‘_PyObject_GenericSetAttrWithDict’; did you mean ‘CPyObject_GenericSetAttr’? [-Wimplicit-function-declaration]
        958 |     return _PyObject_GenericSetAttrWithDict(self, name, value, NULL);
            |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |            CPyObject_GenericSetAttr
      In file included from /opt/hostedtoolcache/PyPy/3.10.16/x64/include/pypy3.10/Python.h:47,
                       from pythoncapi_compat.h:21,
                       from exc_ops.c:1:
      exc_ops.c: In function ‘CPy_ExceptionMatches’:
      CPy.h:838:43: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_info’
        838 | #define CPy_ExcState() PyThreadState_GET()->exc_info
            |                                           ^~
      /opt/hostedtoolcache/PyPy/3.10.16/x64/include/pypy3.10/object.h:115:41: note: in definition of macro ‘_PyObject_CAST’
        115 | #define _PyObject_CAST(op) ((PyObject*)(op))
            |                                         ^~
      exc_ops.c:86:52: note: in expansion of macro ‘Py_TYPE’
         86 |     return PyErr_GivenExceptionMatches((PyObject *)Py_TYPE(CPy_ExcState()->exc_value), type);
            |                                                    ^~~~~~~
      exc_ops.c:86:60: note: in expansion of macro ‘CPy_ExcState’
         86 |     return PyErr_GivenExceptionMatches((PyObject *)Py_TYPE(CPy_ExcState()->exc_value), type);
            |                                                            ^~~~~~~~~~~~
      exc_ops.c: In function ‘CPy_GetExcValue’:
      CPy.h:838:43: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_info’
        838 | #define CPy_ExcState() PyThreadState_GET()->exc_info
            |                                           ^~
      exc_ops.c:90:21: note: in expansion of macro ‘CPy_ExcState’
         90 |     PyObject *exc = CPy_ExcState()->exc_value;
            |                     ^~~~~~~~~~~~
      exc_ops.c: In function ‘CPy_AddTraceback’:
      exc_ops.c:244:5: warning: implicit declaration of function ‘_PyErr_ChainExceptions’; did you mean ‘PyErr_NewException’? [-Wimplicit-function-declaration]
        244 |     _PyErr_ChainExceptions(exc, val, tb);
            |     ^~~~~~~~~~~~~~~~~~~~~~
            |     PyErr_NewException
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for librt
```
</details>

**Comment by ilevkivskyi** [comment]
It means you wouldn't be able to build mypy on PyPy either, but mypy is written in Python, so you can just use the interpreted version. _Potentially_ we can provide some slow pure-Python equivalent of `librt.internal`, but TBH that would be quite significant amount of work. Also we use a lot of CPython internals, so there is no way PyPy people will want to support those internals. Not sure what to do about this, maybe others have some ideas.

**Comment by link2xt** [comment]
We should probably fix this by running mypy using only the latest CPython and run only actual tests with old CPython and PyPy. For now fixed this by pinning mypy, but can also change it. (did it at https://github.com/chatmail/core/pull/7539)

**Comment by ilevkivskyi** [comment]
@link2xt This is actually a good point, mypy is not a runtime dependency, but a dev/test dependency. So people who are developing a library that supports both CPython and PyPy simply don't need to run type check twice (and this is redundant anyway, since results will be identical say for CPython 3.10 and PyPy 3.10).

We already got couple reports about this problem. @JukkaL maybe it makes sense to update the blog post, and/or otherwise advertise this recommendation?

**Comment by ilevkivskyi** [comment]
In any case, let's continue discussion of PyPy specific problems in https://github.com/python/mypy/issues/20329

**Comment by ilevkivskyi** [comment]
So far there has been two crash regressions (one fixed, one pending fix):
* https://github.com/python/mypy/issues/20327
* https://github.com/python/mypy/issues/20341

cc @p-sawicki @JukkaL re deciding on whether we need a point release for these.

**Comment by hauntsaninja** [comment]
Post for potential cherry picks (feel free to edit):
- https://github.com/python/mypy/pull/20334 (fixes https://github.com/python/mypy/issues/20326)
- https://github.com/python/mypy/pull/20333 (fixes https://github.com/python/mypy/issues/20327)
- https://github.com/python/mypy/pull/20323 (fixes https://github.com/python/mypy/issues/20093)
- https://github.com/python/mypy/pull/20345 (not a regression, but fixes determinism issue https://github.com/python/mypy/issues/20344)
- https://github.com/python/mypy/pull/20371 (fixes https://github.com/python/mypy/issues/20341)
- https://github.com/python/mypy/pull/20383 (fixes https://github.com/python/mypy/issues/20367)
- https://github.com/python/mypy/pull/20372 (fixes https://github.com/python/mypy/issues/20353)

**Comment by mr-c** [comment]
Can we get a version 1.19.1 mypy release with https://github.com/python/mypy/pull/20371 included?

**Comment by BobTheBuidler** [comment]
If we're going to do a point release, which I agree seems warranted, what are the chances we can push #19957 to the finish line and include that fix in 1.19.1 as well? 

The reason this is important for me is because 1.20 will not support Python3.9 but the bug is impacting one of my forks of a community project which must still support 3.9 for the time being

Or alternatively, if that seems rushed, can we still do a 1.19.2 later which just cherry-picks this change for 3.9?

**Comment by ilevkivskyi** [comment]
https://github.com/python/mypy/pull/20372 is also worth including in 1.19.1

**Comment by ilevkivskyi** [comment]
Also probably https://github.com/python/mypy/pull/20384 and https://github.com/python/mypy/pull/20389 (in some sense it was a regression).

**Comment by hauntsaninja** [comment]
Cherry picked the PRs in my comment + the PyPy error ones to the 1.19 release branch. I'll probably cut the release tomorrow.

**Comment by hauntsaninja** [comment]
1.19.1 is now out. It's been two weeks since 1.19.0, so going to optimistically close this issue
