### ISSUE TITLE
`from ... import ...` fails the checks with "Name 'modl.Klass' is not defined".

### ISSUE THREAD

**Issue by nolar** [python/mypy#10063]
**Bug Report**

Indirect imports and re-imports fail with "Name 'modl.Klass' is not defined".

**To Reproduce**

Create 2 source files:

```python
# thirdparty.py
from json import JSONEncoder

class X:
    pass
```

```python
# test1.py
import thirdparty
a: thirdparty.X
b: thirdparty.JSONEncoder
```

Test with:

```
$ mypy --strict --ignore-missing-imports test1.py
test1.py:3: error: Name 'thirdparty.JSONEncoder' is not defined
Found 1 error in 1 file (checked 1 source file)
```

_A side-note: Originally, I used conditional imports from 3rd-party libraries — hence the `from ... import ... as ...` syntax. But then, simplified to a StdLib library — it fails exactly the same way, even when not conditional._

**Expected Behavior**

The check should pass in v0.800, as it does in v0.790.

**Actual Behavior**

The check fails in v0.800.
The same happens both for built-in libraries and for 3rd-party libraries install via pip.

**Your Environment**

- Mypy version used: v0.800
- Mypy command-line flags: `--strict --ignore-missing-imports`
- Mypy configuration options from `mypy.ini` (and other config files): none.
- Python version used: 3.9.1
- Operating system and version: MacOS

It was all good in v0.790.

The master branch is also broken (as of 2021-02-10, 6bfc2dbc0e877408f5b70b86818683cd211c0031).

The error appears after the commit 45d3655c38a7260bd91a0324b4048a585f152016 as identified by git bisection:

```
$ cat ./test1.sh
#!/bin/bash
set -x
git submodule update mypy/typeshed
pip install -e .
mypy --strict --ignore-missing-imports test1.py || exit 1
```

```
$ chmod a+x test1.sh
$ git bisect start v0.800 v0.790 --
$ git bisect run ./test1.sh
………
45d3655c38a7260bd91a0324b4048a585f152016 is the first bad commit
```

**Comment by hauntsaninja** [comment]
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport

**Comment by nolar** [comment]
@hauntsaninja Thanks for clarifying. Looks counter-intuitive (not like Python does things), but perhaps you had reasons for that change.

I tried to play with this, and it still does not work as expected even with `from ... import ... as ...` syntax:

```python
from json import JSONEncoder as JSONEncoder
from json import JSONEncoder as Y

class X:
    pass
```

```python
import thirdparty
a: thirdparty.X
b: thirdparty.JSONEncoder
c: thirdparty.Y
```

```
$ mypy --strict test1.py 
test1.py:4: error: Name 'thirdparty.Y' is not defined
Found 1 error in 1 file (checked 1 source file)
```

It looks like the re-exporting works only when the `as` part uses the same name as it is originally called. Change of the name does not work — this is what it does in pure Python.

It works fine with `__all__ = ['Y']`, but I prefer not to have `__all__` at all in internal modules (I do not use `from ... import *` syntax anywhere). It is still unclear why only renamed re-exports should be listed, while internal classes and same-named re-exports shouldn't.

Can you please hint, do I still misunderstand something? Or is it a bug? If so, is this the same bug or should be reported separately?

**Comment by hauntsaninja** [comment]
Note that `--no-implicit-reexport` is an old option and has been included in `--strict` for a long time. The commit you bisected to merely fixed a bug in this flag (detailed in https://github.com/python/mypy/issues/9517).

The semantics here are specified in https://www.python.org/dev/peps/pep-0484 (grep for "X as X", note that the expected behaviour here was recently clarified in the PEP).

To export in this case, you can use `__all__` or alias with `Y = JSONEncoder`.

If you hate this part of `--strict`, I believe passing `--implicit-reexport` should work

**Comment by nolar** [comment]
@hauntsaninja Thanks. I've currently made a workaround in a slightly different waY (importing `X as X`, and then re-assigning). 

But doesn't this PEP-0484 comment and update apply only to stubs files?

**Comment by nolar** [comment]
PS: I do not hate it. I was just confused by this behaviour. Please do not take my notes as any kind of aggressiveness. All is fine — and thanks for your work on this project ;-)

**Comment by hauntsaninja** [comment]
Yes, PEP 484 only mentions this in regards to stub files.
But the problem it's solving is the same — giving modules the ability to specify what their public API is — so it makes sense for the syntax by which we do that to be the same in both cases. It's also nice that mypy gets to use the same code in both cases (https://github.com/python/mypy/blob/6bfc2dbc0e877408f5b70b86818683cd211c0031/mypy/semanal.py#L1732)

**Comment by nolar** [comment]
@hackaugusto I got it. Thanks for clarifying!
