### PR TITLE
Various improvements to fine-grained incremental mode

### PR DESCRIPTION
**Pull request by JukkaL**
Summary of changes:

* Fixes to `NamedTuple`
* Fixes to overloads
* Fixes to generic classes
* Fixes to decorators
* Fixes to processing statements in class bodies and module top levels
* Detect endless fine-grained dependency loops
* Add support for testing which triggers get triggered

### CODE REVIEW

File: test-data/unit/deps-statements.test [hunk 1]
```diff
@@ -549,3 +549,101 @@ def f() -> int:
...
+
+def f(x: A) -> A:
+    g()
+    return x
+
+def g() -> None: pass
+[builtins fixtures/isinstancelist.pyi]
+[out]
+<m.A.__init__> -> <m.B.__init__>
+<m.A> -> <m.f>, m, m.A, m.B, m.f
```
Comment (gvanrossum) [inline test-data/unit/deps-statements.test]: Remind me, why does A trigger m (the whole module?) but not B?

File: test-data/unit/fine-grained.test [hunk 2]
```diff
@@ -996,3 +996,232 @@ class B:
...
+[triggered]
+2: <b>
+3: <b>
+[out]
+main:2: error: Revealed type is 'contextlib.GeneratorContextManager[builtins.None]'
+==
+a.py:1: error: Cannot find module named 'b'
+a.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
+main:2: error: Revealed type is 'contextlib.GeneratorContextManager[builtins.None]'
+a.py:3: error: Cannot find module named 'b'
```
Comment (gvanrossum) [inline test-data/unit/fine-grained.test]: There's only one "import b" in a.py (on line 3) -- why does that error get reported both for line 1 and for line 3?

File: test-data/unit/fine-grained.test [hunk 3]
```diff
@@ -996,3 +996,232 @@ class B:
...
+
+@contextmanager
+def f(x: List[int]) -> Iterator[None]:
+    x.append(1)
+    yield
+[typing fixtures/typing-full.pyi]
+[builtins fixtures/list.pyi]
+[out]
+==
+a.py:1: error: Cannot find module named 'b'
```
Comment (gvanrossum) [inline test-data/unit/fine-grained.test]: Ditto.

File: test-data/unit/fine-grained.test [hunk 4]
```diff
@@ -996,3 +996,232 @@ class B:
...
+    from n import g
+[file m.py]
+class A: pass
+[file n.py]
+def g() -> None: pass
+[delete m.py.2]
+[delete n.py.2]
+[out]
+==
+main:1: error: Cannot find module named 'm'
```
Comment (gvanrossum) [inline test-data/unit/fine-grained.test]: And ditto?

File: test-data/unit/merge.test [hunk 5]
```diff
@@ -829,6 +829,110 @@ NameExpr:11: Overload(def (x: target.A<0>) -> target.A<0>, def (x: builtins.int<
...
+class B: pass
+
+@overload
+def f(x: A) -> B: pass
+@overload
+def f(x: str) -> str: pass
+
+def f(x): pass
+[out]
+MypyFile:1<0>(
```
Comment (gvanrossum) [inline test-data/unit/merge.test]: I hope you verified this file by hand -- I can't follow anything here in detail.

File: mypy/nodes.py [hunk 6]
```diff
@@ -2360,6 +2363,18 @@ def type(self) -> 'Optional[mypy.types.Type]':
         else:
             return None
 
+    def copy(self) -> 'SymbolTableNode':
```
[the remark this answers is not in the document]
Comment (ethanhs) [reply mypy/nodes.py]: The dataclasses backport only works on 3.6 since dataclasses' class based declaration syntax requires PEP 526. It will be a couple years before we can use it (3.5 goes out of support in late 2020).

File: test-data/unit/fine-grained.test (hunk 2 above)
Comment (JukkaL) [reply test-data/unit/fine-grained.test]: That's a bug with the current implementation. There's a TODO comment elsewhere but I haven't repeated it everywhere where this happens.

File: test-data/unit/merge.test (hunk 5 above)
Comment (JukkaL) [reply test-data/unit/merge.test]: Yeah I looked at it by hand. At some point I may update the output of these test cases, as currently it's super verbose.

File: mypy/semanal.py [hunk 7]
```diff
@@ -2880,7 +2877,7 @@ def fail_enum_call_arg(self, message: str,
         self.fail(message, context)
         return [], [], False
 
-    def visit_decorator(self, dec: Decorator) -> None:
+    def visit_decorator(self, dec: Decorator, func_body: bool = True) -> None:
```
[the remark this answers is not in the document]
Comment (JukkaL) [reply mypy/semanal.py]: Looks like it's left over from earlier revisions. I'll remove it.

File: test-data/unit/deps-statements.test (hunk 1 above)
Comment (JukkaL) [reply test-data/unit/deps-statements.test]: It looks like it's because `A` is used as a base class in `B`, whereas `B` is not used as a base class. Base classes are considered to be in the top-level module scope. (Effectively both will trigger the module top level since `m.A` and `m.B` also include `m`.)
