### ISSUE TITLE
Bytes formatting error gets produced during failed overload match

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#12665]
**Bug Report**

`On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"` gets produced during bidirectional inference in a failed overload match.

**To Reproduce**

```python
from typing import overload, Callable

@overload
def sub(pattern: str, repl: Callable[[str], str]) -> str: ...
@overload
def sub(pattern: bytes, repl: Callable[[bytes], bytes]) -> bytes: ...
def sub(pattern: object, repl: object) -> object:
    raise NotImplementedError

def better_snakecase(text: str) -> str:
    text = sub(r"([A-Z])([A-Z]+)([A-Z](?:[^A-Z]|$))", lambda match: f"{match}")
    return text
```

**Expected Behavior**

No errors

**Actual Behavior**

```
test_cases/stdlib/typing/pattern.py:11: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior
```

**Your Environment**

- Mypy version used: master, 0.942
- Mypy command-line flags: none

---

Found in python/typeshed#7679, the repro case minified from some code in homeassistant.

**Comment by AlexWaygood** [comment]
This appears to have been fixed by a3abd3644c5f2c84d2fa65fb621327a6c6a0e695 (#12631), unless I did the `git bisect` wrong. I can't reproduce the error on the original example with a3abd3644c5f2c84d2fa65fb621327a6c6a0e695 checked out, but I can with the commit before it.

**Comment by hauntsaninja** [comment]
Hmm, this happened to me too with that exact same PR: https://github.com/python/mypy/issues/8814#issuecomment-1222759856

Quite worrisome.

**Comment by AlexWaygood** [comment]
Oh, looks like it's actually not _entirely_ unexpected: Jelle mentioned in https://github.com/python/mypy/pull/12631#discussion_r857181069 that the PR was touching logic that impacted this bug. But we should definitely add a test, agreed.

**Comment by sebwills** [comment]
I'm getting the same error `mypy_test.py:6: error: On Python 3 formatting "b'abc'" with "{}" produces "b'abc'", not "abc"; use "{!r}" if this is desired behavior  [str-bytes-safe]` with the following repro

```
import pandas as pd

df = pd.DataFrame({'A': [1]})

x = f"Hello {df.loc[0, 'A']}"
```

mypy: 1.0.0 (strict=True)

**Comment by sebwills** [comment]
Sorry, ignore my previous comment, it went away when I upgraded `pandas-stubs`

**Comment by erictraut** [comment]
This appears to have been fixed in mypy 0.960.

**Comment by AlexWaygood** [comment]
We were keeping this open so that we didn't forget to add a regression test, since this was a strange bug that was fixed somewhat by accident: https://github.com/python/mypy/issues/12665#issuecomment-1324156230. But it looks like we forgot to anyway :)

I filed https://github.com/python/mypy/pull/15867 to add a regression test.
