### ISSUE TITLE
[1.16 regression] determining exhaustive match on an enum with type members

### ISSUE THREAD

**Issue by delfick** [python/mypy#19151]
Hi,

I continued looking at how the codebase I work on responds to the upcoming mypy 1.16 release and I believe I found another bug

```python
import datetime
import enum
from typing import assert_never


class ValueType(enum.Enum):
    BOOLEAN = bool
    DATE = datetime.date
    DATETIME = datetime.datetime


value_type: ValueType = ValueType.BOOLEAN

match value_type:
    case ValueType.BOOLEAN:
        pass
    case ValueType.DATE:
        pass
    case ValueType.DATETIME:
        pass
    case _:
        assert_never(value_type)
```

On mypy 1.16 I get this error

```
a.py:22: error: Argument 1 to "assert_never" has incompatible type "ValueType"; expected "Never"  [arg-type]
```

As far as I can tell this should be correct and I'm unsure why it doesn't think I have an exhaustive match.

**Your Environment**

- Mypy version used: release-1.16 (revision 96525a23f, built locally with mypy_mypyc-wheels for cp312-macosx_arm64)
- Mypy command-line flags: `mypy a.py`
- Mypy configuration options from `mypy.ini` (and other config files): no config
- Python version used: python3.12

**Comment by hauntsaninja** [comment]
Sure, please do. In general, don't need to ask, just put up PRs!

Obviously most principled thing to do is understand what `enum` actually does at runtime to differentiate the lambda case #18675 was thinking about. An ad hoc thing could be to special case type object function likes

**Comment by vidhyavijayan3** [comment]
Thank you very much for pointing that out. I understand the difference between enum and enum.Flag and the need to handle enum.Flag as a special case. I will review the relevant section of the typing specification to ensure I fully grasp the details before implementing the fix. I appreciate your helpful guidance!

**Comment by delfick** [comment]
I believe I found another example of this bug, and it seems to be more than just about enums specifically

So if we have two files

```python
# a.py
from typing import assert_never

import b


def switch[T_Choice: b.One | b.Two](choice: type[T_Choice]) -> None:
    match choice:
        case b.One:
            print(1)
        case b.Two:
            print(2)
        case _:
            assert_never(choice)


switch(b.One)

```

and

```python
# b.py
class One:
    pass


class Two:
    pass

```

Then I get no errors with mypy 1.15 and this error with 1.16

```
a.py:13: error: Argument 1 to "assert_never" has incompatible type "type[Two] | Never"; expected "Never"  [arg-type]
```

**Comment by hauntsaninja** [comment]
Hmm that one bisects to #18972 , let's open a new regression issue for that!
