### ISSUE TITLE
Cannot make mypy to work with dataclasses (Python 3.7)

### ISSUE THREAD

**Issue by pawelswiecki** [python/mypy#5341]
Installed **Python 3.7.0** and **mypy 0.610** (globally, to avoid https://github.com/python/mypy/issues/5092).

Now:

```
$ cat f.py 
from dataclasses import dataclass
$ mypy f.py
f.py:1: error: Cannot find module named 'dataclasses'
f.py:1: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
```

I don't want to ignore-missing-imports, since I want dataclasses to be type indeed checked (I'm guessing it won't be type-checked if I do ignore imports, correct me if I'm wrong), so I pass Python 3.7 path:

```
$ MYPYPATH=/usr/local/lib/python3.7 mypy f.py --show-traceback
/usr/local/lib/python3.7/abc.py:105: error: Cannot find module named '_abc'
/usr/local/lib/python3.7/abc.py:112: error: Name 'ABCMeta' already defined (possibly by an import)
/usr/local/lib/python3.7/enum.py:6: error: Cannot find module named '_collections'
/usr/local/lib/python3.7/enum.py:531: error: Name 'Enum' already defined on line 119
/usr/local/lib/python3.7/re.py:127: error: Cannot find module named '_locale'
/usr/local/lib/python3.7/re.py:127: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
/usr/local/lib/python3.7/copy.py:60: error: Cannot find module named 'org.python.core'
/usr/local/lib/python3.7/sre_compile.py:13: error: Cannot find module named '_sre'
/usr/local/lib/python3.7/functools.py:17: error: Cannot find module named '_functools'
/usr/local/lib/python3.7/sre_constants.py:18: error: Cannot find module named '_sre'
/usr/local/lib/python3.7/importlib/abc.py:6: error: Cannot find module named '_frozen_importlib'
/usr/local/lib/python3.7/importlib/abc.py:12: error: Cannot find module named '_frozen_importlib_external'
/usr/local/lib/python3.7/collections/__init__.py:30: error: Cannot find module named '_collections'
/usr/local/lib/python3.7/importlib/__init__.py:16: error: Cannot find module named '_frozen_importlib'
/usr/local/lib/python3.7/importlib/__init__.py:34: error: Cannot find module named '_frozen_importlib_external'
/usr/local/lib/python3.7/os.py:71: error: Cannot find module named 'nt'
/usr/local/lib/python3.7/importlib/_bootstrap.py:1162: error: Cannot find module named '_frozen_importlib_external'
/usr/local/lib/python3.7/io.py:51: error: Cannot find module named '_io'
/usr/local/lib/python3.7/opcode.py:19: error: Cannot find module named '_opcode'
/usr/local/lib/python3.7/ntpath.py:257: error: Cannot find module named 'nt'
/usr/local/lib/python3.7/subprocess.py:128: error: Cannot find module named '_winapi'
/usr/local/lib/python3.7/locale.py:47: error: Cannot find module named '_locale'
/usr/local/lib/python3.7/locale.py:108: error: Name 'localeconv' already defined on line 63
/usr/local/lib/python3.7/locale.py:589: error: Name 'setlocale' already defined on line 87
/usr/local/lib/python3.7/string.py:21: error: Cannot find module named '_string'
/usr/local/lib/python3.7/signal.py:1: error: Cannot find module named '_signal'
/usr/local/lib/python3.7/threading.py:12: error: Cannot find module named '_collections'
/usr/local/lib/python3.7/pickle.py:94: error: Cannot find module named 'org.python.core'
/usr/local/lib/python3.7/pickle.py:1604: error: Cannot find module named '_pickle'
/usr/local/lib/python3.7/struct.py:13: error: Cannot find module named '_struct'
/usr/local/lib/python3.7/pdb.py:1530: error: Cannot find module named '__main__'
/usr/local/lib/python3.7/_bootlocale.py:8: error: Cannot find module named '_locale'
/usr/local/lib/python3.7/bdb.py:576: error: Cannot find module named '__main__'
/usr/local/lib/python3.7/platform.py:506: error: Cannot find module named 'winreg'
/usr/local/lib/python3.7/platform.py:508: error: Cannot find module named '_winreg'
/usr/local/lib/python3.7/platform.py:591: error: Cannot find module named 'java.lang'
/usr/local/lib/python3.7/platform.py:614: error: Cannot find module named 'java'
/usr/local/lib/python3.7/platform.py:990: error: Cannot find module named 'vms_lib'
/usr/local/lib/python3.7/socket.py:49: error: Cannot find module named '_socket'
/usr/local/lib/python3.7/shutil.py:1018: error: Cannot find module named 'nt'
/usr/local/lib/python3.7/datetime.py:2415: error: Cannot find module named '_datetime'
/usr/local/lib/python3.7/mimetypes.py:31: error: Cannot find module named 'winreg'
/usr/local/lib/python3.7/xml/parsers/expat.py:4: error: No library stub file for standard library module 'pyexpat'
/usr/local/lib/python3.7/xml/parsers/expat.py:4: note: (Stub files are from https://github.com/python/typeshed)
/usr/local/lib/python3.7/bz2.py:19: error: Cannot find module named '_bz2'
/usr/local/lib/python3.7/lzma.py:27: error: Cannot find module named '_lzma'
/usr/local/lib/python3.7/hashlib.py:80: error: Cannot find module named '_sha1'
/usr/local/lib/python3.7/hashlib.py:83: error: Cannot find module named '_md5'
/usr/local/lib/python3.7/hashlib.py:86: error: Cannot find module named '_sha256'
/usr/local/lib/python3.7/hashlib.py:90: error: Cannot find module named '_sha512'
/usr/local/lib/python3.7/hashlib.py:94: error: Cannot find module named '_blake2'
/usr/local/lib/python3.7/hashlib.py:99: error: Cannot find module named '_sha3'
/usr/local/lib/python3.7/hashlib.py:159: error: Cannot find module named '_hashlib'
/usr/local/lib/python3.7/ssl.py:98: error: Cannot find module named '_ssl'
/usr/local/lib/python3.7/typing.py:1326: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.610
/usr/local/lib/python3.7/typing.py:1326: : note: please use --show-traceback to print a traceback when reporting a bug
```

Lots of errors. Is my Python 3.7 installed incorrectly? 

The last error is **error: INTERNAL ERROR**, so with traceback:

```
$ MYPYPATH=/usr/local/lib/python3.7 mypy f.py --show-traceback
[...]
/usr/local/lib/python3.7/typing.py:1326: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.610
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/usr/local/lib/python3.7/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 185, in build
    flush_errors, fscache)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 285, in _build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2398, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2691, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2801, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2009, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options, patches)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 297, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 3301, in accept
    node.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 586, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 366, in visit_func_def
    self._visit_func_def(defn)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 429, in _visit_func_def
    self.analyze_function(defn)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 656, in analyze_function
    defn.body.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 868, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 1542, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 3301, in accept
    node.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 916, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 1624, in visit_assignment_stmt
    self.named_tuple_analyzer.process_namedtuple_definition(s, self.is_func_scope())
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal_namedtuple.py", line 115, in process_namedtuple_definition
    named_tuple = self.check_namedtuple(s.rvalue, name, is_func_scope)
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal_namedtuple.py", line 150, in check_namedtuple
    return self.build_namedtuple_typeinfo('namedtuple', [], [], {})
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal_namedtuple.py", line 249, in build_namedtuple_typeinfo
    iterable_type = self.api.named_type_or_none('typing.Iterable', [implicit_any])
  File "/usr/local/lib/python3.7/site-packages/mypy/semanal.py", line 1267, in named_type_or_none
    assert isinstance(node, TypeInfo)
AssertionError: 
/usr/local/lib/python3.7/typing.py:1326: : note: use --pdb to drop into pdb
```

Is this the same issue as https://github.com/python/mypy/issues/5092? I'm not using ANY virtualenv, pipenv, pyenv, etc.

**Comment by JelleZijlstra** [comment]
You generally shouldn't be pointing MYPYPATH to the 3.7 install; mypy doesn't look directly at the stdlib, but instead uses stub files defined in the typeshed repo. Dataclasses was added to typeshed about a month ago (https://github.com/python/typeshed/commits/master/stdlib/3.7/dataclasses.pyi), but apparently this didn't make it into the 0.610 release.

The next release (which is coming up soon) should have it though. Until then you can use the git master version of mypy.

**Comment by pawelswiecki** [comment]
OK, I see thanks! 

You are correct: mypy installed from the current master is not reporting "Cannot find module named 'dataclasses'" error. Closing the issue.
