### ISSUE TITLE
0.750 regression: Incompatible types with enumerate()/sorted() and property

### ISSUE THREAD

**Issue by The-Compiler** [python/mypy#8064]
With 0.750 and this code:

```python
from typing import TypeVar, Sequence

_T = TypeVar('_T')


class NeighborList:

    def __init__(self, items: Sequence[_T]) -> None:
        self._items = items

    def print_sorted(self) -> None:
        print(sorted(enumerate(self.items), key=lambda e: e[1]))  # <---

    @property
    def items(self) -> Sequence[_T]:
        return self._items


nl = NeighborList([1, 2, 3])
nl.print_sorted()
```

I get:

```
x.py:12: error: Argument 1 to "sorted" has incompatible type "enumerate[_T]"; expected "Iterable[Tuple[int, _T]]"
x.py:12: error: Argument 1 to "enumerate" has incompatible type "Sequence[_T]"; expected "Iterable[_T]"
```

I bisected this, it was introduced in 9d5d0e906deb1469f1c283ecacf07d4d9ff43698 (part of #7933, fix for #7863).

When I remove the property and use `self._items` directly, things seem to be fine.

#7434 looks somewhat similar to me, but I don't think it's the same issue.

**Comment by ilevkivskyi** [comment]
Mypy is correct, you should make the class generic using `Generic[_T]` base, otherwise these annotations don't make much sense (there is another issue to give a better error message in such cases, see https://github.com/python/mypy/issues/6520).
