### ISSUE TITLE
dmypy crash when importing arch (with mypy 1.14.0 and 1.15.0)

### ISSUE THREAD

**Issue by snook92** [python/mypy#18893]
**Crash Report**

dmypy crashing after 3 runs one one file (see below) but mypy works fine.

Can reproduce with 1.14.0 and 1.15.0. Works fine with 1.13.0.

**Traceback**

```
$ dmypy run -v -- ./envdebug.py 
envdebug.py:5: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.15.0
envdebug.py:5: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.15.0
envdebug.py:5: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.15.0
envdebug.py:4: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.15.0
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 237, in serve
  File "mypy/dmypy_server.py", line 286, in run_command
  File "mypy/dmypy_server.py", line 354, in cmd_run
  File "mypy/dmypy_server.py", line 433, in check
  File "mypy/dmypy_server.py", line 701, in fine_grained_increment_follow_imports
  File "mypy/server/update.py", line 286, in update
  File "mypy/server/update.py", line 882, in propagate_changes_using_dependencies
  File "mypy/server/update.py", line 1026, in reprocess_nodes
  File "mypy/checker.py", line 519, in check_second_pass
  File "mypy/checker.py", line 531, in check_partial
  File "mypy/checker.py", line 578, in accept
  File "mypy/errors.py", line 1289, in report_internal_error
  File "mypy/checker.py", line 576, in accept
  File "mypy/nodes.py", line 811, in accept
  File "mypy/checker.py", line 1052, in visit_func_def
  File "mypy/checker.py", line 1056, in _visit_func_def
  File "mypy/checker.py", line 1090, in check_func_item
  File "mypy/checker.py", line 1366, in check_func_def
  File "mypy/checker.py", line 578, in accept
  File "mypy/errors.py", line 1289, in report_internal_error
  File "mypy/checker.py", line 576, in accept
  File "mypy/nodes.py", line 1258, in accept
  File "mypy/checker.py", line 2971, in visit_block
  File "mypy/checker.py", line 578, in accept
  File "mypy/errors.py", line 1289, in report_internal_error
  File "mypy/checker.py", line 576, in accept
  File "mypy/nodes.py", line 1454, in accept
  File "mypy/checker.py", line 4635, in visit_return_stmt
  File "mypy/checker.py", line 4671, in check_return_stmt
  File "mypy/checkexpr.py", line 5905, in accept
  File "mypy/errors.py", line 1289, in report_internal_error
  File "mypy/checkexpr.py", line 5903, in accept
  File "mypy/nodes.py", line 2108, in accept
  File "mypy/checkexpr.py", line 3493, in visit_op_expr
  File "mypy/checkexpr.py", line 4178, in check_op
  File "mypy/messages.py", line 197, in add_errors
  File "mypy/errors.py", line 530, in add_error_info
  File "mypy/errors.py", line 467, in _add_error_info
AssertionError
```

**To Reproduce**

1/ create a file envdebug.py:
```
import arch


def bad_function4(s: str) -> int:
    return s + 4
```

2/ run 3 times in a row

```
dmypy run -v -- ./envdebug.py 

```

**Your Environment**

- Mypy version used: 1.14.0 or 1.15.0 
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.11.11
- Operating system and version: Red Hat Enterprise Linux release 8.10 (Ootpa)

Related packages
```
arch                               7.0.0
mypy                               1.15.0
mypy_extensions                    1.0.0
numpy                              1.26.4
pandas                             2.2.3
scipy                              1.15.2
```

**Comment by sterliakov** [comment]
Hm, I'm unable to reproduce. I configured exactly the same setup (ubuntu instead of Red Hat being the only difference).

```sh
$ ls -la
total 4
drwx------  3 stas stas   80 Apr  8 18:27 .
drwxrwxrwt 98 root root 2120 Apr  8 18:27 ..
-rw-rw-r--  1 stas stas   65 Apr  7 22:00 envdebug.py
drwxrwxr-x  4 stas stas  180 Apr  7 21:53 .venv

$ python --version
Python 3.11.11

$ uv pip freeze
arch==7.0.0
mypy==1.15.0
mypy-extensions==1.0.0
numpy==1.26.4
packaging==24.2
pandas==2.2.3
pathspec==0.12.1
patsy==1.0.1
python-dateutil==2.9.0.post0
pytz==2025.2
scipy==1.15.2
six==1.17.0
statsmodels==0.14.4
typing-extensions==4.13.1
tzdata==2025.2

$ cat envdebug.py
import arch


def bad_function4(s: str) -> int:
    return s + 4

$ for i in {1..10}; do dmypy run -- ./envdebug.py; done
Daemon started
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
envdebug.py:5: error: Unsupported operand types for + ("str" and "int")  [operator]
Found 1 error in 1 file (checked 1 source file)
```

Are there any other unknowns? `pyproject.toml`? `mypy.ini`? Nested directories/modules? Does it happen if you remove (or better rename to have a backup) all caches first?

**Comment by snook92** [comment]
Indeed, I cannot reproduce it on a freshly created conda env. Seems to be specifics to some prebuilt env I'm using. We can close the ticket for now and I will reopen it when I find a way for you to reproduce it. Thanks for looking into it.

**Comment by brianschubert** [comment]
I can reproduce this on master. I agree this looks like #18396; let's continue tracking this there
