### ISSUE TITLE
Regression: descriptors don't work on protocols

### ISSUE THREAD

**Issue by eltoder** [python/mypy#19262]
Descriptors don't work when used as attributes on Protocols. The same code works on a regular class. This worked for many years up to and including mypy 1.15, but stopped working in 1.16.

**To Reproduce**

https://mypy-play.net/?mypy=1.16.0&python=3.11&gist=e1f1bd3254690db213102de71f894854
```python
from typing import Protocol, assert_type

class Desc:
    def __get__(self, obj, owner=None) -> int:
        return 1

class HasDesc(Protocol):
    a: Desc

obj: HasDesc
assert_type(obj.a, int)
```

**Expected Behavior**

This code should type-check. If works with mypy 1.15 or when `HasDesc` is not a protocol.

**Actual Behavior**

```
main.py:11: error: Expression is of type "Desc", not "int"  [assert-type]
```

**Your Environment**

- Mypy version used: 1.16.0
- Mypy command-line flags:
- Python version used: 3.11

**Comment by brianschubert** [comment]
Thanks! Closing as duplicate of #19054

**Comment by brianschubert** [comment]
As a workaround, you can try annotating the protocol member as a `ClassVar`: https://mypy-play.net/?mypy=1.16.0&python=3.11&gist=9db8f68d93df061e745e4ce45c0daa5e

**Comment by eltoder** [comment]
Good idea, but unfortunately this makes actual classes incompatible with the protocol: https://mypy-play.net/?mypy=1.16.0&python=3.11&gist=9321d98d479917bd489d5be8872a509b

**Comment by brianschubert** [comment]
Mypy will accept it if you also annotate the class assignments as `ClassVar`, though I realize that could mean a lot of code churn: https://mypy-play.net/?mypy=1.16.0&python=3.11&gist=65196eafe5d72a12a5d7baadb2d5ace7

**Comment by eltoder** [comment]
Yeah, I don't want to update all my classes to work-around something that will hopefully get fixed.

**Comment by eltoder** [comment]
It's also pretty verbose and ugly. Your snippet is missing the type argument to `ClassVar`, so you lost typing on the actual class.
