### ISSUE TITLE
No type narrowing on TypedDict values

### ISSUE THREAD

**Issue by whtsky** [python/mypy#10701]
**Bug Report**

a.py: 
```python
from typing import Optional
from typing import TypedDict

class D(TypedDict):
    a: int


v: Optional[D]

v and v['a']

class P(TypedDict):
    v: Optional[D]

p: P
p['v'] and p['v']['a']
```

**To Reproduce**

```bash
mypy a.py
```

**Expected Behavior**

No error report

**Actual Behavior**

```
a.py:16: error: Value of type "Optional[D]" is not indexable
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: no flags
- Mypy configuration options from `mypy.ini` (and other config files): no config file
- Python version used: Python 3.9.4

**Comment by bluetech** [comment]
Doesn't reproduce for me in master. According to git bisect, this was fixed by 8e82171a3e68a5180fab267cad4d2b7cfa1f5cdc "Improve type narrowing for walrus operator in conditional statements (#11202)", which is coincidentally the current HEAD as I'm writing this :)

**Comment by hauntsaninja** [comment]
Thanks for checking bluetech! Going to go ahead and close this issue then
