### PR TITLE
Infer type var tuple contents in more situations

### PR DESCRIPTION
**Pull request by A5rocks**
Supersedes https://github.com/python/mypy/pull/17512 as I figured out how to handle this case in a more general manner.

This PR fixes https://github.com/python/mypy/issues/16522. It adds a mechanism for constraints to be discarded if they are less likely to be correct: for instance, if you pass `f(x: int, y: str = "42")` to `Callable[[Unpack[Ts]], None]` it's not clear whether `y` should be included in an unpacked `TypeVarTuple`. This PR makes it such that `function_using_typevartuple(f, 42)` discards constraints based on `f`.

### CODE REVIEW

**Comment by A5rocks** [comment]
The only bad change in mypy primer is:

```
+ homeassistant/components/homekit/accessories.py:656: error: Argument 2 to "async_dispatcher_send" has incompatible type "SignalType[tuple[str, ...]]"; expected "SignalType[tuple[str]]"  [arg-type]
```

... and I'm not quite sure if there's a good way to solve this. We could check whether constraints interfere with each other and only if they do prefer the higher quality ones? That sounds slow, though.

**Comment by A5rocks** [comment]
@ilevkivskyi this is my best guess at a mechanism that would handle `TypeVarTuple` inference when there's also kwargs that need to be discarded. Does it seem reasonable?
