### ISSUE TITLE
Problem with sorted() and _LT

### ISSUE THREAD

**Issue by jolaf** [python/mypy#9582]
The following code:
```python3
from typing import Sequence
class A:
    pass
d: Sequence[A] = ()
s = sorted(d)
print("OK")
```
produces the following output:
```python3
$ python3 Test.py
OK
$ mypy Test.py
Test.py:8:5: error: Value of type variable "_LT" of "sorted" cannot be "A"  [type-var]
    s = sorted(d)
$ python3 --version
Python 3.8.5
$ mypy --version
mypy 0.790
```
The code seems perfectly valid, so `mypy` reaction looks a false positive.

**Comment by srittau** [comment]
Actually adding items fails at runtime:

```python
from typing import Sequence
class A:
    pass
d: Sequence[A] = (A(), A())
s = sorted(d)
print("OK")
```

```
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    s = sorted(d)
TypeError: '<' not supported between instances of 'A' and 'A'
```

**Comment by pmantica1** [comment]
I saw the same `Value of type variable "_LT" of "sorted" ...` issue pop up when I bumped the mypy version number from 0.782 to 0.790.

**Comment by hauntsaninja** [comment]
This is a new trick mypy has learned. The error message is a little inscrutable, but has already been improved on master (https://github.com/python/typeshed/pull/4579). As Sebastian mentions, in this case the error is valid, so I'm closing.
If others are running into the same error, but in a case where they believe it's a false positive, feel free to file another issue

**Comment by JarnoRFB** [comment]
When using generics, you can get around this by bounding your `A` on a comparable type. That does not ship with python so you have to define it yourself at the moment:

```python

C = TypeVar("C", bound="Comparable")


class Comparable(Protocol):
    @abstractmethod
    def __eq__(self, other: Any) -> bool:
        ...

    @abstractmethod
    def __lt__(self: C, other: C) -> bool:
        ...

    def __gt__(self: C, other: C) -> bool:
        return (not self < other) and self != other

    def __le__(self: C, other: C) -> bool:
        return self < other or self == other

    def __ge__(self: C, other: C) -> bool:
        return not (self < other)
```

This idea comes from another mypy issue.

**Comment by hauntsaninja** [comment]
Yup. The ingredients you need for many fixes are:
```
from typing import Protocol
class _SupportsLessThan(Protocol):
    def __lt__(self, __other: Any) -> bool: ...
_SupportsLessThanT = TypeVar("_SupportsLessThanT", bound=_SupportsLessThan)
```
and as mentioned^, you can use `_SupportsLessThanT` instead of a plain typevar for generic situations.

Note the error message on master is also improved: `Value of type variable "_SupportsLessThan" of "sorted" cannot be "A"`, which is hopefully clearer.

Finally, the issue for adding this protocol to typing / typing_extensions is here: https://github.com/python/typing/issues/760
