### ISSUE TITLE
Seemingly correct type narrowing, but still incompatible type

### ISSUE THREAD

**Issue by hwong557** [python/mypy#13744]
**Bug Report**

Mypy seems to type narrow correctly, but still throws an error when trying to add to a set.

**To Reproduce**

Gist URL: https://gist.github.com/c10befca044d78713b96a9706ac355b2
Playground URL: https://mypy-play.net/?mypy=master&python=3.10&gist=c10befca044d78713b96a9706ac355b2

**Expected Behavior**

No error.

**Actual Behavior**

```
main.py:15: error: Argument 1 to "add" of "set" has incompatible type "Data"; expected "Data"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: `mypy 0.990+dev.780534b13722b7b0422178c049a1cbbf4ea4255b (compiled: no)`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.7

**Comment by JelleZijlstra** [comment]
Here's an interesting variation: https://mypy-play.net/?mypy=master&python=3.10&gist=be6708082fc74cb9e2577840877b1741. If you declare a variable as of type `Data` directly, its revealed type is `"Tuple[builtins.str, builtins.int, fallback=__main__.Data]"` instead of `__main__.Data`.

**Comment by sterliakov** [comment]
This is resolved (fails up to and including 1.6.1, works in 1.7.0 through current master). Bisects to seemingly unrelated #249f3f (PR #16053)

**Comment by hauntsaninja** [comment]
Thanks, yeah I guess subtyping changes in that PR help

**Comment by ilevkivskyi** [comment]
Actually it looks like #16053 introduced a subtle bug in subtyping, this is why it fixed this issue. I will at fixing myself soon, I am not going to re-open this, as there is a conveniently open duplicate https://github.com/python/mypy/issues/15299, that also looks fixed because of the subtyping bug.
