### PR TITLE
Docs: show how to @overload function annotations in user code

### PR DESCRIPTION
**Pull request by jkleint**
The docs say `@override` doesn't work in user code, but it seems to work in mypy 0.470.
The update may be waiting on #2603, but that PR does not seem to include doc updates,
so feel free to put this patch in that PR.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Hm, it doesn't actually work yet AFAICT. The example you give produces an error for me:
```
ov.py:11: error: Name '__getitem__' already defined
```
So we're still waiting for #2603. Thanks for the contribution though! Once that is in, this will be very helpful.

File: docs/source/function_overloading.rst [hunk 1]
```diff
@@ -1,60 +1,63 @@
...
-``abs`` function that works for both ``int`` and ``float`` arguments:
+Sometimes the types in a function depend on each other in ways that can't be 
+captured with a simple ``Union``.  For example, the ``__getitem__`` (``[]`` bracket 
+indexing) method can take an integer and return a single item, or take a ``slice`` 
+and return a ``Sequence`` of items.  You might be tempted to annotate it like so:
 
 .. code-block:: python
 
-   # This is a stub file!
+    class Seq(Generic[T], Sequence[T]):
```
Comment (ilevkivskyi) [inline docs/source/function_overloading.rst]: ``Generic[T]`` here and below are redundant.

File: docs/source/function_overloading.rst [hunk 2]
```diff
@@ -1,60 +1,63 @@
...
-Note that we can't use ``Union[int, float]`` as the argument type,
-since this wouldn't allow us to express that the return
-type depends on the argument type.
+    from typing import Generic, Sequence, overload
+    T = TypeVar('T')
 
-Now if we import ``abs`` as defined in the above library stub, we can
-write code like this, and the types are inferred correctly:
+    class Seq(Generic[T], Sequence[T]):
+        @overload       # These are just for the type checker, and overwritten by the real implementation
```
Comment (ilevkivskyi) [inline docs/source/function_overloading.rst]: Such long comments will look a bit ugly on ``readthedocs``. I would recommend wrapping them or shortening to approx. 80 chars.

**Comment by gvanrossum** [comment]
OK, I can merge once you approve it.

**Comment by pkch** [comment]
Is it worth adding the information about the order of `@overload` statements here? It seems that they [matter](https://github.com/python/mypy/issues/1941#issuecomment-235357559):

> Mypy lets you vary the return type even if multiple variants match if your signatures are ordered from narrower to more general. 

but I'm not sure if it's official or undocumented feature; and also whether it's the entire signature needs to be "narrower" or just the argument or return type.

**Comment by gvanrossum** [comment]
Pardon my intervention, I'm superseding this with PR #3159.
