### ISSUE TITLE
Decorated properties report error: "not callable" in mypy 1.7.1 and master

### ISSUE THREAD

**Issue by rouge8** [python/mypy#16694]
**Bug Report**

Prior to mypy 1.7, we were able to add decorators on top of properties by adding a `# type: ignore` comment. In 1.7.1, the decorated attribute now errors on access with `not callable [operator]`.

**To Reproduce**

https://mypy-play.net/?mypy=1.7.1&python=3.11&gist=12b3add6be6394238695b9b42c79d425

**Expected Behavior**

No errors.
**Actual Behavior**

```
main.py:20: error: "MyObj" not callable  [operator]
Found 1 error in 1 file (checked 1 source file)
```
**Your Environment**

- Mypy version used: 1.7.1, master
- Python version used: 3.11

**Comment by rouge8** [comment]
This was broken by https://github.com/python/mypy/pull/15926 cc @hauntsaninja

**Comment by ego-thales** [comment]
+1
Same here:
```python
def decorator(x: object) -> object: ...

class Foo:
    @decorator  # type: ignore[prop-decorator]
    @property
    def foo(self) -> None:
        return

    def bar(self) -> None:
        breakpoint()
        self.foo
```

In my case, I wish to use `decorator` as a simple "wrapper flag" for a metaclass mechanism, that is unwrapped before class creation.

I know that it is explicitly stated that decorated properties are not supported, but it would be great to at least get away with this simple `# type: ignore[prop-decorator]` comment. Is there any ongoing investigation on this issue?

Thanks!
All the best :)
