### PR TITLE
Correctly aggregate narrowing information on parent expressions

### LINKED ISSUE #20596: Regression with narrowing with multiple `hasattr`
```
[case testMultipleHasAttr]
# flags: --warn-unreachable
from __future__ import annotations
from typing import Any

def len(obj: object) -> Any: ...

def f(x: type | str):
    if (
        hasattr(x, "__origin__")
        and x.__origin__ is list
        and hasattr(x, "__args__")
        and len(x.__args__) == 1
    ):
        reveal_type(x.__args__[0])  # N: Revealed type is "Any"
[builtins fixtures/module.pyi]
```

Regression introduced in https://github.com/python/mypy/pull/20492 that I don't yet have fixed in my commit stack. Probably just need to manage the conditional type maps a little more carefully

### LINKED ISSUE #21204: [1.20 regression] narrowing failure with unrelated boolean
**Bug Report**

Mypy 1.20 and master report an incorrect error that seems to be a failure of type narrowing in the following case:

```python
class FancyInteger(int):
    name = 'fancy'

    def __repr__(self):
        return f'{int(self)}!'

    def __str__(self):
        return f'{int(self)}!'


def stringify(value: object) -> str:
    if isinstance(value, (str, int)) or value is None:
        if value.__class__.__str__ == FancyInteger.__str__ and isinstance(value, FancyInteger):
            return f"{value.__class__.__name__}.{value.name}"
    return str(value)
```

[**playground link**](https://mypy-play.net/?mypy=latest&python=3.12&gist=a6f8ba95151fa5e0003273b812d8223e)

This passes in MyPy 1.19.1, and is ostensibly correct code -- this is a minimised version, but the original performs similar checks with `enum.StrEnum`, so not that esoteric.

If the `value.__class__.__str__ == FancyInteger.__str__` comparison is removed, or split to a new `if` statement, the error fails to reproduce.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.12&gist=a6f8ba95151fa5e0003273b812d8223e

**Expected Behavior**

No error

**Actual Behavior**

```shell
$ uvx mypy==1.20
bug.py:14: error: Item "str" of "str | int" has no attribute "name"  [union-attr]
bug.py:14: error: Item "int" of "str | int" has no attribute "name"  [union-attr]
Found 2 errors in 1 file (checked 1 source file)
$ uvx mypy==1.19.1
Success: no issues found in 1 source file
```

**Your Environment**

- Mypy version used: 1.20 & 1.19.1
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.12 & 3.14

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #21204 , fixes #20596

The extra narrowing we perform in mypy 1.20 exposes this much longer standing issue

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]
Thanks! This makes things much cleaner.
