### PR TITLE
Fix crash when inferring multiple assignment with overloaded function

### LINKED ISSUE #10653: 0.902 crashes on tuple assignment
**Crash Report**

Mypy crashed after upgraded from 0.812 to 0.902

**Traceback**

```
/Users/admin/Library/Caches/pypoetry/virtualenvs/test/lib/python3.8/site-packages/mode/services.py:684: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.902
Traceback (most recent call last):
  File "mypy/checker.py", line 401, in accept
  File "mypy/nodes.py", line 1073, in accept
  File "mypy/checker.py", line 2013, in visit_assignment_stmt
  File "mypy/checker.py", line 2051, in check_assignment
  File "mypy/checker.py", line 2551, in check_assignment_to_multiple_lvalues
  File "mypy/checker.py", line 2592, in check_multi_assignment
  File "mypy/checker.py", line 2701, in check_multi_assignment_from_tuple
AssertionError:
/Users/admin/Library/Caches/pypoetry/virtualenvs/test/lib/python3.8/site-packages/mode/services.py:684: : note: use --pdb to drop into pdb
```

**To Reproduce**

**Your Environment**

- Mypy version used: 0.902
- Mypy command-line flags: --html-report .mypy_report --txt-report .mypy_report src/
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.8.8
- Operating system and version: macOS Big Sur 11.4

### PR DESCRIPTION
**Pull request by JukkaL**
When using lvalue context to re-infer call to an overloaded function,
the inferred tuple type can switch to Any. Defensively accept this. It
probably means that an Any component in argument types causes ambiguity.

Fixes #10653.

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]
Makes sense.

**Review by TH3CHARLie — APPROVED** [review]
I wouldn't come up with fixing here, nice!
