### ISSUE TITLE
Starting from version 1.0.0, a union of Generators is (sometimes) treated as if it has no ReturnType

### ISSUE THREAD

**Issue by mwchase** [python/mypy#15141]
**Bug Report**

Starting from version 1.0.0, `yield from` a union on `Generator` types generates the error `Function does not return a value  [func-returns-value]`, and attempting to use the return reveals that Mypy is, in fact, treating it as if it's None.

There are ways around this; it appears that the inference is a little smarter at function boundaries than in-line, so I've just defined a bunch of helper functions to work around it for now.

**To Reproduce**

```python
from typing import Generator, TypeVar

T = TypeVar("T")


def my_iter(arg: Generator[int, None, T] | Generator[str, None, T]) -> Generator[int | str, None, T]:
    return (yield from arg)
```
(https://mypy-play.net/?mypy=0.991&python=3.11&gist=5c3183a0d4d1c02161211b01654d519f)

(The repro is working with `YieldType`, but in my code it's changing `ReturnType`. It breaks either way around.)

**Actual Behavior**

On post-1.0.0 versions:
```
main.py:7: error: Function does not return a value  [func-returns-value]
main.py:7: error: Incompatible return value type (got "None", expected "T")  [return-value]
Found 2 errors in 1 file (checked 1 source file)
```
Pre-1.0.0, produces no output.

**Comment by hauntsaninja** [comment]
I bisected this back to #14224 , which fixed a case where we were basically not type checking coroutines and generators. My guess is you'd need to make a similar change in https://github.com/python/mypy/blob/6b326d556e3a34949c363ef1f728abda164a9f24/mypy/checkexpr.py#L5079

**Comment by hauntsaninja** [comment]
By the way, did you happen to encounter this regression in an open source project?

**Comment by mwchase** [comment]
This is in something I'm working on that's *technically* open source, but not in any convenient way; I don't really want to publicize it anywhere before it's useful.

**Comment by hauntsaninja** [comment]
Thanks! I'd love to include it in mypy_primer so we avoid similar regressions in the future; if you're ever comfortable with that, feel free to post a link to the project here
