### ISSUE TITLE
Compiled wheel build broken on macOS

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#9500]
Mypy wheel builds are broken on macOS. Example failure: https://travis-ci.org/github/mypyc/mypy_mypyc-wheels

There are errors like this:

```
build/__native_dbbd1b679b3c31e8ff5a.c:2272:53: error: implicit conversion from 'long long' to 'CPyTagged' (aka 'unsigned long') changes value from 9223372036854775806 to 4294967294 [-Werror,-Wconstant-conversion]
    cpy_r_r71 = CPyList_GetSlice(cpy_r_matching, 2, 9223372036854775806);
                ~~~~~~~~~~~~~~~~                    ^~~~~~~~~~~~~~~~~~~
```

If I'm not mistaken, we are building both 32-bit and 64-bit binaries:

```
clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 ...
```

(Relevant documentation: https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/64bitPorting/building/building.html)

I suspect that the 32-bit binaries are broken, since mypyc assumes that the target bit width is the same as the CPython bit width, which isn't the case here. The builds are running on a 64-bit Python, but we are building both 32-bit and 64-bit binaries.

We have at least two options to fix the issue:
- Generate code that can be compiled on both 32-bit and 64-bit platforms, instead of specializing the code for each one.
- Only provide 64-bit binaries on macOS.

MacBooks have been 64-bit since 2006. OS X 10.6 (released 2009) was the last version to support 32-bit hardware. It seems totally reasonable to drop 32-bit binaries.

**Comment by JukkaL** [comment]
I was able to fix builds on 3.6 and 3.7 by switching to a 64-bit-only CPython when building the wheels. Python 3.5 has only a mixed 32/64-bit installer, and that seems the source of our problems. Since 3.5 is reaching it's end of life soon, I'm going to try a hacky 3.5-only fix.

**Comment by msullivan** [comment]
I thought there was a hack to remove 32 bit support on os x by patching out
of the compiler command line? Did that break?

**Comment by JukkaL** [comment]
The patching out doesn't seem to work, at least on Travis. I can try to reproduce the issue locally.

An even more hacky fix would be to clamp some big integer literals in the generated C to 32 bits even on a 64-bit Python 3.5 build on macOS. This would break some operations on lists that have more than 2 billion items, which seems marginal enough.

**Comment by JukkaL** [comment]
I wasn't able to reproduce this locally. The extra `-arch` argument was removed correctly on Python 3.5.4 when I tried it. Since debugging travis builds is kind of painful, I'm going to give up and implement the alternative fix for now.

**Comment by JukkaL** [comment]
This works now. The fix shouldn't even break list operations, it just makes them a bit slower on Python 3.5 running on macOS.
