### ISSUE TITLE
0.720 regression for base type aliases

### ISSUE THREAD

**Issue by asvetlov** [python/mypy#7391]
Have the following code:
```
from contextlib import AbstractContextManager
from typing import TYPE_CHECKING, Optional, Type
from types import TracebackType

if TYPE_CHECKING:
    _Base = AbstractContextManager['A']  # problematic "line 6"
else:
    _Base = AbstractContextManager

class A(_Base):
    def __enter__(self) -> 'A':
        return self

    def __exit__(self,
                 exc_type: Optional[Type[BaseException]],
                 exc_val: Optional[BaseException],
                 exc_tb: Optional[TracebackType],
                 ) -> Optional[bool]:
        return None

a = A()
```

Since I cannot use `AbstractContextManager['A']` expression in runtime I've extracted it into `_Base = AbstractContextManager['A']` alias under `if TYPE_CHECKING` condition.
It used to work fine in mypy==0.711 but in 0.720 I see reports like
```
cm.py:6: error: Cannot resolve name "_Base" (possible cyclic definition)
cm.py:6: error: Cannot resolve name "A" (possible cyclic definition)
```

Sure, I can replase `contextlib.AbstractContextManager[T]` with `typing.ContextManager[T]` (which seems to work fine) but I'm curious for the reason for regression.

**Comment by JukkaL** [comment]
The reason for the regression is that 0.720 enabled the new semantic analyzer, which processes forward references differently from 0.710. @ilevkivskyi is working on a new feature called recursive types that may fix this regression. 

@ilevkivskyi Do you believe that recursive types would fix this issue?

**Comment by ilevkivskyi** [comment]
Yes.

**Comment by wmichelin** [comment]
Also running into this issue when trying to represent a tree structure with MyPy.

```
from typing import NamedTuple

class Foo(NamedTuple):
    the_bar: "Bar"
    
class Bar(NamedTuple):
    the_foo: Foo

```

yields

```
main.py:4: error: Cannot resolve name "Bar" (possible cyclic definition)
Found 1 error in 1 file (checked 1 source file)
```

**Comment by wmichelin** [comment]
Update: I was able to work around the issue by converting the `NamedTuple`s into dataclasses. I don't understand why but it works.

**Comment by grthr** [comment]
Any progress on this topic? Seems to be still an issue with 0.782...

**Comment by ilevkivskyi** [comment]
This works on master.
