### PR TITLE
Do not treat `match` value patterns as `isinstance` checks

### LINKED ISSUE #20358: numpy dtype Statement is unreachable with mypy 1.19.0
**Bug Report**
When checking the type field of a dtype with match, mypy 1.19.0 complains sbout some cases with  ` error: Statement is unreachable`.
It doesn't look like a numpy bug because swapping the order of the cases (eg. moving the int32 case to the top) it produces inconsistent results (eg. it generates 1 error instead of 2).

**To Reproduce**

```python
import numpy as np


def f(dt: np.dtype) -> None:
    match dt.type:
        case np.float64:
            print("f")
        case np.int64:
            print("i")
        case np.int32:
            print("i")


dt: np.dtype = np.dtype(np.float64)
f(dt)
```

**Expected Behavior**

Mypy should not complain

**Actual Behavior**
```
kk.py:9: error: Statement is unreachable  [unreachable]
                print("i")
                ^~~~~~~~~~
kk.py:11: error: Statement is unreachable  [unreachable]
                print("i")
                ^~~~~~~~~~
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.19.0
- Mypy command-line flags: `mypy --warn-unreachable kk.py`
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.14.0

### PR DESCRIPTION
**Pull request by sterliakov**
Fixes #20358.

As discovered by @randolf-scholz in #20142, `mypy` treats value patterns in match statement in a completely wrong way. 

From [PEP 622](https://peps.python.org/pep-0622/#literal-patterns):

> Literal pattern uses equality with literal on the right hand side, so that in the above example number == 0 and then possibly number == 1, etc will be evaluated.

Existing tests for the feature are invalid: for example,

```python
foo: object

match foo:
    case 1:
        reveal_type(foo)
```

must reveal `object`, and test `testMatchValuePatternNarrows` asserts the opposite. Here's a runtime example:

```
>>> class A:
...     def __eq__(self,o): return True
...     
>>> match A():
...     case 1:
...         print("eq")
...         
eq
```

I have updated the existing tests accordingly.

The idea is that value patterns are essentially equivalent to `if foo == SomeValue` checks, not `isinstance` checks modelled by `conditional_types_wit_intersection`.

The original implementation was introduced in #10191.

### CODE REVIEW

**Comment by sterliakov** [comment]
I'm frankly not sure what part of the core team to ping here - reviewers of the original PR, @JukkaL? @randolf-scholz please also take a look if you have time, IIRC some recent PRs of yours were related to pattern matching?

Primer finds nothing, apparently `match` isn't that popular in wild...

**Comment by randolf-scholz** [comment]
> Primer finds nothing, apparently match isn't that popular in wild...

Well, many popular projects still support 3.9, but match-case requires at least 3.10, so that's not surprising.

**Comment by randolf-scholz** [comment]
One thing that might be worth testing is if it interacts correctly with unions types and union patterns, e.g.

```python
from typing import Literal

def test1(x: Literal[1,2,3]) -> None:
    match x:
        case 1:
            reveal_type(x)
        case other:
            reveal_type(x)

def test2(x: Literal[1,2,3]) -> None:
    match x:
        case 1:
            reveal_type(x)
        case 2:
            reveal_type(x)
        case 3:
            reveal_type(x)
        case other:
            assert_never(x)

def test3(x: Literal[1,2,3]) -> None:
    match x:
        case 1 | 3:
            reveal_type(x)
        case other:
            reveal_type(x)
```

and possibly the same with enum arguments / enum patterns.

**Comment by sterliakov** [comment]
I don't want to add any enum tests here, they won't be representative due to #19594 - I'd prefer to add `match` equivalents to tests there once this PR is merged. Unions are more relevant, thanks!

File: mypy/checker.py
Comment (A5rocks) [inline mypy/checker.py:6638]: I see *why* you split this function, but it doesn't seem necessary?

File: test-data/unit/check-python310.test [hunk 1]
```diff
@@ -83,7 +83,7 @@ m: A
 
 match m:
     case b.b:
-        reveal_type(m)  # N: Revealed type is "__main__.<subclass of "__main__.A" and "b.B">"
+        reveal_type(m)  # N: Revealed type is "__main__.A"
```
Comment (A5rocks) [inline test-data/unit/check-python310.test:86]: This was confusing for me until I realized that's just how equality works!

File: mypy/checkpattern.py [hunk 2]
```diff
@@ -205,12 +204,15 @@ def visit_value_pattern(self, o: ValuePattern) -> PatternType:
         current_type = self.type_context[-1]
         typ = self.chk.expr_checker.accept(o.expr)
         typ = coerce_to_literal(typ)
```
Comment (A5rocks) [inline mypy/checkpattern.py:206]: Is this `coerce_to_literal` still necessary now that we use `narrow_type_by_equality` rather than `conditional_types_with_intersection`?

File: mypy/checker.py
Comment (sterliakov) [reply mypy/checker.py:6638]: Hm? I split it because I want to reuse `narrow_type_by_equality` in another file, and there's no possibility of `type(...) == ...` checks as part of a checked pattern. Otherwise I'd have to create a fake node to call `equality_type_narrowing_helper` on it, and I'd rather avoid doing that

File: mypy/checkpattern.py (hunk 2 above)
Comment (sterliakov) [reply mypy/checkpattern.py:206]: It probably is; we are not in literal context, so coercion won't happen there for `==`. Removing this will change the behavior significantly.

File: test-data/unit/check-python310.test [hunk 3]
```diff
@@ -2909,9 +2938,9 @@ T_Choice = TypeVar("T_Choice", bound=b.One | b.Two)
 def switch(choice: type[T_Choice]) -> None:
     match choice:
         case b.One:
-            reveal_type(choice)  # N: Revealed type is "def () -> b.One"
+            reveal_type(choice)  # N: Revealed type is "type[T_Choice`-1]"
```
Comment (ilevkivskyi) [inline test-data/unit/check-python310.test:2941]: Does this narrow the type variable upper bound? (You can check e.g. by adding an attribute to only one class and accessing it here). If not, I would say this is a regression.

Comment (sterliakov) [reply test-data/unit/check-python310.test:2941]: It does not, but I won't really call that a regression - we do not support the equivalent equality case either.

```
[case testEqualsTypeObjectTypeVar]
# flags: --warn-unreachable
from typing import TypeVar
import b

T_Choice = TypeVar("T_Choice", bound=b.One | b.Two)

def switch(choice: type[T_Choice]) -> None:
    if choice == b.One:  # E: Unsupported left operand type for == (some union)
        reveal_type(choice)  # N: Revealed type is "type[T_Choice`-1]"
        reveal_type(choice.x)  # E: "type[T_Choice]" has no attribute "x" \
                               # N: Revealed type is "Union[builtins.int, Any]"

[file b.py]
class One:
    x = 0
class Two: ...
```

so either it is unsafe or unsupported, but either way does not belong to this PR. I'll open a ticket and try to look into this later.

("unsupported left operand type" is *really* weird to see here, but it sheds some light on why the match version does not work either)

Comment (sterliakov) [reply test-data/unit/check-python310.test:2941]: It only worked before by pure coincidence, `isinstance` logic is fundamentally wrong thing to apply to value patterns.

Comment (ilevkivskyi) [reply test-data/unit/check-python310.test:2941]: > isinstance logic is fundamentally wrong thing to apply to value patterns

I understand that, but we need to minimize side effects of the fix.

Comment (ilevkivskyi) [reply test-data/unit/check-python310.test:2941]: @hauntsaninja IIRC you added this test case. Does this change look OK in context of https://github.com/python/mypy/issues/19159

Comment (sterliakov) [reply test-data/unit/check-python310.test:2941]: How often do people compare classes with `==`? I hope this is not a very popular pattern, especially multiplied by rarity of `match` statements in general caused by their novelty (they are only globally available in all non-EOL pythons since this November)...

Comment (randolf-scholz) [reply test-data/unit/check-python310.test:2941]: Isn't the behavior that https://github.com/python/mypy/issues/19159 wants unsafe to begin with? 

In the original example, if one makes `class A(b.One): ...`, then `switch(A)` will at runtime catch the `assert_never`.

Comment (ilevkivskyi) [reply test-data/unit/check-python310.test:2941]: Yeah, I vaguely remember someone already mentioned we should allow this only if the classes are final. Anyway, I would wait to see if @hauntsaninja has any objections here.

Comment (sterliakov) [reply test-data/unit/check-python310.test:2941]: Thanks @randolf-scholz! It certainly is unsafe, a subclass will not compare equal to a superclass. Could you cross-post this observation to #19159 too, please? Negative narrowing could only work with two `@final` classes, which is as close to a "corner case we can ignore for now" as possible. 

@ilevkivskyi positive narrowing you're asking about would also be unsafe if we pass a `Two` subclass with a metaclass overriding `__eq__`:

```python
[case testSomething]
from typing import TypeVar
import b

T_Choice = TypeVar("T_Choice", bound=b.One | b.Two)

def switch(choice: type[T_Choice]) -> None:
    match choice:
        case b.One:
            choice.x  # AttributeError at runtime

class Mcs(type):
    def __eq__(self, other): return True

class BadTwo(b.Two, metaclass=Mcs): ...

switch(BadTwo)


[file b.py]
class One:
    x = 0
class Two: ...
```

and I don't remember how custom mcs `__eq__` is handled - does mypy consider that off-limits?

Comment (ilevkivskyi) [reply test-data/unit/check-python310.test:2941]: I think we can assume people don't do this :-) There are other places where user-defined `__eq__` would cause a false positive, in those cases we are careful, but we can accept this false negative IMO.

Comment (hauntsaninja) [reply test-data/unit/check-python310.test:2941]: Yes, I think the change in this PR is good

I don't think losing the accidental positive narrowing here will regress much (but could be good feature to add positive narrowing for this in the future — we can ignore metaclass `__eq__`). 

(and yeah, points on negative narrowing are correct, I think we can just close #19159 )
