### ISSUE TITLE
Ask for an explicit annotation if the inferred type is None

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#3741]
Currently mypy behaves like this
```python
class C:
    def __init__(self) -> None:
        self.x = None

    def bar(self) -> None:
        self.x = 42  # Incompatible types in assignment (expression has type "int", variable has type None)
```
This may be non-intuitive for new users. Instead, it is proposed to either:
* Request an explicit annotation if the inferred type is ``None``, like we would do for ``lst = []``.
* Use partial ``None`` types, like we would do if both assignments were within the same function.

cc @vlasovskikh

**Comment by JukkaL** [comment]
Requiring an explicit annotation would be consistent with how we treat `self.x = []`. Partial types don't escape the scope that defines them and I don't want to change this. Marking this as high priority since I believe that this is a regression (the behavior was changed relatively recently, at least when not using strict optional checking).

**Comment by gvanrossum** [comment]
I bisected, and it's indeed a regression caused by PR #3024 (Make strict Optional type system changes standard). Ideally we'd have this fixed in the 0.521 release.

**Comment by gvanrossum** [comment]
CC @ddfisher

**Comment by ddfisher** [comment]
This wasn't a regression exactly, but rather a purposeful decision about how None types should work in strict Optional that we made in the early days.  This change in how NoneType was treated was incorporated into the main part of mypy along with the other main typechecking changes from strict Optional.

Also, intending for a variable to have type None based only on initial assignment isn't incredibly uncommon.  It happens 21 times in the test suite and 88 times across the Dropbox internal codebase (but it doesn't happen at all in mypy).

Have we actually had any new users confused by this?

**Comment by ddfisher** [comment]
If we decide we want to implement this and want it out by release, feel free to merge #3755.  Note that this is likely to break at least some user code.

**Comment by ethanhs** [comment]
>Have we actually had any new users confused by this?

@vlasovskikh was confused by error on the code @ilevkivskyi posted in the original comment. See https://gitter.im/python/typing?at=596faa652723db8d5e28fe6e and following comments.

**Comment by vlasovskikh** [comment]
@ethanhs @ddfisher I've added my comment about it to #3755.

**Comment by Daenyth** [comment]
> Have we actually had any new users confused by this?

We've been incorporating mypy into our production workflow and we've had people hit this and be confused. I was able to walk them through it, but I also have dived fairly deep into the docs and have been playing with mypy longer than most people here.

**Comment by ethanhs** [comment]
#3755 is closed as wontfix so closing this as well.
