### ISSUE TITLE
Cannot get type hints from python 2 packages

### ISSUE THREAD

**Issue by sqwishy** [python/mypy#5620]
In mypy 0.620, there appears to be inconsistent type checking behaviour depending on how you specify the python version. This exists for handling `-2` and `--python-version 2` arguments and is explained well in [issue #5576](https://github.com/python/mypy/issues/5576#issuecomment-418872062) and addressed by pull request #5619. However, this inconsistency also occurs with specifying the python version in the a mypy.ini configuration file.

```
$ mypy --python-version 2.7 pkgb
pkgb/__main__.py:7: error: Argument 1 to "this_is_a_typed_function" has incompatible type "int"; expected "unicode"
```
That above is expected, but when specifying the version in a config file.
```
$ echo -e "[mypy]\npython_version: 2.7" | mypy --config-file /dev/stdin pkgb
pkgb/__main__.py:1: error: Cannot find module named 'pkga'
```

For good measure, I included a python 2 print statement in the test package to ensure it is actually is running under python 2 mode ... [The example is included here](https://github.com/python/mypy/files/2383934/mypy5576.tar.gz). Extract the archive; in a Python 2 virtualenv, install the package in the `a` directory with `pip -e a`; run mypy on `pkgb`.

---

The behaviour seems to come from looking for typing information in different site-packages between the two cases. With `--python-version 2.7`, a Python 2 interpreter's site-packages are used. With the configuration file, the current interpreter's site-packages are used.

The pull request #5578 was an attempt to resolve this inconsistency by using the Python 2 site-packages in both configurations, but it seems like this broke some things for some folks.

**Comment by Michael0x2a** [comment]
Disclaimer: I haven't really been following this issue, so I may be missing some context, but I wonder if this is solvable by just having the people's whose config files broke with #5578 set the `python_executable` option in addition to the `python_version` option?

**Comment by sqwishy** [comment]
I believe in that case they would have to set `python_version` to 2.7 to check the Python 2 syntax and `python_executable` to a Python 3 interpreter to use its site-packages. There is something that ensures the versions here match and raises an exception otherwise. But maybe this should be allowed? I can't say for sure if mypy would behave as they'd like if it were allowed. That is interesting.

**Comment by ethanhs** [comment]
I think @Michael0x2a's solution is likely optimal here. I will work on a fix for this later.
