### PR TITLE
Fix in-memory cache reuse

### LINKED ISSUE #4185: Daemon mode does not preserve trees after first run
It seems that daemon does not preserve ASTs in memory after the first run. After subsequent runs this works. I think that the reason for this is that `state.meta` is `None` in `mypy.build.preserve_cache` after the first run.

cc @gvanrossum

### LINKED ISSUE #4195: Daemon anomaly
Repro:

- check out 8cd9dbec08a371222a89570dde02bb521c33a635
- `python3 misc/incremental_checker.py --seed dDWZNp2XFrtdXl9vWPH8 --sample 40 --daemon -r $PWD commit 5d86e142`  (When using in dmypy3 branch, add `--last 40`.)

Test output:
```
Assuming mypy is located at /Users/jukka/src/review-mypy
Temp repo will be cloned at /Users/jukka/src/review-mypy/tmp_repo
Testing file/dir located at /Users/jukka/src/review-mypy/tmp_repo/mypy
Using cache data located at /Users/jukka/src/review-mypy/.incremental_checker_cache.json

Cloning repo /Users/jukka/src/review-mypy to /Users/jukka/src/review-mypy/tmp_repo
Fetching last 40 commits (or all, if there are fewer commits than n)
Fetching commits starting at 5d86e142
Sampled down to 40 commits using random seed dDWZNp2XFrtdXl9vWPH8
...
Starting daemon
Note: first commit is evaluated twice to warm up cache
Now testing commit 9d10fcda: "Fix test failures caused by merging of #4059 (#4138)"
    Output matches expected result!
    Incremental: 12.147 sec
    Original:    13.906 sec
Now testing commit 9d10fcda: "Fix test failures caused by merging of #4059 (#4138)"
    Output matches expected result!
    Incremental: 0.347 sec
    Original:    13.906 sec
Now testing commit a1ace484: "Make stubgen return status 0 on --help (#4160)"
    Output matches expected result!
    Incremental: 12.525 sec
    Original:    14.196 sec
Now testing commit 3e49ef9b: "Allow subscripted aliases at function scope (#4000)"
    Output does not match expected result!
    Expected output (14.380 sec):



    Actual output: (11.295 sec):

        mypy/semanal_pass3.py:42: error: Name 'mypy.semanal.SemanticAnalyzerPass2' is not defined
        mypy/semanal_pass3.py:375: error: "Options" has no attribute "disallow_any_generics"


Now testing commit 880bf848: "Fix recent crashes in forward refs (#4120)"
    Output matches expected result!
    Incremental: 11.135 sec
    Original:    14.020 sec
...
```
(and more errors later down the run).

### LINKED ISSUE #4198: No trees are reused, ever
That's a regression introduced by #4169.

### LINKED ISSUE #4208: Daemon sometimes gives spurious errors
Repro:
```
$ git co 528b6f67738debd2376fcf24d77715ba12da64cc  # dmypy3
$ python3 misc/incremental_checker.py --limit 40 --seed dDWZNp2XFrtdXl9vWPH8 --sample 40 -r $PWD commit 5d86e142  --daemon 
Assuming mypy is located at /Users/guido/src/mypy
Temp repo will be cloned at /Users/guido/src/mypy/tmp_repo
Testing file/dir located at /Users/guido/src/mypy/tmp_repo/mypy
Using cache data located at /Users/guido/src/mypy/.incremental_checker_cache.json

Cloning repo /Users/guido/src/mypy to /Users/guido/src/mypy/tmp_repo
Fetching commits starting at 5d86e142
Sampled down to 40 commits using random seed dDWZNp2XFrtdXl9vWPH8
Skipping commit (already cached): 9d10fcdab: "Fix test failures caused by merging of #4059 (#4138)"
.
.
.
Skipping commit (already cached): 648680875: "Rename semantic analyzer classes to SemanticAnalyzerPass[123] (#4093)"

Starting daemon
Note: first commit is evaluated twice to warm up cache
Now testing commit 9d10fcdab: "Fix test failures caused by merging of #4059 (#4138)"
    Output matches expected result!
    Incremental: 19.056 sec
    Original:    16.825 sec
Now testing commit 9d10fcdab: "Fix test failures caused by merging of #4059 (#4138)"
    Output matches expected result!
    Incremental: 0.415 sec
    Original:    16.825 sec
Now testing commit a1ace484e: "Make stubgen return status 0 on --help (#4160)"
    Output does not match expected result!
    Expected output (16.020 sec):



    Actual output: (15.678 sec):

        tmp_repo/mypy/semanal.py:553: error: "None" has no attribute "line"
        tmp_repo/mypy/semanal.py:2405: error: No overload variant of "__setitem__" of "list" matches argument types [builtins.int, mypy.types.Type]
        tmp_repo/mypy/semanal.py:2641: error: No overload variant of "__setitem__" of "list" matches argument types [builtins.int, mypy.types.Type]
        tmp_repo/mypy/semanal.py:3446: error: No overload variant of "__setitem__" of "list" matches argument types [builtins.int*, mypy.types.Type]
        tmp_repo/mypy/checkexpr.py:252: error: No overload variant of "get" of "Mapping" matches argument types [mypy.nodes.Expression]
        tmp_repo/mypy/fixup.py:168: error: "None" has no attribute "bases"
        tmp_repo/mypy/stubgen.py:452: error: Item "Type" of "Optional[Type]" has no attribute "arg_types"
.
.
.
```
This particular set of error messages is particularly persistent, I've gone through a sequence of versions of the daemon logic and I still get this.

### PR DESCRIPTION
**Pull request by gvanrossum**
Fixes #4185.
Fixes #4198.
Fixes #4195.
Fixes #4208.

Also some improvements to mypy/incremental_checker.py and report more stats about in-memory cache.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Ready for review -- this makes the code a little cleaner IMO and fixes two actual issues (one of which was that no trees were reused ever!). I'm not going to be able to address the deeper issue until next week.

**Comment by gvanrossum** [comment]
OK, the last issue should also be fixed. @JukkaL do you have time to review this?

File: mypy/build.py [hunk 1]
```diff
@@ -2290,6 +2285,61 @@ def process_fresh_scc(graph: Graph, scc: List[str], manager: BuildManager) -> No
...
+        # patch_dependency_parents() above.
+        for name in list(tree.names):
+            sym = tree.names[name]
+            subname = id + '.' + name
+            if (sym.kind == MODULE_REF
+                    and sym.node is not None
+                    and sym.node.fullname() == subname
+                    and subname not in st.dependencies):
+                manager.trace("Purging %s" % subname)
+                del tree.names[name]
```
Comment (JukkaL) [inline mypy/build.py]: Can this break some code that assumes that `import m` also brings in `m.submodule`? Say, like people assume that `import os` also gives access to `os.path`.

File: test-data/unit/check-incremental.test [hunk 2]
```diff
@@ -3376,3 +3376,65 @@ def f() -> None:
 [out2]
 [out3]
 [out4]
+
+[case testTreeShadowingViaParentPackage]
```
[the remark this answers is not in the document]
Comment (gvanrossum) [reply test-data/unit/check-incremental.test]: I think that's because in master *no* trees are preserved -- that's #4198, and it completely masks #4208. I suppose I could split the PR in two parts, the part that fixes #4198, at which point #4208 becomes apparent, and then the part that fixes the latter. But that's a fair bit of work. I do know that at some point in the past (I think after the first dmypy PR) I saw the same errors as #4208, and when I was three quarters through this PR I saw those same errors. I am confident that this test demonstrates the specific issue that was fixed.

**Comment by gvanrossum** [comment]
Give it another look. I share your concern that there's still some brittleness left, but I think it's an overall improvement. I don't need this to go out with the release branch though.
