### ISSUE TITLE
mypy thinks that instance variables that implement the descriptor protocol are invoked when accessing them

### ISSUE THREAD

**Issue by glyph** [python/mypy#15822]
**Bug Report**

`__get__` should only be understood to be invoked on descriptors stored in a type's dictionary. But mypy type-checks as if there is a default present. This makes any infrastructure that wraps a decorator impossible to type correctly.

**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&flags=strict&gist=9483880764b49d2ce31d4156c9f4190a

```python
from dataclasses import dataclass

class A:
    pass

class B:
    def __get__(self, instance: A, owner: None=None) -> int:
        return 3

    def __set__(self, instance: A, value: int) -> None:
        print("set:", value)


@dataclass
class W:
    b: B

    def set_b(self, b: B) -> None:
        self.b = b

w = W(B())
w.set_b(B())
print(w.b)
```

**Expected Behavior**

It should type-check without errors, as Python runs it fine.

**Actual Behavior**

```
main.py:19: error: Argument 1 to "__get__" of "B" has incompatible type "W"; expected "A"  [arg-type]
main.py:19: error: Argument 2 to "__get__" of "B" has incompatible type "type[W]"; expected "None"  [arg-type]
main.py:19: error: Argument 1 to "__set__" of "B" has incompatible type "W"; expected "A"  [arg-type]
main.py:19: error: Incompatible types in assignment (expression has type "B", variable has type "int")  [assignment]
Found 4 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 1.4.1
- Mypy command-line flags: `--strict`
- Python version used: 3.11

**Comment by glyph** [comment]
Apologies if this is a dup; I did look through the descriptors topic and there's lots of stuff *adjacent* to this, but I didn't see it reported as such.

**Comment by glyph** [comment]
(Also worth noting that the `@dataclass` seems to be irrelevant; this happens with regular type annotations too with a manual `__init__`.)

**Comment by huix11** [comment]
1

**Comment by jace** [comment]
I've run into the same issue trying to use a Protocol to declare a function's namespace (as is usually set by decorators):

https://gist.github.com/mypy-play/3dc9a75bf220a34c461fe2ed2523f61b

IMO, Mypy should invoke the descriptor protocol only when the variable is a ClassVar (implicit or explicit):

```python
class Foo:
    a: ClassVar[Descriptor]  # Variable type is the return type of Descriptor.__get__
    b = Descriptor()  # Implicit ClassVar descriptor
    c: Descriptor  # The type is just `Descriptor`
```

**Comment by ilevkivskyi** [comment]
FWIW this works correctly on current master (I didn't check any released versions, there is a chance it will only work in 1.16).
