### PR TITLE
Reject invalid ParamSpec locations

### LINKED ISSUE #13966: Bad error message for arguments between ParamSpec P.args and P.kwargs
**Bug Report**

`ParamSpec` `P.args` and `P.kwargs` are not defined when using explicit keyword argument.

**To Reproduce**

This code would be used to type [anyio.run()](https://anyio.readthedocs.io/en/stable/api.html#anyio.run).

[Link to mypy-play](https://mypy-play.net/?mypy=latest&python=3.10&gist=1455472f1f06b31424f3a0f13e28f3a0)

```python
from typing import ParamSpec, Awaitable, TypeVar, Callable, Any

P = ParamSpec("P")
T_Retval = TypeVar("T_Retval")

def run(
    func: Callable[P, Awaitable[T_Retval]],
    *args: P.args,
    backend: str = "asyncio",
    backend_options: dict[str, Any] | None = None,
    **kwargs: P.kwargs,
) -> T_Retval:
    pass
```

but it works without explicit keyword arguments.

```python
from typing import ParamSpec, Awaitable, TypeVar, Callable, Any

P = ParamSpec("P")
T_Retval = TypeVar("T_Retval")

def run(
    func: Callable[P, Awaitable[T_Retval]],
    *args: P.args,
    **kwargs: P.kwargs,
) -> T_Retval:
    pass
```

**Expected Behavior**

It should be able to type and recognize that `run()` passes the rest of the arguments to the function `a()`.

```python
async def a(b: str, c: int) -> None:
    pass

run(a, "", c=0)
```

**Actual Behavior**

```
main.py:10: error: Name "P.args" is not defined
main.py:13: error: Name "P.kwargs" is not defined
```

**Your Environment**

- Mypy version used: 0.981
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10

### LINKED ISSUE #14382: Default value for Generic self is erased by @dataclass
Note that pyright has a similar behavior so I am not sure whether it is a bug per se but I do believe that it is an incorrect behavior.

**Bug Report**

It is possible to specify the default value for a generic self using `__init__` parameter type hint or `__new__` return type hint. However, when a `@dataclass` decorator is applied to the class and when it generates `__init__`, the `__new__` definition gets erased.
 
**To Reproduce**

https://mypy-play.net/?mypy=latest&python=3.11&gist=13b4e50085788299b532d56cf70c3eb8

**Expected Behavior**
Mypy must show:
```
main.py:22: note: Revealed type is "__main__.User[Literal['NotLoggedIn']]"
```

And it does show it if the `@dataclass` gets commented out, `init=False` is passed to the dataclass, or if the following `__init__` is added to the class:
```python
def __init__(self: "User[Literal['NotLoggedIn']]", name: str) -> None:
    self.name = name
```

**Actual Behavior**
```
main.py:21: error: Need type annotation for "f"  [var-annotated]
main.py:22: note: Revealed type is "__main__.User[Any]"
```
**Your Environment**

- Mypy version used: 0.991
- Python version used: 3.11

**Relevant links**

https://github.com/python/mypy/issues/4236

### LINKED ISSUE #14622: False-negative: ParamSpec.args annotating non-*args
Per [the docs](https://docs.python.org/3/library/typing.html#typing.ParamSpec),  "P.args ... should only be used to annotate *args":

```python
from typing import ParamSpec

P = ParamSpec('P')


def f(args: P.args) -> None:
    g(*args)


def g(a: str) -> None:
    print(type(a))
    
    

f(42)
```

Gist:
https://mypy-play.net/?mypy=latest&python=3.11&gist=28f03ed1b30e9707edfd080095b6a868

### LINKED ISSUE #14832: Invalid ParamSpec usage in function with added kwargs not reported as error
**Bug Report**

According to [PEP-612](https://peps.python.org/pep-0612/#id2),
> Placing keyword-only parameters between the *args and **kwargs is forbidden.

However, `mypy` doesn't reject such usage.

**To Reproduce**

```python
from __future__ import annotations

from typing import TypeVar, ParamSpec, Protocol

_P = ParamSpec('_P')
_R = TypeVar('_R', covariant=True)

class BetterCallable(Protocol[_P, _R]):
    def __call__(self, *args: _P.args, x: int, **kwargs: _P.kwargs) -> _R: ...
```

[Playground](https://mypy-play.net/?mypy=master&python=3.11&flags=strict&gist=52dfe0e5ad6b9ba3ddc5c86fac5eb562)

Also consider this code quoted from PEP-612:
```python
from __future__ import annotations
from typing import TypeVar, ParamSpec, Callable, Concatenate

P = ParamSpec('P')

def add(f: Callable[P, int]) -> Callable[Concatenate[str, P], None]:

  def foo(s: str, *args: P.args, **kwargs: P.kwargs) -> None:  # Accepted
    pass

  def bar(*args: P.args, s: str, **kwargs: P.kwargs) -> None:  # Rejected
    pass

  return foo                                                   # Accepted
```

And here's [another playground](https://mypy-play.net/?mypy=master&python=3.11&flags=strict&gist=07b4aeefc24951a3eb28b56e4a07eca0).

**Expected Behavior**

In first case the `__call__` definition should be flagged as error.

In second case the behaviour should match the inline comments.

**Actual Behavior**

In first case no errors are found.

In second case `foo` is rejected due to named arguments (this violates PEP-612, but is easily fixable with `__s` arg name instead, as usual, error message can be improved here). while `bar` is accepted, also violating the PEP:
```
main.py:14: error: Incompatible return value type (got "Callable[[Arg(str, 's'), **P], None]", expected "Callable[[str, **P], None]")  [return-value]
main.py:14: note: This is likely because "foo" has named arguments: "s". Consider marking them positional-only
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: master, 1.0.1
- Mypy command-line flags: `--strict` and without it
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10, 3.11

### PR DESCRIPTION
**Pull request by sterliakov**
Fixes #14832, fixes #13966, fixes #14622.

Still does not report error in #14777, I'll work separately on that.

Move all `ParamSpec` validity checking to `typeanal.py`. Stop treating `P.args` and `P.kwargs` as binding - only bare typevar makes it available in scope. Reject keyword arguments following `P.args`.

This also makes one more conformance test pass. Diff (against baseline on current master):

```diff
diff --git a/conformance/results/mypy/generics_paramspec_components.toml b/conformance/results/mypy/generics_paramspec_components.toml
index 66a386a..86ba0b0 100644
--- a/conformance/results/mypy/generics_paramspec_components.toml
+++ b/conformance/results/mypy/generics_paramspec_components.toml
@@ -8,10 +8,18 @@ Does not report error when keyword argument is specified between P.args and P.kw
 output = """
 generics_paramspec_components.py:17: error: Use "P.args" for variadic "*" parameter  [valid-type]
 generics_paramspec_components.py:17: error: Use "P.kwargs" for variadic "**" parameter  [valid-type]
+generics_paramspec_components.py:20: error: ParamSpec components are not allowed here  [valid-type]
 generics_paramspec_components.py:23: error: Use "P.kwargs" for variadic "**" parameter  [valid-type]
+generics_paramspec_components.py:26: error: ParamSpec must have "*args" typed as "P.args" and "**kwargs" typed as "P.kwargs"  [valid-type]
+generics_paramspec_components.py:30: error: ParamSpec "P" is unbound  [valid-type]
+generics_paramspec_components.py:35: error: ParamSpec components are not allowed here  [valid-type]
+generics_paramspec_components.py:36: error: ParamSpec components are not allowed here  [valid-type]
+generics_paramspec_components.py:38: error: ParamSpec must have "*args" typed as "P.args" and "**kwargs" typed as "P.kwargs"  [valid-type]
+generics_paramspec_components.py:41: error: ParamSpec must have "*args" typed as "P.args" and "**kwargs" typed as "P.kwargs"  [valid-type]
 generics_paramspec_components.py:49: error: Argument 1 has incompatible type "*P.kwargs"; expected "P.args"  [arg-type]
 generics_paramspec_components.py:49: error: Argument 2 has incompatible type "**P.args"; expected "P.kwargs"  [arg-type]
 generics_paramspec_components.py:51: error: Argument 1 has incompatible type "int"; expected "P.args"  [arg-type]
+generics_paramspec_components.py:60: error: Arguments not allowed after ParamSpec.args  [valid-type]
 generics_paramspec_components.py:70: error: Argument 1 has incompatible type "*P.args"; expected "int"  [arg-type]
 generics_paramspec_components.py:70: error: Argument 2 has incompatible type "int"; expected "P.args"  [arg-type]
 generics_paramspec_components.py:72: error: Argument 1 has incompatible type "*P.args"; expected "int"  [arg-type]
@@ -21,14 +29,6 @@ generics_paramspec_components.py:83: error: Argument 3 to "foo" has incompatible
 generics_paramspec_components.py:98: error: Argument 2 to "twice" has incompatible type "str"; expected "int"  [arg-type]
 generics_paramspec_components.py:98: error: Argument 3 to "twice" has incompatible type "int"; expected "str"  [arg-type]
 """
-conformance_automated = "Fail"
+conformance_automated = "Pass"
 errors_diff = """
-Line 20: Expected 1 errors
-Line 26: Expected 1 errors
-Line 30: Expected 1 errors
-Line 35: Expected 1 errors
-Line 36: Expected 1 errors
-Line 38: Expected 1 errors
-Line 41: Expected 1 errors
-Line 60: Expected 1 errors
 """
diff --git a/conformance/results/mypy/version.toml b/conformance/results/mypy/version.toml
index 3030c9f..42ef13b 100644
--- a/conformance/results/mypy/version.toml
+++ b/conformance/results/mypy/version.toml
@@ -1,2 +1,2 @@
-version = "mypy 1.14.0+dev.14974072c0a70f8ca29c17c740475187b800e714"
-test_duration = 8.4
+version = "mypy 1.14.0+dev.e580045ce62e3c8ccd17fb575f60ec7ede65c01b"
+test_duration = 8.2
diff --git a/conformance/results/results.html b/conformance/results/results.html
index e6ef533..1278a53 100644
--- a/conformance/results/results.html
+++ b/conformance/results/results.html
@@ -158,8 +158,8 @@
         </header>
         <div class="table_container"><table><tbody>
 <tr><th class="col1">&nbsp;</th>
-<th class='tc-header'><div class='tc-name'>mypy 1.14.0+dev.14974072c0a70f8ca29c17c740475187b800e714</div>
-<div class='tc-time'>8.4sec</div>
+<th class='tc-header'><div class='tc-name'>mypy 1.14.0+dev.e580045ce62e3c8ccd17fb575f60ec7ede65c01b</div>
+<div class='tc-time'>8.2sec</div>
 </th>
 </tr>
 <tr><th class="column" colspan="2">
```

### CODE REVIEW

**Review by JukkaL — APPROVED** [review]
Thanks, I'm glad to see several bugs fixed. Looks good!

**Comment by sterliakov** [comment]
Amazing. I wasn't able to reproduce the problem on a local clone, and indeed it was apparently a glitch: another primer run did not produce an error there.

**Comment by cdce8p** [comment]
> > Actually, the home-assistant error might be false positive. Can you look at it?
>
> Amazing. I wasn't able to reproduce the problem on a local clone, and indeed it was apparently a glitch: another primer run did not produce an error there.

Not it wasn't a glitch. I just fixed it already after seeing your PR 😉
https://github.com/home-assistant/core/pull/133044

**Comment by sterliakov** [comment]
Ough! I was moderately certain that I reviewed primer hits and found them to be correct, but did not expect a fix in between... Please comment next time you do that!:)

File: test-data/unit/check-parameter-specification.test [hunk 1]
```diff
@@ -2144,7 +2165,7 @@ from typing_extensions import ParamSpec
 P= ParamSpec("P")
 T = TypeVar("T")
 
-def smoke_testable(*args: P.args, **kwargs: P.kwargs) -> Callable[[Callable[P, T]], Type[T]]:
+def smoke_testable(*args: P.args, **kwargs: P.kwargs) -> Callable[[Callable[P, T]], Type[T]]:  # E: ParamSpec "P" is unbound
```
Comment (hauntsaninja) [inline test-data/unit/check-parameter-specification.test:2168]: this is functionality that mypy is losing, right? (you can see what it's going for / the OtherClass example is interesting)

i think that's fine (and seems fine looking at the new primer warnings), but maybe we should clarify this test case? e.g. the comments are out of date

**Review by hauntsaninja — APPROVED** [review]
This looks awesome! Makes things cleaner too.

I had one small nit regarding a test case

File: test-data/unit/check-parameter-specification.test (hunk 1 above)
Comment (sterliakov) [reply test-data/unit/check-parameter-specification.test]: Thanks! I've removed this test. This definition is not allowed by [PEP612](https://peps.python.org/pep-0612/#the-components-of-a-paramspec):

> These “properties” can only be used as the annotated types for *args and **kwargs, accessed from a ParamSpec already in scope.

*args and **kwargs do not add a ParamSpec to the scope, so the test was never conformant. IMO this is an extremely rare case: "given a set of arguments, produce a callable depending on those". I think dropping this implementation-defined extension to prevent silently accepting and misinterpreting invalid typing constructs is sensible.

**Comment by sterliakov** [comment]
In the meantime `prefect` fixed one occurrence of arg between *args and **kwargs and added a few more invalid functions of the same kind:)

**Comment by hauntsaninja** [comment]
There's nothing that puts P into scope / nothing that tells a type checker what P is.

If you changed `def decorate(func: Plugin[ThemeConfig], /) -> Plugin[ThemeConfig]:` to `def decorate(func: Callable[P, ThemeConfig], /) -> Callable[P, ThemeConfig]:` that would do the job. (Looks like Plugin is basically just an alias for Callable)

It's also unclear to me why you need an inner function at all. Seems like you could just `return func` from `decorate` and not bother with `wrapper`. This would also be a fix.

**Comment by ThirVondukr** [comment]
Hello, I'm facing issue with this PR since updating mypy:
```py
from typing import ParamSpec, Generic

P = ParamSpec("P")


class FunctionArgs(Generic[P]):
    args: P.args
    kwargs: P.kwargs
```
```py
def something(func: Callable[P, Any]) -> FunctionArgs[P]: ...
```
```py
$ mypy code.py
code.py:7:11: error: ParamSpec components are not allowed here  [valid-type]
        args: P.args
              ^
code.py:8:13: error: ParamSpec components are not allowed here  [valid-type]
        kwargs: P.kwargs
```

I'm not sure if it's "compatible" with current typing PEPs/Spec, but this seems like a valid use case to me.

**Comment by sterliakov** [comment]
This is not allowed by typing spec and has never been actually supported by
mypy: this PR only adds an explicit error for this invalid definition,
previously args and kwargs were (most likely) silently treated as Any.

As for the "why" bit: given an instance of FunctionArgs, we should be able
to assign some type to its attributes, including `args`. That is impossible
with ParamSpec, its components have no meaning separately. Given a
paramspec for `def fn(x: int) -> None`, both `args: tuple[int]; kwargs: {}`
and `args: tuple[()]; kwargs: {"x": int}` would be equally valid
resolutions, so the type of args is undefined. This can be supported as a
typechecker extension beyond the spec, of course, by requiring that args
and kwargs are only used together, but that would require special-casing
all class attributes similar to ParamSpec itself, and likely provides very
little ROI.

**Comment by ThirVondukr** [comment]
I see, so main issue is not being able to statically type it since function could be called differently, thanks.
I guess my actual use case is a bit different?
```py
@dataclasses.dataclass(slots=True, kw_only=True, frozen=True)
class TaskInstance(Generic[P, TResult]):
    task: TaskDefinition[P, TResult]
    args: P.args
    kwargs: P.kwargs


@dataclasses.dataclass(kw_only=True)
class TaskDefinition(Generic[P, TResult]):
    func: Callable[P, Awaitable[TResult]]

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> TaskInstance[P, TResult]:
        return TaskInstance(
            task=self,
            args=args,
            kwargs=kwargs,
        )
```
This seems ok since we know which arguments were used when creating instance of `TaskInstance`, but I guess if it's currently not supported or isn't planned I'll just type it as `tuple[object, ...], dict[str, object]` or something like that 😅
