### ISSUE TITLE
TypeAlias does not work with Union types

### ISSUE THREAD

**Issue by realharry** [python/mypy#11665]
**Bug Report**

Union types are valid types, just like any other types. That's at least _my_ expectation. However, you cannot currently type alias union types.

For example,

```python
X: TypeAlias = int | str  #   line 3

def f(b: bool) -> X:     # line 6
    if b:
        return 3
    else:
        return "three"
```

Mypy will issue the following errors:

```
typealias_test.py:3: error: Variable "typing.TypeAlias" is not valid as a type
typealias_test.py:6: error: Variable "typealias_test.X" is not valid as a type
```

**To Reproduce**

1. Create a type alias for a union type, using either `typing.Union` or the 3.10 vert bar syntax.
2. You can explicitly declare the type alias implicitly or explicitly with typing.TypeAlias.
3. Run mypy check. Union type aliases are not recognized as type by mypy.

**Expected Behavior**

Union types should be treated as just any other types.

**Actual Behavior**

Union types cannot be type-aliased in the current impl of mypy.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.10.0
- Operating system and version: Ubuntu 20.04.

**Comment by realharry** [comment]
It seems slightly more complicated than I initially thought. Type alias `X = Union[T1, T2]`  works. However, X: TypeAlias = Union[T1, T2]`  does not work. For the 3.10 syntax, neither `X = T1 | T2` nor `X: TypeAlias = T1 | T2` work.

**Comment by hauntsaninja** [comment]
All variants you've described should work on master and in the upcoming 0.920 release

**Comment by jborman-exos** [comment]
I have the same specs as @realharry and am experiencing the same issue. Using an explicit `Union[T1, T2]` works however the union operator `|` does not.

**Comment by hauntsaninja** [comment]
These work with newer mypy (e.g. 0.931).
There's still some issues with generic type aliases ( #12211 ), but most type aliases are not generic.
