### ISSUE TITLE
Module X has no attribute Y, since version 0.700 (works fine with 0.670)

### ISSUE THREAD

**Issue by Dobiasd** [python/mypy#7182]
Here is a minimal setup to reproduce the issue reliably with `docker build .`.

`Dockerfile`:

```
FROM python:3.7

RUN pip install --upgrade pip
#RUN pip install mypy==0.670
RUN pip install mypy==0.711

WORKDIR stuff

ADD mypackage mypackage
ADD setup.py .

RUN pip install .

RUN mypy --strict ./mypackage/tests.py

```

`mypackage/__init__.py`:

```Python
from ._implementation import foobla

name = "mypackage"

```

`mypackage/_implementation.py`:

```Python
def foobla() -> int:
    return 42

```

`mypackage/tests.py`:

```Python
from mypackage import foobla

foobla()

```

`setup.py`:

```Python
import setuptools

setuptools.setup(
    name="mypackage",
    version="0.1.0"
)

```

With `mypy==0.670` everything works fine, but with `mypy==0.711` the result is:

```
Step 8/8 : RUN mypy --strict ./mypackage/tests.py
 ---> Running in 4544be44e618
mypackage/tests.py:1: error: Module 'mypackage' has no attribute 'foobla'
```

**Comment by Dobiasd** [comment]
Ah, damn. Now [I see it can be solved by adding `--implicit-reexport`](https://github.com/python/mypy/issues/7030), i.e.,

replacing:
```
RUN mypy --strict ./mypackage/tests.py
```

with:
```
RUN mypy --strict --implicit-reexport ./mypackage/tests.py
```

and everything works fine.

Sorry for opening this superfluous issue.

**Comment by Tlaloc-Es** [comment]
This still doesn't work for version 0.990?

I have the following case

```
from src.package.a import a
from src.package.b import b

__all__ = ["a", "b"]
```

and I get the error:

```
src.package has no attribue "a" [attr-defined]
```

**Comment by ahopkins** [comment]
> This still doesn't work for version 0.990?

I am seeing this with 0.991

**Comment by AlexWaygood** [comment]
- Please check that the problem still exists on mypy v1.0.1. Bugs are fixed in every mypy release, and we won't be backporting any fixes to v0.991 now that v1.0.1 has been released.
- If the problem still exists on mypy 1.0.1, please open a new issue rather than posting on an issue regarding v0.700, that has been closed for four years now.

**Comment by ahopkins** [comment]
Sorry, still trying to debug my way thru this and come up with a good minimal example. I was posting so I would get any updates since I saw a recent discussion here.

**Comment by AlexWaygood** [comment]
> I was posting so I would get any updates since I saw a recent discussion here.

Well, my comment was aimed at the other recent commenter, just as much as you :)
