### ISSUE TITLE
[2.1 regression] Incompatible types in capture pattern, can't assign a variable when using string unpacking

### ISSUE THREAD

**Issue by WibblyGhost** [python/mypy#21537]
**Bug Report**

After upgrading to specifically MyPy 2.1.0 from 2.0.0 on Python 3.13.13 causes a `Incompatible types in capture pattern (pattern captures type "str", variable has type "Literal['TDMA', 'FDMA', 'NATIVE']")  [misc]` error.

Looking at your release page (https://mypy.readthedocs.io/en/stable/changelog.html) the only particular ticket that looks familiar is https://github.com/python/mypy/pull/21405.

**To Reproduce**

```python
def run_funct(cmd: str, *arguments: str) -> None:
    try:
        start_time = time()
        match cmd, *arguments:
            case ("aff", address, "True" | "true" | "False" | "false" as sd):
                address = group_address(address)
                CONSOLE.aff(address, sd=sd.lower() == "true")
            case ("deaff", address):
                address = group_address(address)
                CONSOLE.deff(address)
            case ("set_phase", "TDMA" | "FDMA" | "NATIVE" as phase):  # ERROR: "str", variable has type "Literal['TDMA', 'FDMA', 'NATIVE']
                CONSOLE.call_rate = call_rate_mapping[phase]
```
Note: I tried creating a gist in the playground but it doesn't seem to pickup the errors.
Note: This only occurs when `as phase` is added to set the variable name.

**Expected Behavior**

MyPy shouldn't be treating the `as phase` setting as setting to a Literal, or should be able to support comparisons with `str`. Setting any string through the match statement with tuple[str] unpacking set for a tuple of [str, str] should be allowed to be assigned to a varible

**Actual Behavior**

```
mypy src
src/consolesimulator3/scripts/run_console_service.py:78: error: Incompatible types in capture pattern (pattern captures type "str", variable has type "Literal['TDMA', 'FDMA', 'NATIVE']")  [misc]
Found 1 error in 1 file (checked 34 source files)
```

**Your Environment**
```toml
[tool.mypy]
exclude = [".*tests/"]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
extra_checks = true
implicit_optional = true
no_implicit_reexport = true
no_warn_no_return = true
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["beaupy.*", "rpyc.*", "construct.*", "sip_parser.*"]
ignore_missing_imports = true
```

**Comment by ilevkivskyi** [comment]
cc @hauntsaninja

**Comment by hauntsaninja** [comment]
Your repro is incomplete (cuts off half way and doesn't define a lot of symbols it uses), could you try sharing something standalone?

**Comment by WibblyGhost** [comment]
I will attempt to create a reproducible build but it's hard to share complete code snippets due to company code.

It seems that this error is not driven by pre-defined type casting, if I define `phase: str`, then sure it seems to work and the Literal can get assigned to a str. However, if I define `phase: Literal["TDMA", "FDMA", "NATIVE"]` then it returns the error again.

*There does seem to be some very strange behavior when sticking a `reveal_type` on my 'Console' class before the actual match statement, then the errors go away. On why the class is impacting the way MyPy is treating the match statement is beyond me.* 

^ I think this has a play into the error. 🤷‍♂️ ^

Noting that the `CONSOLE` variable is well type casted in the main() function.

---

<img width="900" height="355" alt="Image" src="https://github.com/user-attachments/assets/8b669717-af6a-4d88-b9f9-19f63b7bd904" />

What do you mean the variable takes type `Literal[...]` that's already defined above!

---

<img width="865" height="395" alt="Image" src="https://github.com/user-attachments/assets/11e082da-8117-42cb-9e05-72c8f252851f" />
