### PR TITLE
Fixes to union simplification, isinstance and more

### LINKED ISSUE #1914: isinstance(x, (T1, T2)) won't narrow the type of x when NamedTuple is involved.
Test case:

``` python
from typing import NamedTuple, Union

A = NamedTuple('A', [('y', int)])
B = NamedTuple('B', [('x', int)])
C = NamedTuple('C', [('x', int)])

def foo(a: Union[A, B, C]):
    if isinstance(a, (B, C)):
        a.x
        b = a # type: Union[B, C]
```

This fails with:

```
1.py: note: In function "foo":
1.py:9: error: Some element of union has no attribute "x"
1.py:10: error: Incompatible types in assignment (expression has type "Union[A, B, C]", variable has type "Union[B, C]")
```

The error happens only when NamedTuple is involved. Otherwise the type of `a` is correctly narrowed to `Union[B, C]` inside the branch.

cc #1328 

```
$ mypy -V
mypy 0.4.3
$ python3 -V
Python 3.5.2
```

### LINKED ISSUE #2978: [Regression: 0.470->0.501] Lots of new errors relating to "uninhabited" in Django-based app code
```
git clone https://github.com/inducer/relate
cd relate
./run-mypy.sh
```

used to work with no warnings in 0.470. Now, it spews this:

```
course/content.py:877: error: <uninhabited> has no attribute "id"
course/content.py:1445: error: <uninhabited> has no attribute "preview_git_commit_sha"
course/content.py:1446: error: <uninhabited> has no attribute "preview_git_commit_sha"
course/utils.py:179: error: <uninhabited> has no attribute "exam"
course/utils.py:533: error: <uninhabited> has no attribute "preview_git_commit_sha"
course/utils.py:534: error: <uninhabited> has no attribute "preview_git_commit_sha"
course/utils.py:583: error: <uninhabited> has no attribute "permissions"
course/enrollment.py:129: error: <uninhabited> has no attribute "roles"
course/enrollment.py:143: error: <uninhabited> has no attribute "permissions"
course/views.py:156: error: <uninhabited> has no attribute "has_permission"
course/flow.py:416: error: <uninhabited> has no attribute "user"
course/flow.py:633: error: <uninhabited> has no attribute "answer"
course/flow.py:830: error: <uninhabited> has no attribute "get_most_recent_grade"
course/flow.py:848: error: Unsupported left operand type for + (some union)
course/flow.py:855: error: Unsupported left operand type for + (some union)
course/flow.py:862: error: Unsupported left operand type for + (some union)
course/flow.py:923: error: <uninhabited> has no attribute "is_submitted_answer"
course/flow.py:924: error: <uninhabited> has no attribute "save"
course/flow.py:1264: error: <uninhabited> has no attribute "get_most_recent_grade"
```

Focusing on the first error:

https://github.com/inducer/relate/blob/fed97182f4e8940bb032a224c5cbcd007a8bd722/course/content.py#L877

it should be clear that `course` is an instance of `Course` (i.e. not None).

### PR DESCRIPTION
**Pull request by JukkaL**
The main change is that unions containing Any are no longer simplified
to just Any. Use proper subtype check for union simplification and
implement proper subtype checks more fully.

This required changes in various other places to keep the existing
semantics and to avoid regressions and inconsistencies.

Fixes #1914.
Fixes #2978.

### CODE REVIEW

File: mypy/subtypes.py [hunk 1]
```diff
@@ -496,52 +497,157 @@ def unify_generic_callable(type: CallableType, target: CallableType,
...
+        new_items = [item for item in t.items
+                     if (not is_proper_subtype(erase_type(item), erased_s)
+                         or isinstance(item, AnyType))]
         return UnionType.make_union(new_items)
     else:
         return t
 
 
-def is_proper_subtype(t: Type, s: Type) -> bool:
+def is_proper_subtype(left: Type, right: Type) -> bool:
```
Comment (ilevkivskyi) [inline mypy/subtypes.py]: ``t`` and ``s`` should also be replaced with ``left`` and ``right`` in the docstring below.

File: test-data/unit/check-unions.test [hunk 2]
```diff
@@ -217,3 +217,147 @@ class M(Generic[V]):
...
+# Union with object
+reveal_type(u(t_o, object())) # E: Revealed type is 'builtins.object*'
+reveal_type(u(object(), t_o)) # E: Revealed type is 'builtins.object*'
+reveal_type(u(t_s, object())) # E: Revealed type is 'builtins.object*'
+reveal_type(u(object(), t_s)) # E: Revealed type is 'builtins.object*'
+reveal_type(u(t_a, object())) # E: Revealed type is 'builtins.object*'
+reveal_type(u(object(), t_a)) # E: Revealed type is 'builtins.object*'
+
+# Union between type objects
+reveal_type(u(t_o, t_a)) # E: Revealed type is 'Union[Type[Any], Type[builtins.object]]'
```
Comment (ilevkivskyi) [inline test-data/unit/check-unions.test]: ``Union[Type[Any], Type[object]]`` and ``Union[type, Type[object]]`` should give the same result, since ``type`` is equivalent to ``Type[Any]`` (at least it is what PEP 484 says). Maybe this could be fixed by adding a special case in spirit of #3012 at the end of ``visit_type_type``.

File: test-data/unit/check-optional.test [hunk 3]
```diff
@@ -547,9 +547,45 @@ a = None # type: Any
...
+T = TypeVar('T')
+S = TypeVar('S')
+def u(x: T, y: S) -> Union[S, T]: pass
+a = None # type: Any
+
+# Test both orders
+reveal_type(u(C(), None))  # E: Revealed type is 'Union[builtins.None, __main__.C*]'
+reveal_type(u(None, C()))  # E: Revealed type is 'Union[__main__.C*, builtins.None]'
+reveal_type(u(a, None))  # E: Revealed type is 'Union[builtins.None, Any]'
+reveal_type(u(None, a))  # E: Revealed type is 'Union[Any, builtins.None]'
```
Comment (ilevkivskyi) [inline test-data/unit/check-optional.test]: These two lines are duplicated here and in the test case above.

Comment (ilevkivskyi) [inline test-data/unit/check-optional.test]: Oh, wait, this test case almost entirely duplicates previous one. Is this intentional? (I suppose both cases are run with ``--strict-optional``)

File: mypy/subtypes.py [hunk 4]
```diff
@@ -496,52 +497,157 @@ def unify_generic_callable(type: CallableType, target: CallableType,
...
+            if len(left.items) != len(right.items):
+                return False
+            for l, r in zip(left.items, right.items):
+                if not is_proper_subtype(l, r):
+                    return False
+            return is_proper_subtype(left.fallback, right.fallback)
+        return False
+
+    def visit_typeddict_type(self, left: TypedDictType) -> bool:
+        # TODO: Does it make sense to support TypedDict here?
```
Comment (ilevkivskyi) [inline mypy/subtypes.py]: If this is supposed to be used only with ``isinstance`` and ``issubclass``, then no, since they fail at runtime for ``TypedDict``s.

File: test-data/unit/check-optional.test [hunk 5]
```diff
@@ -547,9 +547,45 @@ a = None # type: Any
...
+[case testOptionalAndAnyBaseClass]
+from typing import Any, Optional
+class C(Any):
+    pass
+x = None  # type: Optional[C]
+x.foo()  # E: Some element of union has no attribute "foo"
+
+[case testUnionSimplificationWithStrictOptional]
+from typing import Any, TypeVar, Union
+class C(Any): pass
```
Comment (gvanrossum) [inline test-data/unit/check-optional.test]: Ditto.

File: test-data/unit/check-optional.test [hunk 6]
```diff
@@ -547,9 +547,45 @@ a = None # type: Any
...
 reveal_type(u(None, 1))  # E: Revealed type is 'Union[builtins.int*, builtins.None]'
+
+[case testOptionalAndAnyBaseClass]
+from typing import Any, Optional
+class C(Any):
+    pass
+x = None  # type: Optional[C]
+x.foo()  # E: Some element of union has no attribute "foo"
+
+[case testUnionSimplificationWithStrictOptional]
```
Comment (gvanrossum) [inline test-data/unit/check-optional.test]: Test name should be more like "certain unions are not simplified"

File: test-data/unit/check-optional.test [hunk 7]
```diff
@@ -547,9 +547,45 @@ a = None # type: Any
...
+reveal_type(u(None, C()))  # E: Revealed type is 'Union[__main__.C*, builtins.None]'
+reveal_type(u(a, None))  # E: Revealed type is 'Union[builtins.None, Any]'
+reveal_type(u(None, a))  # E: Revealed type is 'Union[Any, builtins.None]'
+reveal_type(u(1, None))  # E: Revealed type is 'Union[builtins.None, builtins.int*]'
+reveal_type(u(None, 1))  # E: Revealed type is 'Union[builtins.int*, builtins.None]'
+
+[case testIsinstanceAndOptionalAndAnyBase]
+from typing import Any, Optional
+
+class A(Any): pass
```
Comment (gvanrossum) [inline test-data/unit/check-optional.test]: Also use a base of type Any.

File: test-data/unit/check-namedtuple.test [hunk 8]
```diff
@@ -427,3 +427,25 @@ from typing import NamedTuple
...
+
+def f(x: a.X) -> None:
+    # The type of x is broken (https://github.com/python/mypy/issues/3016) but we need to
+    # do something reasonable here to avoid a regression.
+    reveal_type(x)
+    x = a.X(1)
+    reveal_type(x)
+[out]
+tmp/b.py:6: error: Revealed type is 'a.X'
+tmp/b.py:8: error: Revealed type is 'Tuple[Any, fallback=a.X]'
```
Comment (JukkaL) [inline test-data/unit/check-namedtuple.test]: This doesn't work because of #3054.

File: mypy/subtypes.py [hunk 9]
```diff
@@ -496,52 +497,157 @@ def unify_generic_callable(type: CallableType, target: CallableType,
...
+            return is_proper_subtype(left.item, right.item)
+        if isinstance(right, CallableType):
+            # This is unsound, we don't check the __init__ signature.
+            return right.is_type_obj() and is_proper_subtype(left.item, right.ret_type)
+        if isinstance(right, Instance):
+            if right.type.fullname() in ('builtins.type', 'builtins.object'):
+                return True
+            item = left.item
+            return isinstance(item, Instance) and is_proper_subtype(item,
+                                                                    right.type.metaclass_type)
```
Comment (JukkaL) [inline mypy/subtypes.py]: This actually looks wrong so I'm going to remove this and add a TODO item.

File: mypy/subtypes.py [hunk 10]
```diff
@@ -496,52 +509,192 @@ def unify_generic_callable(type: CallableType, target: CallableType,
...
+        # matter much.
+        return True
+
+    def visit_deleted_type(self, left: DeletedType) -> bool:
+        return True
+
+    def visit_instance(self, left: Instance) -> bool:
+        right = self.right
+        if isinstance(right, Instance):
+            for base in left.type.mro:
```
Comment (pkch) [inline mypy/subtypes.py]: This breaks on the code snippet from #3069: when `left` refers to a `NamedTuple`, `left.type.mro` is `None`. I'm guessing it can be fixed by adding mro to instances created by `NamedTuple`?

File: test-data/unit/check-isinstance.test [hunk 11]
```diff
@@ -911,7 +911,8 @@ def foo() -> Union[int, str, A]: pass
 
 def bar() -> None:
     x = foo()
-    x + 1  # E: Unsupported left operand type for + (some union)
+    x + 1  # E: Unsupported left operand type for + (some union) \
+           # E: Unsupported operand types for + (likely involving Union)
```
Comment (JukkaL) [inline test-data/unit/check-isinstance.test]: Yeah, this is unfortunate, but this wasn't trivial to fix. I'll create a follow-up issue to address the duplicate messages (and maybe generally improve error messages related to union types0.

File: test-data/unit/check-isinstance.test [hunk 12]
```diff
@@ -1425,4 +1434,17 @@ T = TypeVar('T', bound=A)
...
+    reveal_type(x) # E: Revealed type is 'T`-1'
 [builtins fixtures/isinstance.pyi]
+
+[case testIsinstanceAndTypeType]
+from typing import Type
+def f(x: Type[int]) -> None:
+    if isinstance(x, type):
+        reveal_type(x) # E: Revealed type is 'Type[builtins.int]'
+    else:
+        reveal_type(x)  # Unreachable
```
Comment (JukkaL) [inline test-data/unit/check-isinstance.test]: That could be nice. There are some cases when this is valid, foe example when type checking `AnyStr` some blocks are often unreachable for either `str` or `bytes`, so the required logic may be somewhat involved.

File: mypy/subtypes.py (hunk 10 above)
Comment (JukkaL) [inline mypy/subtypes.py]: If `mro` is `None` during type checking a lot of things might break. The right fix seems to be to populate `mro` always instead of papering over it here. Named tuple initialization is currently broken in some contexts (see #3054, for example).

File: test-data/unit/check-unions.test (hunk 2 above)
Comment (JukkaL) [inline test-data/unit/check-unions.test]: This is not feasible since `Type[Any]` and `type` have different internal representations. We can't have two different types being proper subtypes of each other unless they are the same type -- otherwise the subtyping relation doesn't form a lattice.

**Comment by gvanrossum** [comment]
Whee! Thanks.
